### ISSUE TITLE
IE11 - Datagrid responding slowly

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1020]
Tested build: http://fgpv.cloudapp.net/demo/v1.0.1/samples/index-fgp-en.html?
keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

It seems build v1.0.1 is responding slower than previous builds, especially for buttons below and their combination.
- Click layer to open Data Table
- Click three dots icon and switch from Split View to Maximize view
- From Maximize to Split View
- Click Close icon to close Data Table from Maximize view

**Comment by alyec** [comment]
## IE 11 profiling (low precision)

Procedure used: open index-one.html, open legend, open CESI layer's datagrid, maximize datagrid.  This was done manually so the results are naturally low precision, this is strictly to get an idea if there is an order of magnitude difference in the JS profiles for different viewer versions.

The top four functions (by descending exclusive time) for each version are listed.

v1.4.0-rc1

Function | Count | Inclusive | Exclusive
-------- | ----- | --------- | ---------
appendChild | 14,171 | 2,144.24 | 2,138.24 | DOM
innerHTML | 27,707 | 1,685.18 | 1,681.18 | DOM
setAttribute | 44,494 | 1,405.15 | 1,405.15 | DOM
scrollHeight | 1,120 | 678.07 | 678.07 | DOM

v1.2.0

Function | Count | Inclusive | Exclusive
-------- | ----- | --------- | ---------
appendChild | 10,917 | 1,537.15 | 1,523.15
innerHTML | 17,118 | 1,247.13 | 1,241.12
setAttribute | 35,120 | 928.09 | 928.09
scrollHeight | 1,057 | 518.05 | 518.05

v1.0.2

Function | Count | Inclusive | Exclusive
-------- | ----- | --------- | ---------
appendChild | 9,930 | 1,319.13 | 1,319.13
innerHTML | 11,087 | 1,138.11 | 1,133.11
setAttribute | 34,787 | 709.07 | 709.07
M.prototype.access | 80,412 | 638.06 | 624.06 | http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.1.min.js | 2

v0.19.0

Function | Count | Inclusive | Exclusive
-------- | ----- | --------- | ---------
innerHTML | 6,765 | 1,741.17 | 1,741.17
appendChild | 6,310 | 1,219.12 | 1,218.12
scrollHeight | 1,286 | 932.09 | 932.09
Scope.prototype.$digest | 135 | 13,543.35 | 721.07 | http://fgpv.cloudapp.net/demo/v0.19.0/core.js | 16,161

v0.17.0

Function | Count | Inclusive | Exclusive
-------- | ----- | --------- | ---------
innerHTML | 6,320 | 2,014.20 | 2,012.20
appendChild | 6,258 | 1,230.12 | 1,230.12
Function.apply | 54,857 | 12,291.23 | 847.09
scrollHeight | 1,040 | 713.07 | 713.07

v0.15.0

Function | Count | Inclusive | Exclusive
-------- | ----- | --------- | ---------
innerHTML | 6,124 | 1,856.19 | 1,854.19
appendChild | 6,210 | 1,254.13 | 1,252.13
scrollHeight | 690 | 899.09 | 899.09
Scope.prototype.$digest | 84 | 10,984.10 | 443.04 | http://fgpv.cloudapp.net/demo/v0.15.0/core.js | 17,305

**Comment by alyec** [comment]
IE does not show drastic changes between our versions.  DOM is expensive and we should follow @AleksueiR 's guidance on trying to optimize our Angular directives and templates as much as possible.

A couple of notes: uploading large user added layers can blow up the browser fairly easily on low end systems.  Also, some plugins (like site advisor) can bog down IE quite a bit.  We will need to set some minimum standards for baseline usage.

There are some optimizations we can look at.  Web workers are an option since IE11 supports them.  They can alleviate some of the UI lockups from processing pressure, but they don't work with DOM interaction and aren't going to solve everything.  We have a few issues open where they are referenced: #850 #964 .

We can also try to disable some animations during the application startup if we want to go into browser detection: #1274
