### ISSUE TITLE
Datagrid and Click Identify broken for some layers

### ISSUE THREAD

**Issue by cynngah** [fgpv-vpgf/fgpv-vpgf#1053]
Somethings seems to be broken (probably the server) whenever we make any querying on a layer for attributes like for the datagrid, symbology or click identify.

This error is displayed in the console for all failing layers.

![Attrib Loading Failed](http://i.imgur.com/ILEs384.png)

**Comment by james-rae** [comment]
[Airports Layer](http://fgpv.cloudapp.net/demo/v1.0.2/samples/index-fgp-en.html?keys=Airports) seems to be failing often

**Comment by james-rae** [comment]
Have dug around and found the following.

The issue is affecting older builds.  So it's not something we recently broke with a code change.

The error happens when the attribute loader attempts to get metadata on the service.  The request times out.  
However, if running this method directly from the GeoAPI test page, it has no problems.  The only difference I can see is that the requests being made from the application are missing the dojo callback parameter.

```
// direct from geoAPI
http://geoappext.nrcan.gc.ca/arcgis/rest/services/FGP/canadian_airports_with_air_navigation_services_en/MapServer/0?f=json&callback=dojo.io.script.jsonp_dojoIoScript2._jsonpCallback

// geoAPI via viewer
http://geoappext.nrcan.gc.ca/arcgis/rest/services/FGP/canadian_airports_with_air_navigation_services_en/MapServer/0?f=json
```

This might explain the timeout -- the missing function means nothing is picking up the result so the dojo loader thinks nothing has returned. 

What is strange is the exact same code is making the request.  The input URL is the same in both cases, and I've verified both pages are using ESRI API 3.14. 

Also, when testing with RCS key `JOSM`, it loads fine and the request does not have the dojo callback (also odd, since the code is specifically setting it)

**Comment by cynngah** [comment]
Layers for some reason load properly if the default basemap (first in config) is in Mercator.

**Comment by james-rae** [comment]
Another difference worth exploring is that the test page in GeoAPI is not using a proxy

**Comment by dan-bowerman** [comment]
The map I'm looking at with this issue (http://section917.cloudapp.net/TRILAT/) is using the following proxy config:

```
<?xml version="1.0" encoding="utf-8" ?>
<ProxyConfig allowedReferers="*" mustMatch="true">
    <serverUrls>
        <serverUrl url="http://services.arcgisonline.com" matchAll="true"/>
        <serverUrl url="http://cgns.nrcan.gc.ca/wmsu/cubeserv.cgi" matchAll="true"/>
        <serverUrl url="http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en" matchAll="true"/>
        <serverUrl url="http://cabin.cciw.ca/cabin/cabin_cr.asp" matchAll="true"/>
		<serverUrl url="http://cabin.cciw.ca/cabin_ows.asp" matchAll="true"/>
        <serverUrl url="http://atlas.gc.ca/cgi-bin/atlaswms_en" matchAll="true"/>
        <serverUrl url="http://geogratis.gc.ca/maps/CBMT" matchAll="true"/>
        <serverUrl url="http://geoportal.gc.ca/arcgis/services/Arctic_Voyage_Planning_Guide_ENG/MapServer/WMSServer" matchAll="true"/>
        <serverUrl url="http://maps.geogratis.gc.ca/wms" matchAll="true"/>
        <serverUrl url="http://geo.weather.gc.ca/geomet" matchAll="true"/>
        <serverUrl url="http://geoappext.nrcan.gc.ca/arcgis/rest/" matchAll="true"/>
        <serverUrl url="http://utility.arcgisonline.com/arcgis/" matchAll="true"/>
		<serverUrl url="http://devmap.on.ec.gc.ca/ArcGIS/" matchAll="true"/>
		<serverUrl url="http://maps-cartes.ec.gc.ca/ArcGIS/" matchAll="true"/>
		<serverUrl url="http://sncr01wbingsdv1.ncr.int.ec.gc.ca/arcgis/" matchAll="true"/>
		<serverUrl url="http://ec.gc.ca/arcgis/" matchAll="true"/>
		<serverUrl url="http://mapservices.gov.yk.ca/arcgis/" matchAll="true"/>
		<serverUrl url="http://geoappext.nrcan.gc.ca/arcgis/rest/" matchAll="true"/>
		<serverUrl url="https://gcgeo.gc.ca/" matchAll="true" />
    </serverUrls>
</ProxyConfig>
```

**Comment by james-rae** [comment]
RCS key `Airports` will trigger the error if the map launches in Lambert projection.  It will not trigger if the map launches in Mercator projection.

RCS key `JOSM` will work fine in both cases.

Inspecting the network traffic, it appears that sometimes requests (for both keys) are made with `jsonp`, and sometimes not. The [esriRequest](https://developers.arcgis.com/javascript/3/jshelp/inside_esri_request.html) utility is designed to drop `jsonp` when it can get around it; in this case it would be due to CORS support on both servers.

Also, network traffic indicates that the failed request actually returns data.  Something in the DOJO/ESRI code is failing to realize it returned and process it, resulting in a timeout.

Attempting to upgrade to ESRI JS.API `v3.17` did not solve the issue.

Moving the layer load from RCS to config file did not solve the issue.  However, if the layer is in both spots, the issue does not trigger.

Was able to verify that other `v10.11` servers would succesfully load when `Airports` would fail.

Have verified that `dojo.xhrGet` is the method initiating the failed call, not `dojo.io.script.get`

Outstanding questions

* What is it about the basemaps that cause an unrelated web request to fail.  Is something in the intialization flow silently erroring, causing something else not to be set up correctly?
* What happened to make this issue appear?  Airports load fine in `v1.0.0-rc3`
* Can we find a layer that fails that is on a different domain (i.e. not hosted on `http://geoappext.nrcan.gc.ca`)

**Comment by mweech** [comment]
leaving bug open.  to be revisited.

**Comment by james-rae** [comment]
Nov 1, 2016 -- Airports layer loads just fine in Lambert.  :confounded:

**Comment by mweech** [comment]
Service in question is no longer available.  Cannot reproduce.
