### ISSUE TITLE
Switching basemap projections changes scale

### ISSUE THREAD

**Issue by cynngah** [fgpv-vpgf/fgpv-vpgf#1068]
So when we switch basemap projections, we get a different scale for Mercator and Lambert.

This is because zoom level is stored on basemap switch instead of scales when bookmarking. However, the scales for the same zoom level is different for different projections (ie. the scale for zoom level 4 for Lambert is 17.5million, while for Mercator is around 37million). If we add a third projection where zoom level 4 has a vastly different scale, it could pose a problem. Or if we store a level that's present in one projection and not in the other, it could break (Mercator goes down to level 23 while Lambert only goes to level 17).

In order to fix this, we would probably have to store scale in the bookmark instead of zoom level, but it makes the bookmark much larger. Or if a smaller bookmark is preferred over having a more accurate scale.

**Comment by james-rae** [comment]
Storing scale is probably the most direct solution.  The size will go from ~2 chars for zoom level to up to 10-12 chars for scale, obviously depends on the current scale.  

If we want to go hardcore on saving space, we could introduce a smaller key (or a 2nd alternate small key) for the basemap schemas.  The currently have long descriptive names like `LOD_ESRI_World_AuxMerc_3857`, if we had a 2nd key like `A`, we could store that in conjunction with scale level.  When the app parses the bookmark, it would look up the scale for the provided basemap schema & level, then find the closest scale in the new basemap schema.  Would mean writing more code to save ~8-10 characters.

**Comment by mweech** [comment]
@spencerwahl will need to weigh in on this..

**Comment by spencerwahl** [comment]
Notes from short discussion in the planning meeting;

- Storing the scale is fine, the space change really shouldn't be that much of a problem
- Need to add a Bookmark Schema version on to the bookmark (Id recommend putting it as the first item)
- Need to add/use a different API call for zooming from the bookmark or use a function that takes a scale and returns the correct zoom level for a projection

**Comment by milesap** [comment]
Cannot get desired behaviour - either zoom level is correct but location is wrong or vice versa. Currently, bookmark uses the same level between different projections and does not need a reference to the basemap we are switching to. I have tried the following:

- Make bookmarks save scale instead of level
- Look ahead at the basemap we are switching to (in the config), computing the new lod level by finding the new lod with the smallest scale difference to the current lod scale.
- Zooming to that level in the current extent inside the `loadNewProjection` function 
- Then run the existing code:

        currentConfig.map.initialBasemapId = basemapId;
        geoService.assembleMap();
