### ISSUE TITLE
Layer loading issue for imported Shapefile

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1103]
Tested build: http://fgpv.cloudapp.net/demo/v1.1.0/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
 Test Data
 Shapefile: 
[ne_10m_ports.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/432787/ne_10m_ports.zip)

When importing Shapefile to FGP, it displayed "Loading layer..." status and never finished, even the layer map points have already added to the map.
![image](https://cloud.githubusercontent.com/assets/18723160/17897560/97ce991e-6922-11e6-871b-cd332c4965d1.png)

**Comment by AleksueiR** [comment]
This seems to affect `.csv` and `.json` files as well.

**Comment by james-rae** [comment]
Will fix alongside https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1041

**Comment by james-rae** [comment]
Latest update to ESRI Terraformer, `v1.0.5`, https://github.com/Esri/terraformer-arcgis-parser, changed the way it processes object ids. `v1.0.4` would take any value, whereas `v1.0.5` would validate them. We were assigning object ids using the array index, meaning the first feature would be given oid `0`.  This was causing the first feature to not have an object id, and thus would crash the attribute indexer and anything else relying on the property.

Troubleshooting was difficult, as `npm install` would not update the library on the local dev copy of geoApi, making it so the issue would only appear if run via the viewer application.  As well, our current issue with blocked github files made version diagnosis harder than it should be.  Issue took longer than original estimate due to these factors.
