### ISSUE TITLE
Export Map Component is Configurable

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1158]
Configuration file will allow for:
- [x] functionality to be disabled
- [x] define the Esri Print Service to use

**Comment by jolevesq** [comment]
Export map, in geoApi, is already configurable for the Esri print service. For the template name, it is not implemented because we can't use template. This is because of the large user added layer. Template will have to be "custom" build in the viewer. In GCViz we worked on a custom print where the viwer would read the html template then generate the form to fill for the info. This way it isi easy to build nay kind of template.

**Comment by AleksueiR** [comment]
Export option will be removed from the side menu if the `exportMapUrl` is not specified in the config.
