### ISSUE TITLE
Create Template for Map Export

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1159]
Print service template that applies a map scale and north arrow to the initial image export request.

**Comment by jolevesq** [comment]
We have a template with north arrow and scale bar for GCViz. I will ask the person in charge to add it to FGP server

**Comment by jolevesq** [comment]
This is the result from the default template for GCViz. If we like it we can take the same template

<img width="1004" alt="screen shot 2016-09-20 at 1 41 03 pm" src="https://cloud.githubusercontent.com/assets/3472990/18681904/070fe334-7f38-11e6-9b3b-3e232300672e.png">

**Comment by jolevesq** [comment]
The template is done but it creates problem when we want to merge user added layers. Because there is items like scalebar and north arrow, the size of the image is not the size of the map. It is not possible to apply the offset because we don't know the gap.

We will try to grab the info from the viewer and add them to the template. The good thing with this approach will be to make it easier to create a custom print template. We had a project to do this in GCViz.

**Comment by mweech** [comment]
Template will not be utilized as this creates issues with combining with a user added layers.  Issue will be closed.
