### ISSUE TITLE
"Plant Hardiness Zones of Canada 2000" attributes will not load

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1184]
When trying to open datatable for "Plant Hardiness Zones of Canada 2000" layer, attributes never finish loading. 

![](https://i.imgur.com/03gFulS.png)

The console shows the following error:

> core.js:12798 TypeError: Cannot read property 'toString' of null
>     at i (http://fgpv.cloudapp.net/demo/develop/lib/core.js:19:6418)
>     at Object.o [as getGraphicIcon](http://fgpv.cloudapp.net/demo/develop/lib/core.js:19:7056)
>     at Object.k [as retrieveSymbol](http://fgpv.cloudapp.net/demo/develop/lib/core.js:35:7203)
>     at http://fgpv.cloudapp.net/demo/develop/lib/core.js:33:27369
>     at Array.forEach (native)
>     at t.u [as createTable](http://fgpv.cloudapp.net/demo/develop/lib/core.js:33:27341)
>     at http://fgpv.cloudapp.net/demo/develop/lib/core.js:33:29660
>     at p.$digest (http://fgpv.cloudapp.net/demo/develop/lib/core.js:3:8263)
>     at http://fgpv.cloudapp.net/demo/develop/lib/core.js:3:9558
>     at i (http://fgpv.cloudapp.net/demo/develop/lib/core.js:1:24398)

**Comment by mweech** [comment]
Need to handle scenarios in which a null value is provided for a column listed as a string.  Layer has a unique value renderer set, however many values have the ZONE_SYMBOL_LABEL field it depends on set to NULL.

**Comment by ChrisLatRNCan** [comment]
In the case of a null value I'll put the OBJECTID as a string in ZONE_SYMBOL_LABEL field.
I could also generate some kind of UUID (maybe to heavy).

**Comment by james-rae** [comment]
I hope I'm not mis-interpreting....this affects [this layer](http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_plant_hardiness_zones/MapServer/0), correct?  Are you referring to `ZONE_SYMBOL_CODE` field?

From the stack trace it looks like the following code is the issue, as `graphicKey` is not an object.

```
if (typeof graphicKey !== 'string') {
   graphicKey = graphicKey.toString();
}
```

We use `graphicKey` to search the renderer and find the correct symbol to use. Since our lookup key is missing we would want to use the default symbol (which, for this service, is also nothing, but I believe Alex's SVG code will insert a default image in that case).

Setting the key to be an object id could give weird results, especially if the object id happens to be the same as a valid `graphicKey` -- you could very well get the wrong image.

I'd think converting the missing value to an empty string would ensure we hit the default symbol, or a defined "empty" symbol if there is one.

**Comment by ChrisLatRNCan** [comment]
I was misinterpreting/misunderstanding. In the debugger, putting any kind of string was  the way to avoid the error. I'll try the empty string. My main challenge here is more about debugging the geoApi (process chain). Johann will help me to push my stuff. Thx

**Comment by AleksueiR** [comment]
GeoApi changes are [PRed](https://reviewable.io/reviews/fgpv-vpgf/geoApi/165#-). This will be demoable when the viewer uses version of geoApi >= v1.0.7-3.
