### ISSUE TITLE
Create Mockups for Thematic Maps Functionality

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1231]
Create UI mockups for the implementation of requirements specified in the thematic maps epic #405 .

**Comment by AleksueiR** [comment]
Some progress, but nothing to show yet. Was working on issues from the usability report.

**Comment by AleksueiR** [comment]
Structured Legend Visibility set Mockups:

![a04 - structured legend visibility sets v0 2](https://cloud.githubusercontent.com/assets/2285779/22694008/8be01aae-ed13-11e6-8efa-f1bb7f20cd8d.png)

**Comment by jolevesq** [comment]
I find option 1 easier to understand for users. Like Mike said, if we put a different colour but same palette for checkboxes inside a group of radio button would be less confusing.

Another option could be to have the colour for everything but disable/hide the checkbox control so user will see only the radio button. This way it will make it obvious on which layer it works and pnly radio button can be use.

**Comment by AleksueiR** [comment]
As I understand, visibility sets do not add anything fundamentally new in terms of how the data is displayed - a visibility set can be represented as a regular group and a user can manually toggle the layers one by one to get the same effect as a visibility set would provide. Visibility sets are a convenience feature, and as such, it should provide some value to the user. One way would be to hide inactive options of the set; another, to focus user's attention on selecting an item from the visibility set when it's triggered.

In essence, **Option 1** is a set of radio button and **Option 3** is a drop down control. Radio buttons are useful where there is lots of screen space and not many options. A user can quickly look over all the radio button options to make sure the correct option is selected before submitting a form, for example. Drop downs, on the other hands, use little space and can display a lot more options; making sure at a glance the correct option is selected is harder with a drop down, but unless the user action is not reversible (like submitting a form), it's not critical.

I do like the simplicity of radio buttons, and if the visibility sets were limited to a small number of layers (two or three), my preference would go to **Option 1**. Since we don't know how many layers map authors will be adding to visibility sets, I suggest **Option 3** as a more universal and providing the most value approach.

@jolevesq using different colour shades for different visibility sets would work, but these colours need a certain level of contrast to be distinguishable from each other. If there are many visibility sets, it might be difficult to generate colours that are visually different enough from each other.

**Comment by alyec** [comment]
I agree with the above, I would only add that one other concern I have with Option 3 is that it may be less obvious what is going on when the user first encounters it.

Given there are trade offs all around I'm generally okay with either approach with a preference for Option 3 alternative.

**Comment by AleksueiR** [comment]
I'll try to update mockups to make sets more visible.

**Comment by james-rae** [comment]
While I personally like the look of `Option 1 Alternative`, I'm fine with any choice

**Comment by jolevesq** [comment]
We have maps with visibility set containing more then 10 layers (all layers are inside one group) and it is not confusing. If we restrict the use of radio button on layer in the same group / level it should not be ok. For sure if we use radio button with layers from different groups it will need dropdown but even with dropdown it will be confusing because layers don't belong together.

@AleksueiR  For the color, it is alway the same color because you can only select one visibility set at a time. In your sample, we just need to put the same color (maybe with a little difference) on the checkbox so user understand it is all related.

I still think option 3 is really not intuitive.

**Comment by milesap** [comment]
My vote is for Option 1 Alternative - I like that it only highlights the visibility set which is being hovered. Easy to see what belongs in the group at first glance. Are we going to make sure that all members of the visibility set are displayed on hover so the user sees all possible choices? If not, would we want to indicate visually that an option is hidden? I'm not saying these are good ideas, I'm just typing out loud 😃

**Comment by mweech** [comment]
I vote Option 1 Alternative.

**Comment by AleksueiR** [comment]
ha-ha, it seems I got outvoted :smiley: 

@milesap In Option 1 all items in a visibility set will be highlighted unless there are too many of them and some are hidden below the fold. 

@jolevesq I'm not saying Option 1 is confusing, not at all. It's just - in my opinion - doesn't add enough value for the user. I believe it could be done better. 

Not sure what you mean by restricting the use to the same group / level. According [the new schema](https://github.com/alyec/fgpv-vpgf/blob/5e9a591c0361f67ba1b405b43cb96896ad37c41e/src/schema.json#L248), the visibility set cannot span several groups. Was that a requirement to allow that? Did we miss something?

I agree with you on the colours; I misunderstood your initial point.

**Comment by alyec** [comment]
Well option 1 works very well with distinct visibility sets, but if you get around to nesting them it gets harder to read than option 3.
