### ISSUE TITLE
Create Mockups for Enhanced Datagrid Functionality

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1240]
Create mockups for the implementation of functionality specified under #884 and as implemented currently by GcCanViz.

**Comment by AleksueiR** [comment]
Started working on this. Got sidetracked by all the structured legend discussions during the last two days.

**Comment by AleksueiR** [comment]
Finished the first round of mockups. Please commend (reactions are welcome):

![a04 - datatable advanced settings and enhancements v0 1](https://cloud.githubusercontent.com/assets/2285779/19659011/38741f5a-99f8-11e6-91c1-4daffdfdd05d.png)

**Comment by AleksueiR** [comment]
- Good point. We would also need to use the backspace icon in geosearch field for consistency.
- Yes, this is intentional. Datatable plugin allows for multisort and they use the `Shift` key as a modifier for multisort.

**Comment by jolevesq** [comment]
- I like your filter window where you can set everything. My only concern is you need to click to see your filter. From your table you need to know if your column is filtered and whats the value. It is the same thing for ordering. The reorder, display and field type are a good fit for setting windows. Filters value and reordering, I think, should be on the main table.
- Just to say, we have the full search in GCViz but most user doesn't want it. They prefer filter by column. On the other it is out of the box with datatable plugin and easy to configure if we want it or not.

**Comment by AleksueiR** [comment]
- There are several considerations:
 - all filters/setting in one place - easy to access and configure everything
 - (assumption) not all users need to filter the table - adding filters and setting to the main table view will needlessly increase visual complexity for such users (this is just a viewer, not Excel after all)
  - users who need to _quickly_ find something, will use search at the top of the panel; (assumption) users who need to do more _in-depth_ filtering will probably be okay with performing an extra step of opening the filters panel
 - it's easier to use filters/settings on a separate panel on a mobile device - due to smaller screen sizes, extra controls will crowd out the table view even more (we can make separate interfaces for mobile and desktop modes, but that's extra work)
- If we implement complex queries allowing to filter columns from the main search, power users can use that since it will be faster than having to filter individual columns. I agree, having that option (as well as filtering panel) configurable is a good idea.

I agree that users might want to see filter values for the columns. We can show them only after the filters are applied for example, to not use up space up-front. I'll try to make some changes to the mockups before tomorrow's UI meeting.

**Comment by alyec** [comment]
> I agree that users might want to see filter values for the columns. We can show them only after the filters are applied for example, to not use up space up-front.

Do you mean something like adding read only headers per column if the filters are active?  :+1:

**Comment by AleksueiR** [comment]
Exactly something like that.

**Comment by jolevesq** [comment]
I agree, filter and setting on the main panel are too much. We need to be careful with extra step. If someone needs to use the table a lot, the extra step can be anoying.

**Comment by AleksueiR** [comment]
Notes from the ui meeting:

- [ ] add filters row to the datatable on large layouts (on smaller layouts, filters are only available in the filters panel)
- [ ] when the filter value is changed, show a "Apply to Map" button
- [ ] grey out the map once the data is stale (the dialog and sidemenu style)
- [ ] clear filters, update map, and filter panel buttons in a cluster

Will update mockups and post here.

**Comment by jolevesq** [comment]
@AleksueiR do you have updated mockups or I follow the one you provided and modify it with comments?
