### ISSUE TITLE
Filter by Extent (Mercator maps) - Number of entries on Datagrid not updating when zooming the map

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1264]
Tested build URL: http://fgpv.cloudapp.net/demo/v1.4.0-rc1/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley
- Load Visualiser and switch to any of Mercator maps
- Open Datagrid for Airports layer
- Enable Filter by Extent feature (No. of entries will be displayed at the bottom of datagrid - this is correct)
- Zoom in or zoom out the map

Number of entries was not updated, see below screenshot
![image](https://cloud.githubusercontent.com/assets/18723160/19200978/bf7776c6-8c99-11e6-915c-ca286007fe10.png)

**Comment by james-rae** [comment]
Solution creates a circular reference with the current architecture.  After the suggestion in [this PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1283#issuecomment-256432833) is implemented, I can use the event to avoid the circular reference issue.

**Comment by jolevesq** [comment]
I have the same problemwith Geosearch. It is why I want the event to be there only when I need it. instead of linking the extent-change event at init, I would like to create it when I open geosearch or datagrid and delete when I close it. It will solve the switch to mercator problem and circular reference.

https://github.com/jolevesq/fgpv-vpgf/blob/1175-geosearch/src/app/geo/map.service.js#L744
https://github.com/jolevesq/fgpv-vpgf/blob/1175-geosearch/src/app/ui/geosearch/geosearch.service.js#L249

Technically I will not check for the event existence because I will remove it on close.

**Comment by alyec** [comment]
From the discussion on the PR this is the way to re-broadcast the event through angular.  This also avoids the circular dependency and it is possible to unsubscribe from the $rootScope event, and it has the benefit of avoiding the `$watch` code.  I think Alex and I are still unclear on what changes when the listener is added directly to geoApi instead of routed through map.service.

```diff
--- a/src/app/geo/map.service.js
+++ b/src/app/geo/map.service.js
@@ -672,6 +672,7 @@

                                 setMapLoadingFlag(true, 300);
                             },
+                            'extent-change': data => $rootScope.$broadcast('extentChange', data),
                             'update-end': () => {
                                 console.log('   Map update END!');

--- a/src/app/ui/filters/filters.service.js
+++ b/src/app/ui/filters/filters.service.js
@@ -68,15 +68,7 @@
             // add a DataTable filter which only accepts rows with oidField values in the validOIDs list
             $.fn.dataTable.ext.search.push((settings, data) => validOIDs.indexOf(parseInt(data[oidColNum])) !== -1);

-            // call onExtentChange function when the extent has changed
-            const stopGeoServiceWatcher = $rootScope.$watch(() => geoService.isMapReady, isReady => {
-                if (isReady) {
-                    gapiService.gapi.events.wrapEvents(geoService.mapObject, {
-                        'extent-change': debounceService.registerDebounce(onExtentChange, 300, false)
-                    });
-                    stopGeoServiceWatcher();
-                }
-            });
+            $rootScope.$on('extentChange', debounceService.registerDebounce(onExtentChange, 300, false));

             // DataTable is either being created or destroyed
             $rootScope.$watch(() => stateManager.display.filters.data, (val, prevVal) => {
```

**Comment by jolevesq** [comment]
I will have to test but your code but I see it will unsubscribe from rootScope but it will not remove the event from esri api. You need to remove the event.

https://developers.arcgis.com/javascript/3/jshelp/inside_events.html

**Comment by alyec** [comment]
In this case we don't want to remove the ESRI event.  Basically mapService always listens for ESRI events and re-broadcasts them through angular events.  Anything else that wants to listen for extent change can subscribe and unsubscribe from the event as appropriate.

**Comment by jolevesq** [comment]
Ok, understand now. I will implement it like this for geosearch

**Comment by alyec** [comment]
I just opened a PR for the filter https://github.com/fgpv-vpgf/fgpv-vpgf/pull/1311, so you should only need to update the geoSearch code.

**Comment by james-rae** [comment]
Issue solved by above PR.  Done thanks
