### ISSUE TITLE
Allow Viewer to have Map Extent Restricted

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1320]
The viewer should allow for the viewable area (extent) of the map set via configuration.  The user would then be unable to pan to areas of the map outside of this extent.  i.e. Joint Oil Sands Monitoring Portal should not allow users to pan outside of the relevant area.

Investigate porting code from RAMP1.

**Comment by AleksueiR** [comment]
What is the use case for this? 

I can sort of understand restricting the viewable area to the extent of the useful basemap (our Lambert basemaps only show North America, so restricting to that can be justified). I don't see any benefits of imposing such a restriction on a user with a full basemap.

If the user pans the map beyond an arbitrary-set boundary and the map bounces back, it will likely frustrate the user. By cancelling user's actions in this way we are telling the user that he is wrong, that he used the app incorrectly. This is not the case however. The user didn't make a mistake, he panned the map with some goal in mind and will return to the featured area if he needs or wants to (there is always a "Home" button to go back in case he's lost). If the user just pans the map mindlessly or for fun, that's still not our business to interfere. Let the user pan to his heart’s content.

If restricting the extent solves our technical problem (like turning of extent filtering in geosearch when zooming out too far), it still does not justify the restriction. This is our problem and we shouldn't offload it to the end user.

Introducing this option allows for map authors to screw user experience and these "bugs" will be charged back to us. Imagine, for example, a narrow and relatively long (Canada-US border from the west coast to the Great Lakes) extent the map is restricted to. When the user zooms out far enough, the centerpoint can get outside of the restricted area; the map bounces; the user tries to pan up or down and because the zoom level is low, the centerpoint gets outside and the map bounces back. I think it is frustrating.

I do not see any reason to allow for such a restriction.

**Comment by mweech** [comment]
This is a requirement that is requested frequently by previous and existing clients who would use the viewer.  IE JOSM, NACEI, etc... 

In each case these are portals with a regional concern.  There is no interest on their parts in having their web mapping sites used to view areas of the globe outside of the Oil Sands region or the North American continental area.  In particular for a map like NACEI, it possess global datasets (METARs) however there is no reason for their user base to use that viewer for non-NA viewing.

**Comment by AleksueiR** [comment]
Would anyone agree with me that there is no real reason to restrict the map extent for the user?

Requirements can sometimes be wrong. If the the map author thinks there is no reason for the user base to use the viewer outside some specific area, that's okay, and the users probably won't do that, but why impose a restriction if some users will want to use it this way? This is just more work with no real benefits.

**Comment by jolevesq** [comment]
If we remove some lod from config file we can restrict the zoom out (not the pan). Just this can be enough for most users. It is easy to zoom too far out when you use scroll zoom and I don't think it is useful in most cases for users to end up with something like these

<img width="2506" alt="screen shot 2016-11-02 at 9 15 35 am" src="https://cloud.githubusercontent.com/assets/3472990/19930061/fa0e2c92-a0dc-11e6-9bbc-c264eb8b8bc2.png">

<img width="2216" alt="screen shot 2016-11-02 at 9 18 24 am" src="https://cloud.githubusercontent.com/assets/3472990/19930125/5bc0b7a2-a0dd-11e6-914d-2bdb0b58c27d.png">

**Comment by AleksueiR** [comment]
I think restricting zoom levels is acceptable and I agree that zooming out that far provides nothing useful.
Restricting Lamber to level 2 and Mercator to level 3 should be enough.

**Comment by mweech** [comment]
This was lost in a refactor, please add to 2.2.1 patch line.

**Comment by dan-bowerman** [comment]
Use case: CESI has a number of sensitive or otherwise unmappable data points that they currently just set to 0,0. Like pipelines. They need to report on these stations without plotting their location directly. In the current version of RAMP2, they appears as stacked in the Atlantic ocean. The clients would like to keep this information available in the data grid while not being visible on the map itself -- having this restricted boundary would solve this problem perfectly.

**Comment by YaroRoodzit** [comment]
Tested with build v.2.4.0-b2. Sample #66. Viewer extent restricted to a viewable area of the base map.

**Comment by bkutty** [comment]
Sample#66 does not have option to choose a Mercator basemap in the current build. We will retest this item in the upcoming build.

**Comment by dane-thomas** [comment]
Mercator basemap option for` Sample #66` will be added in v2.5.0

**Comment by dane-thomas** [comment]
`Sample #66` has been updated with a Mercator basemap in #2781 so it should be included in the upcoming build
