### ISSUE TITLE
Determine which UI elements to capture for state preservation and how they should be restored

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1356]
Notes added from a pod meeting.

## UI Elements to be Tracked

- ToC
- legend tree (structured legend format: no settings)
- metadata and settings panels (store layerId for source layer)
- identify panel (store click point)
- datatable (need layerId)
  - split / maximized state
  - details panel (recordId / objectId)
- overview map
  - expanded / collapsed

Related:
- expand schema for structured legend to include expanded / collapsed state by group

**Comment by milesap** [comment]
### Initial Structure Proposal

```js
legendTree: [ // an ordered array
  {
    layerID: Number
    isExpanded: Boolean
  }
]
sidePanel: "metadata" | "settings" | {Point Information} | Number //recordId or objectId
filterPanel: "full" | "partial"
overviewMap: Boolean
selectedLayerId: Number
```

### Implementation Notes
Retrieve a `layer` object by calling `geoService.layers[selectedLayerId]`

If **sidePanel** is:
 - ***metadata***; pass `toggleMetadata` in `toc.service.js` a `layer` object
 - ***settings***; pass `toggleSettings` in `toc.service.js` a `layer` object
 - ***Point Information Object***; pass `clickHandlerBuilder` in `identify.service.js` a `clickEvent` object
 - ***Number***; see `onDetailsClick` in `filters-default.directive.js` for implementation idea

If **filterPanel** is defined pass `toggleLayerFiltersPanel` in `toc.service.js` a `layer` object

If **overviewMap** is true set `$rootScope.overviewActive` to true, false otherwise
