### ISSUE TITLE
Design UI state format and implement serialize and deserialize functions

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1357]
- [ ] document state format
- [ ] implement state capture and serialization
- [ ] implement deserialization and state restoration

**Comment by milesap** [comment]
### Initial Structure Proposal

```js
legendTree: [ // an ordered array
  {
    layerID: Number
    isExpanded: Boolean
  }
]
sidePanel: "metadata" | "settings" | {Point Information} | Number //recordId or objectId
filterPanel: "full" | "partial" // uses selectedLayerId for layer object, if undefined filter panel is not shown
overviewMapExpanded: Boolean // if false overview map is minimized
selectedLayerId: Number
```

### Implementation Notes
Retrieve a `layer` object by calling `geoService.layers[selectedLayerId]`

If **sidePanel** is:
 - ***metadata***; pass `toggleMetadata` in `toc.service.js` a `layer` object
 - ***settings***; pass `toggleSettings` in `toc.service.js` a `layer` object
 - ***Point Information Object***; pass `clickHandlerBuilder` in `identify.service.js` a `clickEvent` object
 - ***Number***; see `onDetailsClick` in `filters-default.directive.js` for implementation idea

If **filterPanel** is defined pass `toggleLayerFiltersPanel` in `toc.service.js` a `layer` object

If **overviewMap** is true set `$rootScope.overviewActive` to true, false otherwise

**Comment by AleksueiR** [comment]
Some notes:

- `isExpanded` only applies to the "group" layers; is it going to default to `false` to single item layers?
- we probably also want to store whether the main panel is opened or not
- opened/closed state of the overview map

**Comment by alyec** [comment]
In structured legend mode not all LegendEntries will be tied to layers.  I think `legendTree` should closes mimic the full structured legend spec (and since this is internal we can always mess around with it if the structured legend schema changes when we go to implement).  We also need to not only track the layer group expanded state but the symbology state as well.

I think expanding side panel to:
```js
{ type: 'metadata', layerId: 3 }
{ type: 'settings'; layerId: 3 }
{ type: 'clickEvent', event: {define me fully or link to docs} }
{ type: 'details', recordId: 33 }
```
will help avoid having to do JS variable type comparisons

**Comment by milesap** [comment]
### Proposed Final Structure

```js
legendTree: [ // an ordered array of "structuredNode"
  {
    name: String
    renderChildren: "tree" | "inline"
    expanded: Boolean // optional
    symbologyExpanded: Boolean // optional
    children: Array // optional
    layerId: String  // optional
    index: String  // optional
  }
]
sidePanel: {
  type: 'metadata' | 'settings' | 'clickEvent' | 'details'
  layerId: Number // optional when type is 'details'
  recordId: Number // optional when type is not 'details'
}
filterPanel: {
  type: 'full' | 'partial'
  layerId: Number
}
mainPanel: {
  expanded: Boolean
}
overviewMap: {
  expanded: Boolean
}

```

**Comment by milesap** [comment]
All serialize and most deserialize is complete, see branch [1357-ui-state](https://github.com/milesap/fgpv-vpgf/tree/1357-ui-state). I've asked @alyec for help with deserializing `details`, `identify`, and `legendTree`, as soon as some free time opens up this will be wrapped up
