### ISSUE TITLE
Clean up errors on load

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#1397]
This is showing up in the console:
> core.js:12798 TypeError: Cannot read property 'slice' of null

Tested on http://fgpv.cloudapp.net/demo/users/milesap/build-1.4.0-6/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale but seems to happen on several other builds as well.  This is not our code, but may be triggered by our code so we should try to find out the cause and clean it up.

**Comment by james-rae** [comment]
Culprit is RCS key `mb_colour`.  For reasons yet to be determined, the `entry-symbology.directive.js` scope value `self.entry.symbology` is missing.  This causes nothing to get passed into the `rvReverse` reverse filter that is used to arrange the icon stack in the legend.  The filter throws the error, but since there is no content anyways the app doesn't care and ends up showing the "letter" icon anyways.

**Lazy solution**: Enhance the reverse filter to not do array operations if the input is not an array

**More work solution**: keep mucking through directive code to discover where things are failing such that no symbology property is generated.

Note that [problem layer](http://www.agr.gc.ca/atlas/rest/services/imageservices/mb_colour_orthos_50cm/ImageServer) is an `ImageServer`, but have tried a [different one](http://section917.cloudapp.net/arcgis/rest/services/TestData/LCV_AAFC_CLASSIFIED_30M_1995/ImageServer) and didn't get the error.

Error occurs when loading from config and from wizard.

**Comment by james-rae** [comment]
Implemented lazy solution. Chasing details seems non-priority with massive legend refactor looming

**Comment by AleksueiR** [comment]
The symbology placeholder generator function is async. Looks like it's a race condition between generating a placeholder and adding it to the legend.
