### ISSUE TITLE
Make datagrids and filters use the informations provided by configuration file (thematic map)

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1414]
Once #1413 is done, modify the filters to use the configuration file information instead of the default information when those information are set. This will be mostly use for thematic map.

- [x] Set table open by default
- [x] Set table name
- [x] Hide/Display field
- [x] Set field not searchable
- [x] Set filter type
- [ ] Freeze filter type
- [x] Set sorting field by default
- [x] Set field name (title)
- [x] Set fields order
- [x] Enable/disable global search for a table
- [x] Set width for a column
- [x] Order Fields

This is out topic but can those informations be stored in RCS so some feature from FGP catalog can be configured?

**Comment by mweech** [comment]
Just saw your question re: RCS here... this would go against the model for Catalogue conversion/RCS registration we currently have.  The catalogue wants to minimize the amount of details set for a service and focus on people deciding after the fact how to make use of the data.  Rather the focus is on Web Service quality standards so that this kind of override functionality is needed less.

**Comment by jolevesq** [comment]
Good, so it will only be use for layer inside config file. Mostly for thematic map.

This issue is related with #1711
