### ISSUE TITLE
Exported map - Scale bar deviation

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1423]
Tested build: http://fgpv.cloudapp.net/demo/v1.4.0-7/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

The scale on the exported map is incorrect as comparing with the original map. Screenshot below.
![image](https://cloud.githubusercontent.com/assets/18723160/20671970/91c96842-b54d-11e6-91a3-2eb28882a099.png)

**Comment by milesap** [comment]
I'm going to suggest this be closed as a no fix. Seeing as the exported maps canvas size differs, the scalebar is adjusted accordingly. The [ArcGIS API](https://developers.arcgis.com/javascript/3/jsapi/scalebar-amd.html) is using the bottom border size as its reference since the scalebar node is after the map. There is also no support for this in the API (that I can see).

Thoughts?

**Comment by milesap** [comment]
The scalebar is correct, it's just not the same size/units as the interactive map

**Comment by alyec** [comment]
When you say "we must provide a correct scalebar", is there a correctness issue with the one we have right now?  My understanding is that since we generate one instead of copying from the map we end up with different sizing but still correct.

**Comment by AleksueiR** [comment]
I thought the scale bar itself was incorrect, not that it just looked differently. Sure, no need to fix this.

**Comment by bkutty** [comment]
Closing the issue.
