### ISSUE TITLE
Add Features to Left Sided Menu for Alternative Navigation Paths

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1424]
- [x] Add ability to open and close Legend from the sidemenu (use a checkmark)
- [x] Change fullscreen toggle to use a checkmark
- [x] Add basemap toggle to the sidemenu
  - [x] Remove basemap toggle from the mapnav cluster

**Usability Issues:**
### V2. Confusion caused by the menuicon placement (Type: Design)

Testers repeatedly clicked on the menu iconwhen they wanted to open the legend and were frustrated to continually make thesame mistake.  Testers commented that thelegend icon should be moved to the left hand side.

### V10.  Unable to find basemap switcher (Type: Labelling)

Testers were unable to find the basemapswitching function and commented that the icon didn’t mean anything to them.  Testers also asked that the tooltip be clearer such as “Basemap options” or “Change the basemap” or “Switch the basemap”.

### V20.  Full screen state change (Type:  Labelling)

After pressing the full screen button, when a tester wanted to return to the regular page “non-full screen” state the button is still labelled full screen.

**Comment by AleksueiR** [comment]
#### V10
If we are adding the basemap toggle to the left side menu, we need to move the basemap selector to the left side of the viewer as well; otherwise it is going to open to far from the actual click and the distance needs to be minimized. It would probably be okay for now to just open the basemap selector on the left for a quick fix, but in the future, the basemap selector content should be integrated into the side menu, so we don't have two different menu panels on one side.
