### ISSUE TITLE
Location not working

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1458]
Tested build :http://fgpv.cloudapp.net/demo/v1.4.0-8/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley,ZoomScale

When tested for Location, Viewer gives the message "Your Location could not be found". It works in Firefox though. Please investigate. 

![screenhunter_2655 dec 01 11 05](https://cloud.githubusercontent.com/assets/18539315/20801279/560b75be-b7b6-11e6-8158-1ac253b71868.jpg)

**Comment by AleksueiR** [comment]
By design:
Geolocations is using Google services to detect the locations (with fallback on browser location). We remove our own googleAPIkey from the public builds, so it won't be accidentally deployed in a production setting. The map author should include their own googleAPIkey to use advanced geolocation.

Suggestion:
Leave the key in QA builds for testing purposes.
