### ISSUE TITLE
Map Export returns blank map on high zoom levels

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1461]
- zoom to lowest possible level (it helps to get some svg-features in the extent, so you know export is working for Feature layers)
- open export dialog
- wait for the image to render (observer the image rendered correctly)
- select map size larger than the default
- wait for the image to render
- observe the blank basemap and non-Feature layers (Feature layers should be visible)

**Comment by JahidAhmed** [comment]
The issue seems to be occurring when making the call to the esri PrintTask [here](https://github.com/fgpv-vpgf/geoApi/blob/develop/src/map/print.js#L82). 
Note: the call suceeds, it doesn't error out.

The basemap appears as expected for the default size (and any size smaller), but doesn't work when you change it to a larger size because it seems to be recalculating the view by trying to grab the next level, which in this case does not exist since we are at the highest zoom possible.

The same issue (but in reverse) can be seen by zooming all the way out and selecting a map size smaller than the default.
