### ISSUE TITLE
feat(ui): point information panel - open layer list on hover intent or after a slight delay

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#147]
Right now it's just opening on hover which might be annoying.

Also, open the list on focus for keyboard support. When triggered from the keyboard, set focus to the pane's close button.

**Comment by milesap** [comment]
The hoverIntent jQuery Plugin ([demo here](https://briancherne.github.io/jquery-hoverIntent/)) fires an event when it detects the mouse movement slowing. A timeout also works in this case since the layer list item element is small so users are unlikely to remain focused on the element if they don't intend to expand it. 

I think the hoverIntent jQuery Plugin is good, but is most likely overkill for this issue.
