### ISSUE TITLE
Implement OnHover ToolTips for Feature Layers

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#1491]
- [ ] A feature layer may optionally support the display of tooltips for its features. 
- [ ] Tooltip will display the default field for the feature and if clicked, open the feature details panel (as per datagrid)

Refer to #1337 for design considerations.

**Comment by james-rae** [comment]
ASSUMPTION: we are using our own SVG tooltip for accessibility (?)

Detail list

- Config schema setting to turn on/off hover tips
- Wire up esri mouse events on feature layer if setting is present
- Function to create SVG element for tip
  - Input: feature + layer record for the host layer
  - Insert icon
  - Insert name using `<text>` to make it accessible
  - Details button.  Is SVG appropriate for buttons? Do we need something else?
  - Box border / sizing
  - One of those little pointy nubs that singles out the feature?
- Positioning of SVG tip above feature
- Removal of tip on mouse-out
- Test what happens if we zoom in and mouse stays inside feature. Will a mouse-out / mouse-in event chain happen?  If not, do we need to force it to avoid badly-scaled tip?

**Comment by james-rae** [comment]
After discussion, have decided to persue an angular tip solution rather than using SVG in an ESRI Graphic Layer.

* While SVG can handle hover, it becomes problematic when implemnting an anchor tip
  * Anchor needs a close button, which adds accessibility issues
  * Doesn't make sense to have an SVG framework for hover tips and a different framework for anchor tips
* In-layer SVG is harder to style
* Zooming issue -- in layer SVG will scale up or down when when zoom
* Can't position the tip outside of map.  It always has to be contained in the map (in all three dimensions)

**Revised detail list**

- Config schema setting to turn on/off hover tips
- Disable regular identify function if config setting is present
- Wire up esri mouse over / out / click events on feature layer if setting is present
- Removal of tip on mouse-out
- Single identify on feature click. Target is top-most feature (i.e. the feature that triggered the click event).  Code will be more similar to the datagrid detail button event than an identify.
- Show hover tip on feature mouse over (remove any other existing one? )
  - Inputs
    - feature; gives us object id of target
	- need to derive the layer record from the feature
	- feature + layer record gives us enough info to derive display name and icon
  - Insert icon
  - Insert name text
  - Box border / sizing
  - One of those little pointy nubs that singles out the feature?
- Positioning of angular tip above feature
  - If near top or side of map, do we let tip go out of the map, potentially covering non-map content?  Or do we re-position so tip is always in the map (bottom or to the side)
  - Utilize map point to screen point functions in esri api for position origin
    - Screen point will be relative to the DIV the map is in. Angular tip inside this div?

**Comment by AleksueiR** [comment]
The user needs to be informed that regular identify click is disabled and it's not possible to get details from non-Feature layers by clicking on the map (only through datagrid).

**Comment by AleksueiR** [comment]
Some poc; big white box represents a feature on the map.

![tooltips_take_one_2](https://cloud.githubusercontent.com/assets/2285779/21721233/7018972e-d3f5-11e6-9469-8dc232ff1407.gif)

**Comment by james-rae** [comment]
Nice work.  Earphone icon for bonus points

**Comment by AleksueiR** [comment]
Started working on hover tooltip collision detection:
![tooltips_take_three](https://cloud.githubusercontent.com/assets/2285779/21782922/27a3c2f8-d683-11e6-83e2-0b23ea80dea5.gif)

**Comment by mweech** [comment]
"GET BACK IN YOUR BOX TOOLTIP"

**Comment by AleksueiR** [comment]
more:
![](https://fgpdoc.zz9.ca/index.php/s/f5t3uUlOdXkhG9x/download)
