### ISSUE TITLE
"Help" non responsive in Firefox

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#1508]
Tested URL :http://fgpv.cloudapp.net/demo/v1.5.0-1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,mb_colour,Airports,Barley

"Help" option from the left hand side panel or from the right side panel do not work. Help window does not load in both cases. Below is the error I see in the console. Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/21155923/fefed73a-c141-11e6-891f-1bcc6a59dae5.png)

**Comment by AleksueiR** [comment]
`event` object is not defined when opening the help panel in this function: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/help/help.service.js#L63

The event is actually passed to the function. Chrome somehow picks it up and `event` is available in the function's scope. Not so in Firefox. I think that's why it's failing.

**Comment by bkutty** [comment]
no longer an issue. Accepted. per tests on v1.5.0-9
