### ISSUE TITLE
Datagrid not populating if field names have "." characters in them

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#1530]
![blob](https://cloud.githubusercontent.com/assets/5294596/21325475/93ee55bc-c5f4-11e6-8865-30c2dca05d2b.png)

This is seemingly caused when a service has field names with "."s in them, denoting a relationship between two tables, e.g. 
![capture](https://cloud.githubusercontent.com/assets/5294596/21325525/c7f9c878-c5f4-11e6-9740-50b7d9767e7a.PNG)

**Comment by ChrisLatRNCan** [comment]
Can happen also with added file containing an attribute with a dot.
![image](https://cloud.githubusercontent.com/assets/16193004/21325633/46accddc-c5f5-11e6-825e-6426721ea17a.png)

**Comment by james-rae** [comment]
I think [this article](https://datatables.net/reference/option/columns.data) under the Types --> String section is the cause. Datatables is treating this as object property notation (e.g. looking for property `uuid` on object `JOSM2` instead of root property `JOSM2.uuid`). 

If this is the case we will need to add some code to escape any periods in field names when dealing with the grid, as described in the article, or think of another solution

**Comment by bkutty** [comment]
Confirmed the issue with  layer http://section917.cloudapp.net/arcgis/rest/services/JOSM/JOSM2_en/MapServer/0

tested build : http://fgpv.cloudapp.net/demo/v1.5.0-13/prod/samples/
