### ISSUE TITLE
fix(export): Not able to tab between width and height fields for custom export size

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#1536]
In Firefox and Safari (on Mac, may apply on PC as well), for custom size export, we are not able to tab between width and height fields for keyboard user.

**Comment by milesap** [comment]
@jolevesq this may have been resolved with PR #1741, when you have a minute try to replicate using this link: http://fgpv.cloudapp.net/demo/users/milesap/1373-arrow-support/prod/samples/index-one.html

Testing with FF on PC I am able to tab between the two. Focus is lost when custom size is selected from dropdown so it takes a while to get back to the width/height by tabbing (alt-tab instead).

Note that focus manager is only tested and supported on chrome since each browser implements focus movement and related events differently. If support is needed for IE and firefox to match chrome, an epic issue should be opened instead.

**Comment by milesap** [comment]
Although this is a no fix, FM improvements in latest update have fixed this :+1: closing
