### ISSUE TITLE
Datagrid columns stacking on top of each other

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1597]
When looking at the datagrid for layer `http://services.aadnc-aandc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Bail_minier_NU_Mining_Lease/MapServer/0`, some of the columns sit on top of each other.

![badgrid](https://cloud.githubusercontent.com/assets/7585245/22028008/b7d8c762-dca3-11e6-8181-7b6e804ca379.jpg)

From Alex: 

> is inconsistent: loads fine locally, fails on cloud

**Comment by jolevesq** [comment]
The error happen because there is an error when date is set. This happen because there is null date inside the dataset

ISSUE_DT: 784382400000
RENT_DUE_DATE: null
TERM_EXPIRY_DATE: 1446984000000

ISSUE_DT: 848318400000
RENT_DUE_DATE: null
TERM_EXPIRY_DATE: 1510920000000

ISSUE_DT: 820152000000
RENT_DUE_DATE: null
TERM_EXPIRY_DATE: 1482840000000

ISSUE_DT: 820152000000
RENT_DUE_DATE: null
TERM_EXPIRY_DATE: 1482840000000

ISSUE_DT: 820152000000
RENT_DUE_DATE: null
TERM_EXPIRY_DATE: 1482840000000

```
} else if (field.type === 'esriFieldTypeDate') {
                            // convert each date cell to a better format
                            displayData.rows.forEach(function (r) {
                                return r[field.name] = $filter('dateTimeZone')(r[field.name]);
                            });
                        } 
```
core.js:12798 ReferenceError: moment is not defined
    at Object.dateTimeZone (http://localhost:6001/build/lib/core.js:147025:28)
    at Object.invoke (http://localhost:6001/build/lib/core.js:4570:17)
    at Object.enforcedReturnValue [as $get] (http://localhost:6001/build/lib/core.js:4422:37)
    at Object.invoke (http://localhost:6001/build/lib/core.js:4570:17)
    at http://localhost:6001/build/lib/core.js:4387:37
    at Object.getService [as get] (http://localhost:6001/build/lib/core.js:4529:39)
    at http://localhost:6001/build/lib/core.js:18632:24
    at http://localhost:6001/build/lib/core.js:132181:56
    at Array.forEach (native)
    at http://localhost:6001/build/lib/core.js:132180:46

**Comment by james-rae** [comment]
@milesap Can you take a look? Your code might need some extra checks for null dates

**Comment by james-rae** [comment]
Newly added date formatting was not assigning a column width.  Column was collapsed and contents bleeding into next cell

**Comment by IsabellaPan** [comment]
Feb 8 2017
No longer an issue in build v1.5.0-rc3
