### ISSUE TITLE
Identify tool on OGC/WMS added service with some unqueryable layers won't work

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpv-vpgf#1613]
1. Add OGC/WMS service http://maps.geogratis.gc.ca/wms/railway_en
2. Select all available layers
3. Use the identify tool on the map
Selecting a subset of queryable layers won't give that error

![image](https://cloud.githubusercontent.com/assets/16193004/22159062/4a490af6-df0d-11e6-8ade-ab513e45b578.png)

**Comment by ChrisLatRNCan** [comment]
Finally #1228 might take a different path. Here I'm removing the layer or the layers group and showing a toast. However, for the  resolution problem (#1228) I'm still not sure if I need to apply the same solution. In both case I'm retrieving the service error. The push will still need to wait a bit.

**Comment by ChrisLatRNCan** [comment]
The error is triggered only at GetFeatureInfo and not at GetMap. As it is right now, we can't stop layer from loading even though it will generate an error at query time (when using identify tool)

**Comment by milesap** [comment]
There is one sub-layer named `railway.subdivision` which seems to be misconfigured on the WMS server. The main layer and all other sub-layers are working fine. There is nothing to be done on our end, I more thorough debugging should take place on the WMS server. 

Confirmed that the layer exists and is queryable in http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetCapabilities. 

Confirmed GetMap recognizes this layer is defined since it returns a transparent image. Changing the layer name to a random one returns an error, so it doesn't return a transparent image when a layer can't be found. Link tested http://maps.geogratis.gc.ca/wms/railway_en?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=TRUE&STYLES=&VERSION=1.3.0&LAYERS=railway.subdivision&WIDTH=1138&HEIGHT=700&CRS=EPSG:3978&BBOX=801656.7769452205,81050.49563965743,1855494.301286936,729280.9587672504

Maybe @alyec can look into the service further, but no further action is needed here.

**Comment by alyec** [comment]
I looked at the service and I don't see anything that looks like it could be an issue on our end.  What you saw in the GetCapabilities for `queryable="1"` means that the error message doesn't make sense to me.

**Comment by mweech** [comment]
Issue will be raised with Service providers.  This issue keeps reappearing.
