### ISSUE TITLE
Missing symbology for some user added CESI layer map points

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#1637]
http://fgpv.cloudapp.net/demo/v1.5.0-rc1/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,Airports,Barley
Test Data: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer

Added Air Emissions sub-layer for CESI from above test data, clicking map points will open Feature Details panel as below screenshot, but the symbology is missing, and the magnifying glass button is not responding.
![image](https://cloud.githubusercontent.com/assets/18723160/22348642/884d293c-e3da-11e6-8296-37da4d8b094c.png)

**Comment by milesap** [comment]
This doesn't appear to be an issue with the view as the test data provided has incomplete symbology for some layers. I verified `svg.directive.js` and the `ui.details` module are working as intended.

For example, some features have symbology:

```
<svg id="SvgjsSvg2198" width="32" height="32" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" viewBox="0 0 32 32"><defs id="SvgjsDefs2199"></defs><image id="SvgjsImage2206" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABcAAAAXCAYAAADgKtSgAAAAAXNSR…PQMiRSAKJsMjnui0Re7NVVyTU3Nj39GcBwqZpSqWhBV5o/uNPt4QWdV6wAAAAASUVORK5CYII=" width="23" height="23" x="4.5" y="4.5" transform="matrix(1,0,0,1,0,0)"></image></svg>
```

While another has 
```
<svg id="SvgjsSvg2868" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs"><defs id="SvgjsDefs2869"></defs></svg>
```

Could not replicate the issue with zoom to feature with provided Air Emissions sub-layer. 

Moving issue back into QA, if testing can demonstrate feature has a valid symbol but is not displaying then I can take another look.

**Comment by james-rae** [comment]
This is a funny situation caused by how the CESI services are defined.  These services act as a source to the CESI Webmap Site, not as a "Catalogue of CESI Data".  We have layers for many different pollutants. Usually, due to how the data is generated, we will have a Point per Location per Pollutant.   So if a McDonalds is only polluting CO2, it will also have points for NOX, NO, etc.  

One of the user requirements is that if a point exists with no pollutants, it should not show on the map.  This prevents massive amounts of "0 measurement" points polluting the map....users only care about points with emission values.

How CESI handles this is it gives a value of `-1` in the symbol column for a no-emission point. There is no symbol defined for `-1`, so it doesn't show on the map.

What is confusing having these layers in a Catalog Viewer is:

* We see the symbol stack on the left side of the identify results, which makes us feel we should see a Grey Dot.
* The identify function is server based and works off of geometry, not symbology. It has no problem returning invisible things (they are invisible because they have no symbol -- their visiblity is still true).

So the blank symbol is actually correct.
Here is the underlying data for the point in the screenshot:
http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer/17/314

However, the zoom button is a bug.  It is failing on `self.triggerZoom` in directive function `rvDetailsRecordEsrifeature`, it is not finding an `entry`, which is meant to be a `zoomLayer` input in function `zoomToGraphic`. This causes a crash and the zoom does not complete.

**Comment by james-rae** [comment]
Miles, I'll show you how to replicate this.

**Comment by james-rae** [comment]
Further investigation shows:

Zoom issue is caused by the leaf layer existing in a sub-group instead of at the root of the dynamic layer.

In function `self.triggerZoom` in `rvDetailsRecordEsrifeature`, it has the correct leaf index (`featureIdx`) but uses the line `let entry = self.requester.layerRec.legendEntry` to grab the legend entry -- in this case, the legend entry is the Group entry, not the leaf.  This causes a grand mismatch.

Potential routes forward.

1. Lazy -- ignore until refactor, hope it is fixed in refactor.
2. Cleaner Lazy -- identify when bad situation happens and abort zoom, avoiding the error on console.
3. Working Lazy -- identify when bad situation happens. Change parameters so we zoom but don't worry about scale (i.e. make a dummy object that plays nice, or adjust zooming code to have default behavior when missing data)
4. Attempt fix -- original attempts were nasty, as sub child legend entries were missing key data. Would need to keep backfilling missing properties until things worked.

**Comment by AleksueiR** [comment]
:point_right: :one:
