### ISSUE TITLE
Prevent non-tested dependency version console warnings from being stripped

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1702]
A recent PR strips all console warnings. Need to add `/*RemoveLogging:skip*/` to preserve once about potential problems with untested dependency versions.

**Comment by AleksueiR** [comment]
The warning statement is still being stripped in prod:
![](https://i.imgur.com/nCOwOlf.png)

**Comment by milesap** [comment]
#### Solution 1:
- I have a working solution using the existing `uglify` library which drops all console outputs. To write to the console in prod mode we would need to change our syntax to something like `RV.console.warn()` instead of `console.warn`.

#### Solution 2 (enthusiastically recommended by @alyec):
- Research and implement a custom logger, part of issue #981. I would put it at an estimate of 5. Would offer more debugging flexibility and would make @AleksueiR and @alyec very happy (James not so much).

#### Solution 3 (James):
- Press F12 to close debugging. Problem solved :+1:

**Comment by AleksueiR** [comment]
Solution 4:
- disable console log suppression for 1.5.3 release
- implement Solution 2 for 1.6+
