### ISSUE TITLE
Layer ID != Layer Array Position in Esri Dynamic MapService Layers

### ISSUE THREAD

**Issue by cmndrbensisko** [fgpv-vpgf/fgpv-vpgf#1736]
Hello from the City of Ottawa!  We've been experimenting with using your fgpv viewer application, and we may have stumbled on a bug that we'd like to have confirmed if possible.

The issue which we may be seeing in the 1.5 version is related to layer visualization.  When MapServices are published, it's possible to set them to preserve their sublayer IDs when new layers are added to the service in the future (http://server.arcgis.com/en/server/latest/publish-services/windows/map-authoring-considerations.htm#ESRI_SECTION1_4C54586DEB0445B4B97AF15856E546AB).  This means that it's possible to have MapServices where the Layer IDs are not strictly sequential, and do not correspond to the position of the sublayer within the MapService.  The City of Ottawa Cycling Map below is an example:

`http://maps.ottawa.ca/arcgis/rest/services/CyclingMap/MapServer`

Because a sublayer's position within a MapService cannot be taken to be the same as its ID in this case, we're finding that the layer fails to load.  Please test using the attached "layers" configuration, and hopefully you can see this in action,

```
"layers": [
	{
		"id":"dynamicCycling",
		"name": "Cycling",
		"layerType":"esriDynamic",
		"url":"http://maps.ottawa.ca/ArcGIS/rest/services/CyclingMap/MapServer",
		"layerEntries": [
			{"index": 0},
			{"index": 5},
			{"index": 15}
		],
		"options": {
			"visibility": { "value": null }
		}
	}
],
```

Within the compiled core.js code, there are a few occurrences where the layer position is used in place of it's ID.  Please see the DYNAMIC_ENTRY_MASTER_GROUP.init function on line 116849 (compiled).  On line 116888, the following loop is used to set the initial sublayer visibility of the layer;

```
this._layerRecord.layerInfos.forEach(function (layerInfo, index) {
	var sublayerEntry = void 0;
	var sublayerEntryInitialState = {
		name: layerInfo.name,
		layerType: layerEntryType,
		options: layerEntriesOptions[index] || {},
		featureIdx: index
	};
	...
});
```

In this function, index will have a sequential index value from the loop, but it will attempt to use this as an indicator to retrieve a value from "layerEntriesOptions", which contains Layer Ids.  I haven't gone too far in testing to see if this is the ultimate source of the layer's failure to load or not, but it is an example of the kind of mismatch which may be causing the problem.

Hope this helps, I'd be happy to provide additional information or configuration files if necessary.

**Comment by james-rae** [comment]
Thank you!

Quite possibly this is also the root cause of the zooming issue in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/1637

**Comment by james-rae** [comment]
We certainly have some code that is cheating and will need a fix.

[Dynamic Master init](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v1.5.2/src/app/geo/legend-entry.service.js#L549), as noted above, suggest using `layerInfo.id` in place of `index` and test it with the [sample service](http://maps.ottawa.ca/arcgis/rest/services/CyclingMap/MapServer).

[Process Dynamic Layer](https://github.com/fgpv-vpgf/geoApi/blob/v1.1.2/src/attribute.js#L470), this is using array index to determine how to skip groups of sub-layers. This was some of the earliest code in the project; we have yet to actually use the `.skip` option. and to be honest current requirements indicate an inclusive filter will be more useful than an exclusive (e.g. only load index `4` and `6`, rather than skip index `1,2,3,5,7,8`).  Seriously consider refactoring this.

There may be other bits of affected code lurking.

Was wrong about issue #1637

**Comment by milesap** [comment]
@AleksueiR @james-rae I think this should be corrected on the refactor. If this is urgent it could be patched with v1.6.1. Let me know if this is urgently needed and how it is impacting your use of the viewer.

**Comment by james-rae** [comment]
Believe all instances of this are squished when `v2.0` is released.
The legend has been rebuilt and no longer crawls/parses the dynamic layer structure directly. 
The attribute loader in geoApi also no longer crawling dynamic child structures (or doing any type of skipping). It now only entertains requests for a single endpoint.

**Comment by james-rae** [comment]
Missed one spot. 
`layerInfos` array is not indexed by sublayer id.  Need to do array search instead

**Comment by james-rae** [comment]
Layer behaves with geoApi `v0.0.0-protoLR-80` and up.

Did notice one problem with the `Existing Cycling Network / Réseau cyclable (actuel)` layer (index 3). Zooming to the feature fails.  This is because the server will not return a proper result when querying the feature.
[example](http://maps.ottawa.ca/arcgis/rest/services/CyclingMap/MapServer/3/3?f=pjson)
