### ISSUE TITLE
Provide Subresource Integrity (SRI) values for library file in samples and release notes

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1796]
Subresource Integrity (SRI) is a mechanism for the browser to prevent execution of a compromised script file. Read more here: https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

**Comment by milesap** [comment]
This would imply we need to enable this in `bootstrap.js` as the following loads core from potentially the same "compromised" CDN:

```js
loadScript(`${repo}/core.js`, () => {
        RV._deferredPolyfills.forEach(dp => dp());
        RV.allScriptsLoaded = true;
        fireRvReady();
    });
```

Unless we assume that it is highly unlikely `bootstrap.js` remains untouched but `core.js` is infected. This would be a targeted attack that would likely be out of our control. I would imagine a rogue CDN would serve all files with a malicious payload rather than selectively choosing (unless targeted).

**Comment by milesap** [comment]
Autoloading scripts inside `bootstrap.js` would require a similar check, it wouldn't be enough to provide an SRI for just bootstrap. This needs a more detailed analysis if it were to move forward.
