### ISSUE TITLE
Plugin / API Discussion

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#1935]
Our old bootstrap process is largely obsolete now that everything is bundled. With a major release looming we should finalize the general direction our API / plugin architecture will follow. 

### Should plugins / API loading be bundled separately?

This would require a small file be loaded in the header section of a page, with the library remaining at the end of the body. Plugin / API requests would be available before the viewer loads. If plugins or external API is not needed it can be omitted.

### Should the API handle map state internally?

API calls that change the map like change projection would no longer return a promise to the user. Instead, subsequent API calls that would normally need to be called inside a returned promise can be invoked immediately where the API internally waits for the map state to be ready before passing on the request to the viewer.

Reasoning: API calls should not change depending on map state. Avoid enabling/disabling API methods which can be confusing to users. 

#### Alternative

Layer the API such that not all API methods are directly available. For example, `api.change_projection(mapApi => { do stuff with mapApi here... });` where the callback is provided a subset of the api containing map related api functions not available on the top level api.

### Promises or callbacks?

Some API methods, particularly get methods can't return values immediately. In these cases should the API return promises or accept a callback function?

## When should it be released?

- No plugin / API support on v2.0, add on v2.1 to prevent further delays.
- Release bare bones API with minimal support for 1 or 2 critical methods. This should not delay v2.0 but it is a possibility.
- Release API and plugin support which matches current v1.x support (back to cart, bookmarking etc...).  This should not delay v2.0 but its a 50/50 chance we hit a roadblock that slows us down.
- Release full API and plugin support. This will delay the v2.0 release by 2 weeks in perpetuity.

**Comment by milesap** [comment]
@mweech advised that this should released under the option:
> Release API and plugin support which matches current v1.x support (back to cart, bookmarking etc...). This should not delay v2.0 but its a 50/50 chance we hit a roadblock that slows us down.

I personally like the idea of bundling the API / plugins separately, and using callbacks instead of promises as I would imagine more users would prefer this.

As for the API handling map state I'm on the fence over the two proposed ideas. I'm leaning towards the 
> Layer the API such that not all API methods are directly available.

This direction would not be as complex as the "handle internally" idea while remaining transparent and easy to understand for a user (and to document).

**Comment by AleksueiR** [comment]
### > Should plugins / API loading be bundled separately?

Either the bundled or bootstrap/api file needs to be loaded after the markup for the viewer, so initialization code can actually find the nodes to instantiate. This suggests placing it at the bottom of the page; however, this approach requires any host page scripts that interact with the app to be placed below our main file (assuming blocking, sync execution order). 

```html
...
<div class="myMap" id="mobile-map" is="rv-map" .... ></div>
<script src="../rv-main.js"></script>
<scrip>
   host page scripts interacting with API
</script>
...
```

Splitting the main file into two does not seem to add any benefits - the script with the body of the app can to be placed either immediately after the bootstrap/api file, or after the host page scripts (placing it in the header will block page rendering). In both cases, the API will wait for the body and geoApi to fully load.

I can see benefit in splitting the API from the main body if we implement dynamic viewer generation during runtime:
```html
<script src="../rv-api.js"></script>

<div id="empty_div"></div>

<scrip>
   RV.newMap($('#empty_div'), configObject);
</script>

<script src="../rv-body.js"></script>
```

In this case, the body can be placed at the very bottom of the page, so not to block anything before it.

###  > Should the API handle map state internally?

Current write API calls that change internal map state never return promises; only read calls return promises because we cannot guarantee they will execute right away. Chaining API calls internally can be a nice enhancement to the current implementation, if implement properly.

Right now, the API calls are `halted` when the map is being rebuild (projection change, bookmark load, etc.) which means that any incoming API calls are queued until the map is ready and can accept them. After the map is fully loaded, all queued API calls will execute at once. The API is not modified based on the map state.


### > Promises or callbacks?

I would argue that callbacks act as promises in this case:

#### callback
```js
RV.changeProjection(newProjection, callbackFunction);
```
#### promise
```js
RV.changeProjection(newProjection).then(callbackFunction());
```

Looks about the same to me, but if we go with callbacks, we would need handle callback functions ourselves; with promises, well, we can just use promises :)

As to people expecting callback instead of promises, there should be no difference as long as we document our API.

### > When should it be released?

- 2.0 should be released with 1.7 API, no changes
  - we already have code for it, and it works (mostly)
  - we don't have time to re-implement more stuff - 2.0 is way overdue
  - it's likely soon we won't have manpower to implement this to a high quality
  - our main architect is indisposed, and I don't think we should redo everything without careful consideration that late in the process
- any changes to API / Plugins should be done in 2.1+
- support for 2.0 API should be maintained in 2.1+, because.

___

Unbridled refactor changes and lack of proper planning got us into 2.0 mess in the first place. Let's not do that again.

**Comment by jolevesq** [comment]
@milesap will you add the thing I need so I can push my coordinate info plugin?

**Comment by milesap** [comment]
@jolevesq yes, functionality will be in the PR for the coordinates plugin

@AleksueiR below are some changes to the original proposal and clarifications:

### API

The API is not bundled with plugins and remains in `rv-main.js`. Instead the viewers API would be passed to a special init function (can be anywhere on the page) such that the following will work:

```html
<html>
<head>
. . .
<script>
// called by viewer when api is callable. Multiple viewers will each call this function once. api contains viewer id so user can filter unwanted invocations manually.
function mapInit(api) {
    api.someMethod();
}

// possible addition - only called by a specific viewer with that ID
function mapInitViewerElemId(api) {
    api.someMethod();
}
</script>
. . .
</head>
<body>
...
<script src="rv-main.js"></script>
</body>
</html>
```
### Plugins

Plugins are bundled and included in the header since all plugin types are extendable. This allows custom plugins to be defined in the header like:

```html
<script src="rv-plugins.js"></script>
<script src="myCustomPlugins.js"></script>
```

or directly

```html
<script src="rv-plugins.js"></script>
<script>
class myCustomPlugin extends RV.base.somebaseplugin {
. . .
}
</script>
```

I'm ok with promises instead of callbacks to make my life easier :smiley: Although I'm wondering if promises should instead be returned for functions which cause an API halt and for entire sections of the API like layers or datatable that are loaded separately.

**Comment by james-rae** [comment]
Probably a lot I don't understand / mis-understand. Some incoherent thoughts:

* Unfortunate if we need to add two scripts to pages, but if that's best then lets make sure we document it and provide samples
* Would hope anything on viewer API that does things that are asynch would provide promise / callback and not just rely on "queuing things in order".  I could see user-devs needing to know when something is finished so they can continue their instructions.
* Release timelines: will defer to PMs

**Comment by milesap** [comment]
pod discussion with @mweech and @AleksueiR determined that no API changes will be made on v2.0 so it can be released on schedule. v2.1 will likely bring non compatible API changes to be determined at some future time.
