### ISSUE TITLE
Handle Feature Layer Service with Query function disabled

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#1965]
Appears a feature layer endpoint of an esri map service can have the query function disabled. We use the query endpoint to download attributes.

[Example Service](http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_CBCT_GEOM_3857/MapServer/0)

Discuss on how to handle it.
Grid has graceful failure (error indicator on screen). Need to test what happens in tooltips, identify results.

**Comment by AleksueiR** [comment]
Initially I was thinking about showing a notification that a layer has the query function disabled. However, if the layer was purposely added to the structured map, the author must have known about this limitation and it will appears as by design and no notification is needed. If the layer is added by the user, through the catalogue or using an RCS key, notification might be useful since the user might not know about disabled query setting for that layer.

Can we detect this at layer load? If so, we can simply remove corresponding controls, or disable them and show a notification similar to the wrong-projection one.

Thoughts?

**Comment by mweech** [comment]
We should definitely handle this case particularly for RCS/auto-legend cases.

**Comment by james-rae** [comment]
Also of note, services that do not expose `query` will not draw geometry when used in a Feature Layer.  They will draw if used in a Dynamic Layer

**Comment by mweech** [comment]
on further review, we should be looking to allow for structured legends to add such a layer and suppress identify/datagrid/etc seemlessly.  however, in an autolegend scenario the datagrid should be completely disabled, however we should indicate on Identify results with a message "No results.  This layer has been configured to not respond to queries." or something of that nature.

**Comment by james-rae** [comment]
Have found a way to detect if a service supports the `query` function without relying on a error/timeout.
The json of the service description has a property called `capabilities`, which is a comma separated string of values. A service with query function will have `Query` as one of the values.
