### ISSUE TITLE
Date layer symbology is rendered incorrectly

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#1972]
The symbology stack for the Datelayer (http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0) is distorted -
 symbols are repeated multiple times. 

![](https://i.imgur.com/Ub1yDOp.png)

Affects latest develop: http://fgpv.cloudapp.net/demo/develop/dev/samples/index-mobile.html

**Comment by james-rae** [comment]
Interesting Renderer / Legend in this service. 
The legend endpoint shows a nice, concise list
http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/legend

However, the renderer is a unique value renderer, and has entries for a number of different values and maps them onto the legend categories.
http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0?f=pjson

Since our symbology stack for features is driven off of the renderer, we get the above situtation -- an entry for every unique value, but the visible name is identical.

Some initial thoughts:

1. Add a `unique` pass to our symbology stack. Remove any duplicates (same name, same symbol)
2. Double check our code in the whole renderer processing, as I seem to recall us having some logic that made the assumption that labels were unique (and in this example, that is not true)

**Comment by james-rae** [comment]
Also, let's double-check our parsing of multi-field unique values.  It is a comma-separated string, but some of the values in this service have commas in the text.

E.g. `Fatality, Serious Injury (NEB or TSB), Not Applicable`
should be split `Fatality, Serious Injury (NEB or TSB)` , `Not Applicable`

**Comment by james-rae** [comment]
Followup 
- commas not an issue, as we generate the keys rather than split them.
- unique label assumption applied to the legend, not the renderer. A legend with two identical labels will result in ambiguous results

**Comment by AleksueiR** [comment]
[Date Layer](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0) lost all symbology in the datatable, but its legend does not have duplicates anymore:
![](https://i.imgur.com/sf1iOJB.png)

**Comment by james-rae** [comment]
Re-open

**Comment by james-rae** [comment]
After looking at the code running, it is a different issue.  I'll open a new one
