### ISSUE TITLE
Bookmarking not storing viewer state correctly

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#1983]
Viewer state not maintained for the following:
- [ ] ~~Eco Geo layers with bounding box enabled~~
- [x] Removed / reordered layers in autopopulated legend
- [x] Layer order is not preserved (autolegend only)
- [ ] ~~Datatable filters applied to map~~
- [ ] ~~Language is French~~

**Comment by james-rae** [comment]
The last three things would not be supported by the current bookmark structure (version `B'`). We would expect this kind of stuff once we start storing state on a third party storage provider.

**Comment by JahidAhmed** [comment]
Oh alright, edited above accordingly

**Comment by AleksueiR** [comment]
#### Re: Eco Geo layers with bounding box enabled
In 2.0 we switched from having a single bounding box for a dynamic layer to having bounding boxes for all its children. Since EcoGeo is a dynamic layer, it will have bboxes set up on its children. The [V2 Bookmark specification](https://fgpv-vpgf.github.io/fgpv-vpgf/v2.0.0/tutorial-bookmark_formats.html), doesn't account for bounding box settings on dynamic children. According to the spec, `<Child Item>` = `<Opacity><Visibility><Query><Root Flag><Layer Index>`. 
This situation is not idea - you lose bboxes on dynamic children - but it's valid. Full state restore should solve all this.

#### Re: removed layers
Not sure. Will check.

**Comment by AleksueiR** [comment]
The current implementation of V2 bookmark does not preserve removed layers. I guess we want this functionality. We should also add it to the spec.

**Comment by AleksueiR** [comment]
Changed layer order and removed layers are preserved in the bookmark now (autolegend only).
