### ISSUE TITLE
Data attributes for Google Tag Manager

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2064]
Data attributes need to be added so that Google Tag Manager can track statistics on the viewer usage for FGP.

Redmine issue: http://redmine.gcgeo.gc.ca/redmine/issues/8646

**Comment by phuppe** [comment]
Timeline for implementation desired by management: September

**Comment by yblain** [comment]
@phuppe we need to come up with a list of items to add data tags to.

**Comment by phuppe** [comment]
We need data-event tags on all the controls that perform viewer functions if we want to be able to judge their use.  For data layers, the data-event tag could be used to indicate that the data table was opened instead of trying to capture the layer information itself.  For buttons like "...", I do not think we need anything on those, because they are not really functions, but only intermediate steps to real functions.

**Comment by AleksueiR** [comment]
I would suggest, if resources allow, to add data-event tags to all interactive components, including "..." menu buttons. Menu buttons are intermediate steps, but valuable usability stability statistics can be gleamed even from them. For example, a user might open and close the menu several times without selecting anything when looking for some specific functionality she expects to be in the menu. 
Is it possible to capture mouse movements or key presses while panning and zooming the map? These might also be useful.

**Comment by phuppe** [comment]
Not sure we can capture mouse movements.  If we can, that would probably capture too much information. Regarding key clicks for panning and zooming, that may be possible.  I will have to investigate.

I agree with your comments about the "...".

**Comment by AleksueiR** [comment]
We don't need to capture all mouse movements, just the "drag" events (click, move, release). Scrollwheel events might be good to capture as well.

**Comment by phuppe** [comment]
I will investigate that.

**Comment by phuppe** [comment]
I have done more digging into Google Tag Manager (GTM) and found a way to allow us to capture what we need and send back desired information.  We can use attributes the begin with "**data-**" and GTM takes care of getting that information.

Because we want to capture to use of specific functions, we will not have to bother with the fact that there may be more than one application per page.  For each feature we want to capture information for, we would add the following:

`<htmltagname ...  data-feat="feature name" ... />`

where "feature name" would be a value like:
- menu
- geolocation search
- basemap
- layers
- etc...

For layers, we could capture more information:

`<htmltagname ...  data-feat="layer" data-uuid="metadata UUID value for this layer" ... />`

**Comment by milesap** [comment]
This sounds like a good candidate as an external plugin if the API moves towards implementation. We can further discuss at next weeks api meeting. Based on the current api design, this feature would be fully supported.

**Comment by phuppe** [comment]
In testing, I have found that to ensure I get the data if the user clicks on the icon or just beside it, I need to add the "data-" attribute to both the button and its child icon tags:

`
<button data-feat="layers" class="md-icon-button primary .....>
  <md-icon data-feat="layers" md-svg-src="maps:layers" .......>
</button>
`

**Comment by AleksueiR** [comment]
Came across an interesting project to track user activity: https://www.fullstory.com/

**Comment by phuppe** [comment]
Interesting indeed.  I will pass it on.

**Comment by AleksueiR** [comment]
Related issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2733

**Comment by mweech** [comment]
This issue appears to be orphaned albeit some related research applies.
