### ISSUE TITLE
Unable to import some Json files

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#2096]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily11/prod/samples/index-samples.html

Test data:
[convert.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/1122784/convert.zip)
[happyEnhance.zip](https://github.com/fgpv-vpgf/fgpv-vpgf/files/1122797/happyEnhance.zip)

This test data works in Firefox. However, for some reason does not work in Chrome. Importing this file gives the below error in  Import Panel. Please investigate

![image](https://user-images.githubusercontent.com/18539315/27839630-9e023890-60c0-11e7-884b-7c5a9a2409b6.png)

**Comment by AleksueiR** [comment]
I'm getting
> rv-main.js:94469 Possibly unhandled rejection: urn:ogc:def:crs:EPSG::3978

It fails here: https://github.com/james-rae/geoApi/blob/refactor/src/layer.js#L955
If you try to add the same file again, after it failed, everything works.

@james, I vaguely remember that we had a similar issue before. Any ideas?

**Comment by james-rae** [comment]
Weirdness.
It happens consistently for me in Firefox and Chrome. Using `convert.json` will trigger it because that file is in a projection that is not hardcoded into `proj4`.

We do a projection lookup for both the in and out projections ([code here](https://github.com/fgpv-vpgf/geoApi/blob/v0.0.0-protoLR-76/src/layer.js#L947)) . 
Our lookup returns a promise. It resolves immediately if we have the projection, or does an asynch lookup, which then registers the projection and resolves when done. ([code here](https://github.com/fgpv-vpgf/geoApi/blob/v0.0.0-protoLR-76/src/layer.js#L848)) .

Am noticing `projectionLookup` returns a `Promise` when the projection exists, but returns a `$$state` object (which has a `then` function) when it needs to do the lookup.  
Way down the call stack is an `$http.get()` call. ([code here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.0.0-daily15/src/app/geo/layer-blueprint.class.js#L218))

So order of events is

1. First attempt to load file
2. Our two lookups result in a resolved promise and a `$$state` object.
3. The promise chain [here](https://github.com/fgpv-vpgf/geoApi/blob/v0.0.0-protoLR-76/src/layer.js#L986) treats both lookups as resolved and executes `buildLayer` prior to the projection lookup completing.
4. Layer fails because there is no projection definition.
5. The `$$state.then()` eventually returns, and the projection is registered in `proj4`
6. Second attempt to load file
7. Both definitions exist, two resolved promises are returned by our lookup attempts
8. Layer loads fine because it has both projection definitions

**Comment by AleksueiR** [comment]
This happens in 1.7.0 as well, so it's should not be related to any changes done in 2.0 refactor.

**Comment by james-rae** [comment]
Problem was in the way promises were being declared.
Originally [this code](https://github.com/fgpv-vpgf/geoApi/blob/v0.0.0-protoLR-76/src/layer.js#L986) was a lovely pyramid of doom. Was then re-written after code review to use the chained promise structure to collapse the pyramid. The assumption at the time was the promises were declared, then invoked in order at the chain at the bottom of the function.  This was not what actually happens; the promises were invoked at declaration, so the `buildLayer` promise body would run prior to the thread hitting the chain.
By changing it from a declaration to a function, it now gets called when we want it to run.  Lesson: leave working code alone.

`$$state` is just the angular promise prototype.

**Comment by james-rae** [comment]
Issue ready for QA once geoApi `v0.0.0-protoLR-77` or higher is referenced by the viewer
