### ISSUE TITLE
Map click still displaying Feature Details results for sample file 21 (Layer with Query disabled)

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2097]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily12/prod/samples/index-samples.html

![image](https://user-images.githubusercontent.com/18723160/27839837-7abbc7b4-60c2-11e7-952c-a37ba6b551af.png)

![image](https://user-images.githubusercontent.com/18723160/27839871-a9cf962a-60c2-11e7-91de-781d89644d1e.png)

**Comment by AleksueiR** [comment]
This is the expected behaviour.

The following line only disabled the UI control that allows user to change whether the layer is queryable or not:
```json
"disabledControls": [
         "query"
]
```
Here the query control is greyed out and cannot be clicked:
![](https://i.imgur.com/5qdlCHi.png)

____

To change the default value of the "query" setting, the config `state` property should be used. For example: 
```json
{
  "id": "powerplant100mw-1",
  "name": "Power Plants, 1",
  "layerType": "esriFeature",
  "state": {
    "query": false
  },
  "url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/1"
},
````
