### ISSUE TITLE
Remove is not an option in legend

### ISSUE THREAD

**Issue by barryytm** [fgpv-vpgf/fgpv-vpgf#2126]
When `remove` was added in `layers` under `controls` in a config file.  

![capture2](https://user-images.githubusercontent.com/19259169/27930269-fc9df67e-6263-11e7-93e2-36ea40d47232.PNG)

The following appeared when the "more options icon" was clicked.

![image](https://user-images.githubusercontent.com/19259169/27930236-d7246388-6263-11e7-8e8a-46e15f09e5aa.png)

**Comment by AleksueiR** [comment]
Happens because of this line: https://github.com/AleksueiR/fgpv-vpgf/blob/9999-udpate-layer-import-checkbox/src/app/ui/toc/templates/legend-node.html#L38

This condition is no longer valid as the "remove" control can potentially be available in the structured legend on user-added layers, so it's not removed from the default control list but is hidden dynamically. This causes a situation when the "remove" control should be available according to the config, but is not due to the logic here: https://github.com/AleksueiR/fgpv-vpgf/blob/9999-udpate-layer-import-checkbox/src\app\ui\toc\legend-element-factory.class.js#L272.

A nice solution would be to decorate the menu directive so it will hide itself if no interactive elements can be found inside.
