### ISSUE TITLE
Datagrid from config-sample-34 remaining after switching to other test samples

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2136]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-daily15/prod/samples/index-samples.html

- Load daily build and select sample 34 (Set table open by default)
- Switch to other test samples

Datagrid from config-sample-34 remained, this layer is not contained under legend though.
![image](https://user-images.githubusercontent.com/18723160/28024673-631619a6-655f-11e7-89ab-71bb2b90e11b.png)

**Comment by AleksueiR** [comment]
Switching between configs needs to close already opened panels.

**Comment by barryytm** [comment]
This only happens in the `index-samples.html` file due to the data and UI relating to the data table not being destroyed when selecting a different sample(different config).  However it is not an actually feature of the viewer and it is a minor problem thus I don't think it is important enough and necessary to fix such issue.
