### ISSUE TITLE
Unable to apply filters to map for file layers

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2202]
No `Apply to Map` option for file based layers

**Comment by JahidAhmed** [comment]
That makes sense, thanks for the clarification!

**Comment by AleksueiR** [comment]
Is it at all possible to somehow filter file-based feature layers manually? If possible, do we even want to do that?

**Comment by jolevesq** [comment]
I tried to find an easy way fews years ago when I implemented this in GCViz and didn't find anything. Maybe with version 3.20 (I was on 3.12) there is a way but I doubt.

We can use graphic layer and deal with add remove items based on filters but it is not out of the box. To have it on file base layer will reduce the confusion for users for sure but it is not an easy modification.

**Comment by AleksueiR** [comment]
Let's keep this issue in the backlog then.

**Comment by barryytm** [comment]
Ignore the reference regarding to 2399, made mistake.  After investigating this issues , I can confirm that `ArcGIS 3.21` does not support queries that need to be performed on the server when creating `FeatureLayer` using the second overloading constructor which takes a `featureCollectionObject` and `options` as oppose to a URL.

**Comment by james-rae** [comment]
With WFS coming into the fold, this might get priority bump.
Reminding everyone of this fun repo: https://github.com/RAMP-PCAR/rql-nodojo

If we decide to use it, it probably needs a re-package into something that will play correctly with module loaders and webpack.

Once working, a parser to convert the definition query format into rql format could go a long way.  We probably want to restrict ourselves to non-super-fancy queries in the beginning.

Other options should be explored as well.

**Comment by milesap** [comment]
## WFS 3.0 layers
geoApi does not support WFS v2.0 layers natively, although ESRI 3.24 does offer support for v2. WFS 3 is still in its initial draft stage. 

https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html

For the purpose of supporting WFS 3, the resulting geoJSON file will be treated as an ESRI feature layer. 

See https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2202#issuecomment-331915786 and
https://developers.arcgis.com/javascript/3/jsapi/featurelayer-amd.html#featurelayer2

> Does not support queries that need to be performed on the server, for example queries with a where clause or non-extent based spatial queries.

Since the WFS layers are serverless, and the ESRI api will not support local queries, we will need to implement local filtering ourselves.

Reviewed the code at https://github.com/RAMP-PCAR/rql-nodojo/blob/master/js/rql.js as suggested by James and I don't see any issues with reviving it for use in RAMP. Minor work needed to fully modularize the library and integrate it. The queries we'll be supplying won't be complex and we can expand upon `rql-nodojo` as needed. 

I don't think `rql-nodojo` is a good candidate for being an intention since the scope of work to replace it would be large and unlikely to be done. Let me know if anyone feels differently. 

🐌

**Comment by mweech** [comment]
@milesap please take a look at how to apply filters at query time for the GeoJSON from the WFS 3.0 so we can make sure we have a full picture of how to query/filter WFS 3.0.

**Comment by milesap** [comment]
### 7.13.5. Parameters for filtering on feature properties

There are two examples of filtering under [this section](https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html#_parameters_for_filtering_on_feature_properties) of the draft proposal. 

There is also a demo site https://app.swaggerhub.com/apis/cholmesgeo/WFS3/M1

Will continue to investigate

**Comment by james-rae** [comment]
A little fun fact to add: found that `rql` is supported as an [npm library](https://www.npmjs.com/package/rql).

Still debatable if it's the best path forward, but removes the conversion effort to a proper js lib.

**Comment by james-rae** [comment]
Implemented by https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3062
