### ISSUE TITLE
User added layers appearing on top of their respective groups for auto legends

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2253]
Tested build: http://maps-cartes.dev.ec.gc.ca/sandbox/ramp2_test/v2.0.0-rc4/prod/samples/index-fgp-en.html?keys=JOSM,EcoAction
Test data: ne_10m_airports.zip (Feature layer)
http://geoappext.nrcan.gc.ca/arcgis/rest/services/NEB/Incident/MapServer/0
(added as Dynamic layer)

It seems the rule "For auto legends, user-added layers are added at the bottom of their respective groups (Feature or non-feature)." is not working in current build, see below screenshot. James sent out this in an email regarding Layer Ordering.
![image](https://user-images.githubusercontent.com/18723160/28537498-1ad8029c-7079-11e7-920e-c5ebf5c4c98a.png)

**Comment by AleksueiR** [comment]
Yeap, this is inconsistent with previous implementations (<=1.7).
Can we modify the rules and have all user-added layer to be added at the top of the legend or their respective groups?

We assume users want to see the data they are adding :), so user-added in the structured legend go on top of everything else. Otherwise, they can be partially or completely obscured by other layers without an option to reorder them.

With the auto legend, the user can reorder the layers, so it is very important where in the list the user-added layer will end up (the argument about added data being obscured still applies though). That's said, for consistency between two legend types and the existing behaviour in 2.0, let's have user-added layer be added to the top of the legend.
