### ISSUE TITLE
Map Export not finish loading when selecting Mercator projection

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2261]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc5/dev/samples/index-samples.html

It seems legend, scale, north arrow, footnote could be loaded, but not for map points and basemap.
![image](https://user-images.githubusercontent.com/18723160/28579427-ad99299c-712a-11e7-8a6f-7306c6759d4c.png)

**Comment by AleksueiR** [comment]
> Layer "layer3": Unable to connect to map server at http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer.

![](https://i.imgur.com/1Xisgm0.png)

**Comment by james-rae** [comment]
Encountered same failure outside the firewall (on my mobile phone).

Attempting to use ESRI's public print server resulted in failures for both Lambert and Mercator Maps.  Assuming that service is down/broken or restricted due to people using it all the time.

Using a print service hosted at a college in the US resulted in success.

So would appear to be some type of issue with the print service or whatever types of proxies/firewalls are doing things on the server it resides on.

**Comment by AleksueiR** [comment]
I suggest closing this as out of our control and opening another one to provide meaningful error messages in such cases when export fails (I'm sure there are some try/catches already, but they don't seem to be enough.

**Comment by mweech** [comment]
@AleksueiR go forth and re-create. :+1:
