### ISSUE TITLE
Full Screen mode - Open Settings for each layer will hide Layers panel

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2266]
Tested build: http://fgpv.cloudapp.net/demo/v2.0.0-rc5/dev/samples/index-samples.html

Close icon (X) becomes an arrow, that could close the Settings.
![image](https://user-images.githubusercontent.com/18723160/28588265-020655d2-7148-11e7-825e-612bc9799814.png)

**Comment by AleksueiR** [comment]
After looking into this for a bit, it seems IE "thinks" this fullscreen is "mobile" layout for some reason, and that's why close buttons are replaced with arrows.

**Comment by JahidAhmed** [comment]
When we enter fullscreen, in IE the width of the element goes from 1660 to ~600 and thus the `currentLayout` is set to `medium`.

I found a similar [issue](https://connect.microsoft.com/IE/feedback/details/838286/ie-11-incorrectly-reports-dom-element-sizes-in-fullscreen-mode-when-fullscreened-element-is-within-an-iframe) related to iframes.

**Comment by JahidAhmed** [comment]
Similar to #2052, this only happens on `index-samples`. The width in `index-mobile` is 0 and that case was handled earlier, so the layout remains what it previously was. (If it was medium before, the problem will still occur though)

**Comment by AleksueiR** [comment]
I think this can be done more elegantly -  when switching to the `full-screen` mode we can assume the end size of the map container to be equal to the current screen size (it's full-screen mode after all), `LayoutService` can use these dimensions to determine the appropriate layout ('large/medium') instead of trying to get the current width/height from the root element or the map container itself. Also, when switching back to the normal mode, the previous size (judiciously stored beforehand) can be used to determine the correct layout. See this comment https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2318#issuecomment-322535162 with the same idea applied to re-centring the map after `full-screen` toggle.
