### ISSUE TITLE
Full-screen does not re-center the map after transition in IE

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2318]
When entering full-screen, the map is re-centered to keep the extent center in the center of the new container. This doesn't happen in IE - when entering the full-screen mode, the map keeps its relative position to the left upper corner; when exiting the full-screen mode, the map is re-centered but it just pushes it further up and to the left. If you cycle the full-screen mode enough time, the map will be pushed so far that nothing is visible anymore.

**Comment by JahidAhmed** [comment]
The problem is occurring [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/common/full-screen.service.js#L202). The current timeout value is not enough for IE and the right size and extent is not provided.

A possible solution is to remove the timeout completely and store the current position before entering full screen mode and then using the screen resolution, calculate the correct offset and center the map accordingly.

**Comment by AleksueiR** [comment]
Was looking at how the full-screen services works, and it seems there is a bunch of unnecessary DOM manipulations there. The initial implementation - the one not using HTML5 full-screen capabilities - animated the map container to offset it manually during the transition. This would keep the center of the map as you see it in the center of your screen. The timeout was to remove artificial offsets applied to the DOM elements and to call maps reposition and resize functions. All this should have been seamless. Try full-screening this sample: http://fgpv.cloudapp.net/demo/v1.7.0/prod/samples/index-fgp-en.html
Someone wrecked it while switching to HTML5 fullscreen capabilities. I would like to restore the same smoothness in the fullscreen transition. I'm afraid there is no quick fix for it and the whole service needs a refactor.

**Comment by mweech** [comment]
please provide a synopsis of the scope of the refactor and specifics on the design of what should be accomplished.

**Comment by milesap** [comment]
`full-screen.service.js` is relatively small, mostly animation stuff that will need to be redone anyways. 

The trick, if one even exists, is to have the ability for an animation during fullscreen transition. Fullscreen is OS level, and the browser may just be snapped into fullscreen position without any say in how that would animate. I speculate a bit here since I could imagine an OS has ways of animating fullscreen changes. But that would differ on each OS, and then each browser would need to support those. I'll look into that. Prior to this, we just animated inside a browser window which is obviously well supported.
