### ISSUE TITLE
Tabbing in datatable body extremely slow

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2324]
Holding tab to go through elements in the body of the datatable gets slower and slower the longer it is held to a point where it doesn't seem responsive at all.

**Comment by AleksueiR** [comment]
Could it be the Focus Manager is slowing it down?

**Comment by milesap** [comment]
Holding down the tab key triggers the corresponding event watchers many many times a second - each of which activates the expensive `shiftFocus` method in the FM. Instead of the usual debounce solution, I would suggest we instead have FM ignore focus requests while one is being processed. 

FM should also output some angry console warnings when a request needs to be ignored because they are tabbing too fast.

**Comment by AleksueiR** [comment]
I don't think angry console messages are needed - people tab in different ways, and how can you define what is too fast.

**Comment by milesap** [comment]
Estimate has been bumped up, this one's tricky... With FM completely disabled, there is no change in tab speed. 

Profiling the performance is shown below. Starting from the left is when the tab key is pressed, then we can see the massive computations (and the JS heap growing on the blue line chart). At the end, the next element is finally selected. Same pattern occurs with smaller data sets but computations happen faster.

![performance](https://user-images.githubusercontent.com/10187181/33219119-9eab40d4-d10e-11e7-81a0-38488eb47ff1.png)

A few avenues to explore:
- See if jQuery is wrapping focus and doing a horrible job. I can't see a browser struggling with this (other than IE).
- If this is related to the scroller extension rendering all rows at the same time. Solving this would likely solve this issue in an in-direct way due to the reduced dom nodes needed for "whatever this computation" is doing.
