### ISSUE TITLE
API / Extension Discussion

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2346]
#### Latest docs can be found at http://fgpv-vpgf.github.io/fgpv-vpgf/api/index.html
----

This issue is for lively ~~debate~~ discussion over some changes when the full external API gets rolled out under v3 some time in the future. Feel free to post your thoughts on any/all of the topics below. Nothing is final and this continues to be a `wip`.

### geoApi

Custom implementations of geoApi could be imported into the viewer as we do now for geoApi. So instead of 

```js
import geoapi from 'geoApi';
```

a map author could do

```js
import customGeoApi from 'customGeoNpmPckg'; // when installed through npm
import customGeoApi from '../customGeo/index'; // or when files are inlined with viewer, though this is not preferred as it makes viewer code updates more difficult (don't delete your custom files!)
```

This means custom implementations cannot be added on runtime - instead the viewer needs to be built with the custom implementation. This makes some sense since the API will need the geo implementation before it can be used anyways.

If this is the preferred way, we'd likely want to provide typescript declaration files which would enforce a geo interface on build. 

###  Code Splitting/Plugin Bundling

We want to make some parts of the viewer as optional bundles of code (so if they're not needed they can be omitted to speed up the viewer, like data tables). They would be bundled as separate files, included in the distribution or be provided in separate repos, and would only rely on the external API. 

We have a few options at this point:
1. Like it is now, keep their dependencies in sync with the core viewer. There would only need to be minor changes done so that they work with the external API. Since they would require dependencies from the core viewer like jQuery, they need to be built with the viewer and are not strictly independent. Their code base would likely reside in the viewers repo (in a separate "plugin" folder)

2. Move them all out of the repo into one plugin repo. This repo would be built separately from the viewer. All the plugins would share the same dependencies - but in theory do not require to be the same as the viewers. So this opens the possibility of upgrading the plugins to Angular 4, jQuery 3, or whatever else we think will boost their performance (without needing to do the same with core). The bundling would look something like:

```html
<script src="rv-main.js"></script>
<script src="rv-plugin-core.js"></script>
<script src="rv-plugin-datatable.js"></script>
```

3. Lastly, each plugin could be in its own repo where it is bundled with its dependencies. This would make each plugin larger since each has its own bundled dependencies (where duplication can exist between plugins). However, since each plugin only bundles the dependencies it needs some plugins could be significantly smaller than the option 2 approach above. Some plugins for example may not require angular, but with option 2 it would need to be in `rv-plugin-core.js` since some other plugin needs it.

Maybe there's a hybrid approach to 2 and 3?

### Config vs. API

Should there be API overlap with the config? Likely yes since third party plugins may want to make changes without the map author needing to modify the config. Or only provide API to functionality not available in the config, and perhaps allow plugins to submit a full/partial config which is merged into the main one.

**Comment by AleksueiR** [comment]
Shouldn't we align exAPI closer to the config, internal implementation and naming?

There are `LatLng` and `LatLngBounds` globals for example, which seem to be `Point` and `Extent`. Why do we want to use different names? I thought this could be done to make it easier to people to work with the API, but anyone using API will probably be familiar with the config already anyway.

A subset of the config's `map` section can be used as the API `Map`s constructor instead of defining a new set of options which then need to be mapped to existing options. 

`Map` class has a `data` property which is the same `layers` in the config's `map` section, and API `legend` is specified under its `UI` section. `legend` can be moved under the `Map` class for consistency. Both `LegendEntry` and `Layer` should probably accept JSON snippets with the same structure as their config counterparts. 

If we get rid of layer types at the API level, we still need to map them to the proper layer types in the viewer/geoApi level anyway. Some layer types have exclusive properties dynamic (`layerEntries` for example) which need to be specified somehow.

**Comment by milesap** [comment]
`Data -> Layers` sounds good to me.  

`LatLng` and `LatLngBounds` have different units (I think) than `Point` and `Extent`. Although I can also agree with either supporting all four, just `LatLng` and `LatLngBounds`, or just `Point` and `Extent`.

I think keeping `Layer` as one universal type will keep it simple for outside developers and is likely more than enough to satisfy plugin authors. If you need fancy layers, you can always use the config along with the API.  If there's a picky layer type we can banish it from the API altogether. I think as long as our API remains universal (nothing esri specific) and relatively simple to pickup then I'm happy. 

> legend can be moved under the Map class for consistency.

:+1: 

> Both LegendEntry and Layer should probably accept JSON snippets with the same structure as their config counterparts.

Maybe, or maybe nothing including `layers` should accept config snippets.

**Comment by AleksueiR** [comment]
Hm, still not convinced you can get rid of layer types. How would you add a single child or several children from a dynamic layer? I wouldn't consider them to be fancy layers.

**Comment by milesap** [comment]
I'm no expert here, so I'll defer the layer discussion outcome until everyone has a vote. My only concern is if dynamic layers are esri specific (not sure that they are). If they are I think we'd be heading down a slippery slope in hard coding vendor specific types into the API. There would be many layer types from different vendors that would need support and I can't yet see how we could support that.

In theory the API could support layers that are defined in geoApi, so a custom geoApi implementation could define different types of layers for the API. Though this doesn't seem very different than having someone extend a base api layer to support their custom layer type.

**Comment by james-rae** [comment]
Some random thoughts.

Overall, I feel I'm missing the big picture of what the API does. I see lots of abstract classes and calls, but not sure when I'd use them or what for.

Maybe having an example of applying a real-world use-case to this design would help understand, as well as verify the approach works?  E.g. how would we implement Mark Lague's Clip-Zip-Ship plugin here?  Doesn't have to be a formal writeup, some paper drawings & pod discussion would suffice for now (something more concrete when it's clear that it's what we want).

### Layers via API

- What do we want to do with layers via the API?
- If answer is "anything", maybe just allow API to give various proxy objects to host page?
- If answer is restricted things, I think we need to determine what those things are.

### Differences in Layers

- parent-child structured / single feature class
- attributes / no attributes
- file based / service based
- image / vector (further broken to on-demand / snapshot / vector as image)
- logical features / physical features ( Might be worth reviewing the [LayerRecord class heirarchy](https://github.com/fgpv-vpgf/geoApi/blob/v2.1.0-12/src/layer/layerRec/main.js#L14) for more on this )

So  you can see how putting support for all these types into a general `Layer` class that just works can be a trick.

### Being MappingAPI Agnositc

We already have MappingAPI specifics throughout the app

- config structure
- legend generation
- details display panels
- import wizard options

While being MappingAPI agnostic is good from an academic standpoint, I don't see this ever happening in the real world without being accompanied by a full refactor.  If a choice is easy, always go for agnostic option. If going agnostic greatly increases the complexity, it should at least be discussed on merits of practical value.

### Layer Class

Is the [Layer Class](http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.layer-1.html) tied to real layers? Or just meant to do unbound vector graphics on the map?

- `[get|set|forEach|remove]Property` . What is a property? A property of the LayerRecord? An attribute of a feature?
- `[get|set]Geometry` . Only valid for certain layers. Some geometry exist only on server, can't update them.

**Comment by milesap** [comment]
I've added a detailed introduction + samples to the link above. Hopefully it helps to explain the general flow of the API and some of the issues you raised.

Good points for our api meeting next week. In regards to not `Being MappingAPI Agnositc`, this would imply that we would (more or less) further lock in to the world of esri. I'm ok with this, but a few things we need to consider or acknowledge: 

- If geoApi is forked or replaced to use non-esri or leaflet, all extentions (including the core ones we write) would no longer work. 
- We plan on moving some things out of core into extentions, like data tables so:
    - We scrap this idea
    - We make geoApi mandatory on esri
    - We make the user fork the plugins they want and customize them to work with their geo implementation.

If we do decide to take the esri road, it may no longer make sense to have geoApi in a separate repo.

**Comment by mweech** [comment]
brief thoughts:
- we shouldn't take an approach that requires plugins to be kept in a particular repository.   plugin authors should be able to manage them in their own repo's.  this may result in some bloats with dependency overlaps, but this is where we can pursue a core vs external plugin approach.  core ones we try to keep aligned to minimize overlap, and allow external to be managed seperately

- i would agree with James that we should take a User Story approach to developing the API.  what are the capabilities  a plugin would need? we can model out a few and make sure we are judging success against the ability to implement these (i.e. alternative datagrids, clip/zip/ship, geocoding, etc., custom identify behavior, external map layers toggling and/or map centering, etc)

**Comment by james-rae** [comment]
Pre-weekend thoughts.

The doc examples have helped immensely. 

This is....ambitious! Very powerful if implemented.

Semi-formed idea regarding layers belonging to specific mapping APIs:

The viewer as it is today has what I'll call _supported layers_. Even if I were to modify geoApi to have a new layer type (e.g. WMTS -- open version of ESRI Tile), I'd need to make changes in the viewer for WMTS to actually be supported. 
- New config defs for defining that kind of layer. 
- Legend logic (e.g. make it consider projection. define how it behaves for re-ordering)
- Add relevant logic to Import Wizard
- Details behavior (in this case, to be ignored from identify / show no details)

Three potential paths forward on this (there are probably more)
1. Our API exposes supported layer classes instead of generic layer class. I'm still not deep enough into this to know if this approach breaks the concept of plug-ins.  This approach puts the complexity of layer differences on the API user / plugin implementer.
2. Our API layer takes generic layer requests, inspects the internal layers, and figures out how to translate the generic request to supported layer types. This approach gives us some generic-ness and lets us bypass another large refactor on the viewer/geoApi. API would have to react if mismatches happen (e.g. attempt to open grid on a tile layer).
3. We totally abstract Mapping APIs from the viewer.  This goes whole-hog for "geoApi determines mapping API, viewer should work with any geoApi as long as it implements the correct interface".  Probably the most amount of work, and would give the most amount of flexibility. Discussion point would be something like "if we build that level of flexibility, how much would it be used? would the effort pay off in realized value?"

Some of our things are already well abstracted. Others, not so much. Will be interesting to see how many things need a good ol' REFACTOR.

Fun fact: the initial reason `geoApi` started in it's own repo was to isolate dojo.

**Comment by milesap** [comment]
#### October 10th API meeting notes

- add an `RV.registerPlugin(filenames)` to the api which handles the loading and plugin initialization
- Rename `LatLng` and similar classes to `XY` - we will enforce geometry units as decimal degrees
- Add `Polygon` to `RV.GEOMETRY` types
- Add `Annotation` to `RV.GEOMETRY` with a text property for display on the map
- Allow a standard popup to be triggered open/closed  in addition to the panel controls
- Add more mouse events to the map class to allow drawing tool type plugins
- Add a "`fetchData`" option on layers so data downloading can be invoked through api
- Add a "`setQuery`" option on layers (and corresponding events) 
- Add config reloading on map instances
