### ISSUE TITLE
Export map ignoring opacity of certain layers

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2369]
'Certain layers' could possibly be feature layers, not entirely sure the case.

Tested build: http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html (Sample 41)

Setting the opacity of the layer to 0 and opening the map export still shows the layer on the map.

**Comment by AleksueiR** [comment]
Yes, seems like the export functionality ignores opacity set on feature layers. This happens because the code "steals" svg elements directly from the map DOM node. I guess in the process the opacity set by ESRI gets lost, so the layers are rendered as fully opaque.

**Comment by AleksueiR** [comment]
@JahidAhmed and I did some digging and it turns out that the library we are using to convert svg to canvas (canvg) has a bug that ignores nested opacity values: https://github.com/canvg/canvg/issues/510.

Even worse, the library seems abandoned and there is no chance this is getting fixed. We would need to find another way/library to do the conversion. First think I would check is Highcharts source code since they have a export to image/pdg function. We can find how it works and ~~steal~~ get inspired.

**Comment by AleksueiR** [comment]
Somewhat related to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2392.

**Comment by AleksueiR** [comment]
We should try using [native methods of drawing svg to canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas) instead of relying on the discontinued canvg library.

**Comment by milesap** [comment]
Opacity can be set on canvas, but not on the individual image/svg elements that compose it.

Demo:
http://jsfiddle.net/vnj18ahn/
