### ISSUE TITLE
Optimize layer loading

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2419]
Adding 25+ layers causes the viewer to appear unresponsive and it takes a noticeable amount of time to recover. 

We can improve this by reducing the amount of service calls to "as-needed", and allowing some layer info to be added to the config instead of a service hit.

**Comment by AleksueiR** [comment]
The loading takes time because each service is interrogated and and is added to the map even if the layer is not initially visible. We do this partially to get the layer name and structure (for Dynamic). I don't think we can avoid this with the auto-legend.

In case of a structured legend, when all the legend blocks are given names and everything, maybe we can provide a config option to suppress this initial service query for layers that are not initially visible. We can generate legend blocks for the rest of the layers and only query their respective services when they user toggles these layers on.
