### ISSUE TITLE
Clicking Reload for failed CESI layer will remove the layer from the legend

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2425]
Tested build: http://fgpv.cloudapp.net/demo/v2.1.0-daily02/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways

- Click below Reload button for CESI (which was failed on initial loading)
- CESI layer got removed under the legend (2nd screenshot)
![image](https://user-images.githubusercontent.com/18723160/31628146-c830c0be-b27d-11e7-90d9-085a0bfa96f9.png)
![image](https://user-images.githubusercontent.com/18723160/31628218-0444c6ea-b27e-11e7-9196-bb04fce96d34.png)

**Comment by AleksueiR** [comment]
The problem is here: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/legend.service.js#L189

The legend block is being added back in the layer selector only after the `rv-loaded` event occurs on the layer record. If the layer fails, the corresponding block is never added back. I think this was changed from the initial implementation to re-open any panels on layer reload. 

As a solution - re-add the block immediately and return the promise which resolves when and if the layer loads correctly.
