### ISSUE TITLE
Map Click on point from Dynamic Layer nothing visible

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2481]
When a user clicks on a point from a dynamic layer, everything fades out, including the clicked on point.  The behaviour is different from a feature layer where the point that was clicked on remains visible and all other items fade out.

**Comment by james-rae** [comment]
Interesting.  It *should* be adding the highlighted item.  Could you provide the layer URL you're using so we can test it out?

**Comment by ppollock** [comment]
http://fgpv.cloudapp.net/demo/v2.0.1/dev/samples/index-samples.html

And others...

**Comment by barryytm** [comment]
Tested on http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html sample#4
![graphic4](https://user-images.githubusercontent.com/19259169/32955561-5a14c16e-cb84-11e7-970f-23baaeb71457.gif)

**Comment by james-rae** [comment]
Yep clearly some funny business going on. Thanks for the bug report Patricia

**Comment by ppollock** [comment]
Thanks for your quick responses!

**Comment by james-rae** [comment]
This appears to be caused by the map service definition.  Take a look at the fields for the [Natural Gas Layer](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/21)

```text
OBJECTID ( type: esriFieldTypeInteger , alias: OBJECTID ) 
OBJECTID_1 ( type: esriFieldTypeOID , alias: OBJECTID )
```

The real object id is `OBJECTID_1`, which RAMP will recognize and use. But both fields have the same alias.


If we do an [identify](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/identify?f=json&tolerance=5&returnGeometry=false&imageDisplay=1853%2C913%2C96&geometry=%7B%22x%22%3A821037.5448734241%2C%22y%22%3A-208156.20256540546%7D&geometryType=esriGeometryPoint&sr=3978&mapExtent=568095.3723224123%2C-529890.1793666924%2C1548643.1667513347%2C-46760.046439759826&layers=all%3A17%2C19%2C21) on point `Lake Superior` (near Sault St Marie), you can see the result from ArcGIS Server only gives an `OBJECTID` field (value `2062`). The `OBJECTID_1`  This is because Identify results have attributes indexed **by alias** (to make it human readable). The duplicate aliases in the service definition cause the values to get written into the same property.

However, the real `2062` is [Lennox Power Generation](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/21/2062), which is what get's hilighted (near Kingston). The [Lake Superior](http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer/21/2061) location is in reality `2061`, but has the fake object id as `2062`.

Because the server actually removes the correct value, the viewer has no way to accurately determine which feature we are talking about. It treats the incorrect number as valid and we get a hilight in a different location. Being a service issue, there is no fixes we can do in code to resolve this.

I'm going to think a bit more on other alternatives (e.g. checking for this situation and alerting the user?).

**Comment by ppollock** [comment]
I discovered this behavior with a service that does not have two OBJECTID fields nor does it have two attribute fields with the same alias but this service is not visible outside NRCan.  I will try to find an example that you can see...

**Comment by james-rae** [comment]
Worst case maybe we can do a webex looking at your screen.  Let us know

**Comment by ppollock** [comment]
This double OBJECTID related problem is important and I think I have figured out the unexpected behavior I am seeing which is unrelated to the double OBJECTID.  I have sent an email to a group who hopefully will be able to address the double OBJECTID on the NACEI services.

For my issue I will open a new issue with more details.

**Comment by ppollock** [comment]
The new issue is:
#2492
