### ISSUE TITLE
Complex Cartography Rendering for Dynamic Service

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2492]
Now that FGPV allows for the inclusion of Dynamic Layers into the map there are some unexpected behaviors that are popping up.  These unexpected behaviors are mostly occurring on services with complex cartography, such as:
- labels using Maplex (Indigenous Place Names)
![image](https://user-images.githubusercontent.com/5502696/33214374-ac349f6c-d0f9-11e7-827d-06be615a13fc.png)
- hatching (Petroleum Administrative Areas)
![image](https://user-images.githubusercontent.com/5502696/33214412-d679eb60-d0f9-11e7-848f-28e996448e26.png)
- cartography with a set reference scale (Wind Energy Potential)
![image](https://user-images.githubusercontent.com/5502696/33214470-17dcb6aa-d0fa-11e7-842c-58f8c0cc0fab.png)

The unexpected behaviors are:
1. When clicking on the layer to obtain "Feature Details"
![image](https://user-images.githubusercontent.com/5502696/33214635-c067d5c0-d0fa-11e7-9732-bedbf03334e6.png)
![image](https://user-images.githubusercontent.com/5502696/33214644-cc1a0d8e-d0fa-11e7-8b10-3eff7bbfb318.png)
OR
![image](https://user-images.githubusercontent.com/5502696/33214684-f4765f30-d0fa-11e7-86a1-43695c2d7d50.png)
![image](https://user-images.githubusercontent.com/5502696/33214697-fefd3988-d0fa-11e7-8302-ee7d2ae68075.png)
OR
![image](https://user-images.githubusercontent.com/5502696/33214958-ecfd7e86-d0fb-11e7-82e4-04da8e77b85a.png)
![image](https://user-images.githubusercontent.com/5502696/33214941-db9bcad0-d0fb-11e7-9f7c-58b697394175.png)

2.  When viewing the legend:
![image](https://user-images.githubusercontent.com/5502696/33214791-5af8afb0-d0fb-11e7-9a27-d12b7443aea0.png)
All of these legend items should look like this
![image](https://user-images.githubusercontent.com/5502696/33214834-825a9df2-d0fb-11e7-8a69-f794a8766e50.png)

3. When viewing the table:
![image](https://user-images.githubusercontent.com/5502696/33214885-a2f05854-d0fb-11e7-97f6-46f2df9d3b21.png)

I think this relates to the way the FGPV is making these calls, browser-side vs server-side rendering.

**Comment by james-rae** [comment]
Could you provide REST endpoint to the ArcGIS servers hosting these layers? e.g. for `Indigenous Place Names`, `Petroleum Administrative Areas`, `Wind Energy Potential`

**Comment by ppollock** [comment]
Unfortunately, all of these are currently only visible internal to NRCan.  There might be a way to put out small test versions that you could work with.  Or is there another way?

**Comment by james-rae** [comment]
As a start, maybe email me the `json` version of the service definitions for each layer? I might be able to crack some of the problems by examining what is defined there.

**Comment by james-rae** [comment]
Thanks for sending the endpoint definitions. Here's what I've gleaned from them.

## Maplex isn't included in highlight

Labelling is not currently supported by RAMP when it comes to highlighting.  The labelling definition is separated from the symbol (you can see the symbol highlighting on the map).
New issue to look into adding support for it https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2493

## Power Density doesn't identify

Service-wise, everything looks suitable for RAMP. One thing I notice in the screenshots is that the area clicked is not directly in the center of the dot.  This has always been a tricky area for dynamic layer identification when dealing with a point layer that has large symbols. The symbols take up lots of real estate, but the server-side identify is geometry based (matching against a point, not a large circle).

This [writeup](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/419#issuecomment-346882016) goes into more detail.

A few things to try:

* Try clicking directly in the middle of the circle. If this still doesn't return a result, then it may indicate a different issue.
* If your site is pre-canned (i.e. not getting layers from the Add button or a catelog reference / RCS key), you can add a property to the layer configuration called `tolerance`, which will adjust the buffer size (in pixels) for matching identify clicks (sample below).

```json
{
	"id": "somepowerplants",
	"name": "Power Plants",
	"layerType": "esriDynamic",
	"layerEntries": [
		{ "index": 17 },
		{ "index": 19 },
		{ "index": 21 }
	],
	"tolerance": 20,
	"url": "http://geoappext.nrcan.gc.ca/arcgis/rest/services/NACEI/energy_infrastructure_of_north_america_en/MapServer"
}
```

Otherwise I can't really tell much about what's happening without access to the layer.


## Solid Highlight & Symbology for Fancy Hatches

This is a known limitation with ArcGIS REST / Javascript API

E.g. here is what the ArcGIS Server returns as a description for one of those hatched polygons. Notice the `style` is indicating Solid.

```json
{
	"symbol": {
		"type": "esriSFS",
		"style": "esriSFSSolid",
		"color": [ 104, 104, 104, 255 ],
		"outline": {
			"type": "esriSLS",
			"style": "esriSLSSolid",
			"color": [ 104, 104, 104, 255 ],
			"width": 0.5
		}
	},
	"value": "Canada-Nova Scotia Offshore Petroleum Board",
	"label": "2. Canada-Nova Scotia Offshore Petroleum Board",
	"description": ""
}
```

Here is a [forum post](https://community.esri.com/thread/32433#comment-205322) that somewhat goes into the technical reasons why ESRI implemented things this way.

The hatching appears on the map because it is a dynamic layer. The image is drawn server-side, which is not restricted by the above technical limiations. If you were to add the layer as a Feature Layer, I would expect the polygons to be solid.

It's an unfortunate thing (as it looks terrible) but I don't have a solution for it.

**Comment by ppollock** [comment]
Sorry just realized that I put the wrong screen capture in as the second image for the Power Density scenario...
![image](https://user-images.githubusercontent.com/5502696/33274792-1c12e980-d35f-11e7-961b-c726cbd94964.png)

**Comment by james-rae** [comment]
James - Nov 28 (email)

> I’m still a bit stumped on the power density layer not highlighting... [ramblings removed]

Patricia - Dec 20 (email)

> I was able to recreate the problem behaviour and I figured out that this behaviour was happening because of a problem with the service I created and the underlying data. 

I think at this point, all the issues have either been corrected or identified as an ESRI limitation, and we have one new issue to look at adding text to the viewer's highlighting engine ( https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2493 )

Will close in a day or so if there are no objections.
