### ISSUE TITLE
Wrong extent when switching languages

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2522]
When switching languages, you are returned to the wrong extent.

This behavior can be observed in the GCGeo implementation of the viewer: http://gcgeo.gc.ca/viz/index-en.html

Redmine issue: http://redmine.gcgeo.gc.ca/redmine/issues/11402

**Comment by barryytm** [comment]
After some extensive testings on Chrome, IE, and Firefox.  It seemed only Chrome was having such problem.  When cache was disabled in Chrome, extent matched what was on the bookmark as intended.  Can anyone try it on their machines to confirm what I said it true?

**Comment by spencerwahl** [comment]
:point_up: same on my machine

**Comment by barryytm** [comment]
Another thing I forgot to mentioned was that I have also done testings on [v2.0.0](http://fgpv.cloudapp.net/demo/v2.0.0/dev/samples/index-fgp-en.html) and [v2.2.0](http://fgpv.cloudapp.net/demo/v2.2.0/dev/samples/index-fgp-en.html) with another template and it didn't seem to have the issue.  Perhaps the issue was caused by the template?

**Comment by james-rae** [comment]
Given this template has back to cart, and I explained that back to cart uses the browser cache, that is a pretty safe assumption.
