### ISSUE TITLE
No Data - Using Data Exclusion

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2531]
When a service is created using either Quantities or Charts in ArcMap there is an option to create an exclusion or No Data value.  If this exclusion option is employed:

- The No Data value is not visible in the legend:
![image](https://user-images.githubusercontent.com/5502696/34167467-daeee582-e4af-11e7-82ad-64a43bc2a44d.png) where as it looks like this in the ArcGIS server legend:
![image](https://user-images.githubusercontent.com/5502696/34167515-fb236af8-e4af-11e7-94e9-3e4458f2f18b.png)

- If the service is added as Feature Layer then none of the No Data records are visible in the map:
![image](https://user-images.githubusercontent.com/5502696/34167621-3bec25a2-e4b0-11e7-9564-036f86481e63.png) where as if it is added as a Dynamic Layer then the No Data records are visible:
![image](https://user-images.githubusercontent.com/5502696/34167651-5fece3f6-e4b0-11e7-9549-4667aefad30b.png)

- The No Data value is also not visible in the legend:
![image](https://user-images.githubusercontent.com/5502696/34167721-875b2830-e4b0-11e7-9dc2-72c356fb6b88.png)

_

**Comment by james-rae** [comment]
I've derived what I can without having access to the actual services.

It appears the internals of the MapServer are comfortable in dealing with the concept of No Data, but the REST and Javascript APIs are not.

## No Value not showing in legend

The server Legend endpoint (generated on the server) will show the No Value entry.  But if you look at the layer's exposed renderer:

```json
 "drawingInfo": {
  "renderer": {
   "type": "classBreaks",
   "field": "MED_H_INCOME",
   "classificationMethod": "esriClassifyManual",
   "minValue": 13168,
   "classBreakInfos": [
    {
     "symbol": {...},
     "classMaxValue": 50000,
     "label": "$13,168.00 - $50,000.00",
     "description": ""
    },
    {
     "symbol": {...},
     "classMaxValue": 65000,
     "label": "$50,001.00 - $65,000.00",
     "description": ""
    },
    {
     "symbol": {...},
     "classMaxValue": 70336,
     "label": "$65,001.00- $70,336.00*  *national median",
     "description": ""
    },
    {
     "symbol": {...},
     "classMaxValue": 100000,
     "label": "$70,337.01 - $100,000.00",
     "description": ""
    },
    {
     "symbol": {...},
     "classMaxValue": 195570,
     "label": "$100,001.00 - $195,570.00",
     "description": ""
    }
   ]
  },
  "transparency": 0,
  "labelingInfo": null
 }
```

you can see it has no definition for anything outside of the numeric ranges. It doesn't even have a `defaultSymbol` property.

For feature-based layers, RAMP generates legends and icons from the Renderer, not the server Legend endpoint. We do this to support things hosted in FeatureServer, which does not have a Legend endpoint.

Current pseudocode:

```text
Load Layer
Get Renderer
Generate Symbol Icons from Renderer
Extract Legend from Renderer
```

To make things work in this situation, we'd have to attempt something like

```text
Load Layer
Get Renderer
Generate Symbol Icons from Renderer
Extract Legend from Renderer
If MapServer
   Load Server Legend
   Crossreference Server Legend to Renderer Legend
   If Extra Entries in Server Legend
      Add to Client Legend
	  Add to Client Renderer / Symbol Icons
	    (to support grid / tooltip / detail icons)
        (need to add extra logic to symbol lookup for No Value case)
Resolve Legend Promise
```

## No Value features not showing on map for Feature Layer

Similar to the above situation. Javascript API has no idea how to draw the No Value shapes as the renderer provided by ArcServer REST has no specification for it.

Dynamic Layer draws it because the image is prepared on the server.

For the graphs, it's similar as Javascript API currently has no support for Graph Renderers.  At a glance, API 4.0 doesn't support this either.

No real solution for this unless we look into hacking the ESRI API (careful now!).

## Next Steps

Determine if enhanced legend support will be implemented and if so, prioritize.

Review our viewer documentation and add notes about what type of renderers are supported in what capacity if it's missing.

**Comment by mweech** [comment]
No supported by the ArcGIS API = Not fixable.
