### ISSUE TITLE
Change North Pole Snowman symbol

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpv-vpgf#2541]
Unfortunately, the client services group have been receiving emails about people complaining about the snowman symbol for the north pole. Apparently, some people are offended by it.

Can we change the symbol or make it configurable?

Thanks,

**Comment by AleksueiR** [comment]
This icon is not configurable, unfortunatelly, but we can certainly change it and/or make it configurable.

Would you be able to reach out to people requesting this and find out what symbol would they rather see instead? There needs to be a default symbol, even if it's made configurable in the config file.

**Comment by barryytm** [comment]
Since the snowman shows where the north pole is at.  I am thinking `northPole` with would probably be a good name for the property?  `northPole` will be a URL(string) that points to a SVG image endpoint.  The viewer will ignore `northPole` and use the default cached SVG if it is not provided.

I believe `northPole` should be under (`map` -> `components` -> `northArrow`) to indicate that it is part of the `northArrow` component.   Any other suggestions regarding to the location?

Currently `enabled` under `northArrow` controls both `northArrow` and snowman because the viewer is treating them as the same component.  Should we create it's separate `enabled` for `northPole`?

**Comment by james-rae** [comment]
Good initial ideas.
My thoughts are either have two separate components: `northArrow` & `northPole` (or `northPoleMarker`), or combine into a bigger structure, e.g.
```json
northIndicator : {
   northArrow: {
      svgString: "asdfsd",
      enabled: true
   },
   northPole: {
      svgString: "tyuio",
      enabled: true
   }
}
```

but am open to other ideas

**Comment by barryytm** [comment]
Another question came to my mind after reading James' snippet.  Do we want property to be an URL or a SVG string or both?  Since we are making it configurable, we can also support other image types too.

**Comment by AleksueiR** [comment]
Let's keep it consistent with the symbology stack images approach: they accept absolute image urls and base64 dataURL images (can be png, jpeg, svg, almost anything, I think).

**Comment by jolevesq** [comment]
We think @james-rae idea of having it configurable from the config file is a good one. This way we will not have to bother about it anymore.

@mweech do you think this can be part of your next release?

**Comment by james-rae** [comment]
After discussion, will go with the following config schema.

```text
mapComponents: {
   northArrow: {
      arrowIcon: "lxBYStTJSe3THw....",
      poleIcon: "t9qKqCqWl5Tw....",
      enabled: true
   }
}
```

as mentioned above, the `Icon` fields should support urls and base64 data.

**Comment by YaroRoodzit** [comment]
Request resolved. SnowMan has been replaced ( unfortunately ) with a flag. Bye - Bye, SnowMan!
