### ISSUE TITLE
Share Link not loading any layers after switching FGP viewer to French

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2589]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-semi-weekly02/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways,ZoomScale

- Go to left side menu and switch language to French
- Click "PARTAGER" to generate a Share Link
- Paste the link to a new tab
No layer is loaded, meanwhile the viewer changed back to English menu.
![image](https://user-images.githubusercontent.com/18723160/36852712-6e4d6ad4-1d3a-11e8-8491-a323830268c1.png)
![image](https://user-images.githubusercontent.com/18723160/36852808-c0bf72b2-1d3a-11e8-854a-2b9f712397d9.png)

**Comment by barryytm** [comment]
**Findings**
The problem is caused by loading  bookmarked French rcs layers in an English host page and vice versa.  One thing to point out is when decoding an RCS layer to [get its key](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-build-05/src/app/core/reload.service.js#L153), RAMP would not have known whether the rcs layer is English or French as they are [loaded](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-build-05/src/app/core/config.service.js#L148) based on the language in the config object which ultimately gotten from the host page.   Therefore, English rcs layers corresponding to the keys extracted from the bookmark should load but in our case, they did not.

**What I've tried**
Loading bookmarked rcs layers in the host page with the same language worked so we can eliminate the possibility of RAMP failing to load bookmarked rcs layers.

I've also tried changing the [language](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-build-05/src/app/core/config.service.js#L139) to a `'fr'` when loading rcs layers.  What that means is RAMP will always load rcs layers in French and it did indeed work for all bookmarked French rcs layers.  This requires more investigations as it should not have mattered what the language is.

**Possible Explanation**
There is some kind of logic checking the language in the extracted rcs layers from bookmarks to see if they match the host page's language.  It is likely to be the root of this issue.  It is probable to be somewhere after [the rcs layers being processed](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-build-05/src/app/core/config.service.js#L128).

**Things to do**

- Find where the language of RCS layers are being validated with the config object/host page
- Try to improve that logic to make RCS layers work in a host page with a different language

**Notes**
A bookmark that captures the language of the bookmarked page (#1277) might be implemented in the future.  Therefore we might be able to overwrite the language of the host page.

**Comment by mweech** [comment]
The issue is that when the user switches language using the left menu options they are not switching the host page language.  Instead they have only switching the viewer language.  So when a bookmark is generated, the english host page is still used and subsequent loading of the bookmark using the default language of the page, not the state of the viewer at time of bookmark.

This is a specific edge case and while tracking the language of RAMP itself in the bookmark seems like a fix, a more appropriate change would be to eliminate the side menu based language changing or allow it to trigger the overall page language switching as well.

Marking as "wont fix"
