### ISSUE TITLE
API-07: HoverPoint extends Point, and various improvements to Geometry/Point

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2593]
#### HoverPoint extends Point
constructor contains a third parameter like [Annotation](http://fgpv-vpgf.github.io/fgpv-vpgf/api/classes/_index_d_.rv.geometry.annotation.html) which is either a string of either pure text, or a string containing valid HTML. Probably want to `jQuery.html(it)`. 
- When you hover over a `HoverPoint` it opens a hover tip that remains in a fixed position above-center to the point. It closes when the icon looses focus. 
- Clicking on it has no effect (i.e. identify still happens, won't see it in the toc/identify panel. 
- A fourth (optional) parameter is a `keepOpen` boolean property (default is `false`) which keeps the hovertip open.

#### Create default simpleLayer on the map
All map instances will have a simpleLayer created for them to make it easier to add points or w/e to the map without needing to create a layer. This layer won't appear in the map instances `LayerGroup`, you would simply make a call to get the layer, like `let theSimpleLayer = RZ.mapInstances[0].simpleLayer;`.

#### Other changes
- Provide support for inline svg images for the `Point` class.
- `layerAdded` should emit `Promise<layer[]>` instead of `void` in all cases.

**Comment by AleksueiR** [comment]
Does the hovertip close when you zoom the map?

**Comment by JahidAhmed** [comment]
Just wanted to outline a few of the important changes made to the description of this issue after discussing it in meetings and some R&D:

#### HoverPoint extends Point
- hoverpoint does not extent anything anymore; it is a standalone class that can be added to any supported geometry type (`apiGeometry.addHoverpoint(apiHoverpoint)`)
- it is instantiated with 2 required and 1 optional parameter. the optional parameter is an object containing a list of the available controls to the user outlined below (all of them being optional): 
     *     keepOpen:        true or false. default is false.
     *     position:        'top', 'bottom', 'left' or 'right'. default is 'top'. (if followCursor is true, position value will be ignored.)
     *     xOffset:         any number. default is 0.
     *     yOffset:         any number. default is 0.
     *     followCursor:    true or false. default is false. (if keepOpen is true, followCursor value will be ignored.)
- if the map is zoomed or a graphic is offscreen, the hoverpoint will be closed (however if graphic offscreen and it comes back on screen, hoverpoint will reopen if property `keepOpen` was true)

#### Create default simpleLayer on the map
- default `SimpleLayer` created on the api mapInstance; so `RZ.mapInstances[0].simpleLayer` for example
- used an empty string as an id to avoid any duplication in id if a `SimpleLayer` was created by a user. for example if the id used here was `sl`, a user creating a `SimpleLayer` with the id `sl` would result in problems

#### Other changes
- API Geometry `Point` can be created using an SVG path as the icon instead of just URLs. eg:
```js
var pointE = new RZ.GEO.Point(4, 'M24.0,2.199C11.9595,2.199,2.199,11.9595,2.199,24.0c0.0,12.0405,9.7605,21.801,21.801,21.801c12.0405,0.0,21.801-9.7605,21.801-21.801C45.801,11.9595,36.0405,2.199,24.0,2.199zM31.0935,11.0625c1.401,0.0,2.532,2.2245,2.532,4.968S32.4915,21.0,31.0935,21.0c-1.398,0.0-2.532-2.2245-2.532-4.968S29.697,11.0625,31.0935,11.0625zM16.656,11.0625c1.398,0.0,2.532,2.2245,2.532,4.968S18.0555,21.0,16.656,21.0s-2.532-2.2245-2.532-4.968S15.258,11.0625,16.656,11.0625zM24.0315,39.0c-4.3095,0.0-8.3445-2.6355-11.8185-7.2165c3.5955,2.346,7.5315,3.654,11.661,3.654c4.3845,0.0,8.5515-1.47,12.3225-4.101C32.649,36.198,28.485,39.0,24.0315,39.0z', [79, 32]);

```

- `layerAdded` emits a Promise resolving to `Array<BaseLayer>` instead of `void` in all cases. 
- if a `ConfigLayer` is reloaded, a new `ConfigLayer` will not be created, only the required layer settings will be updated with new values (such as layerRecord, geoApi proxy, etc.) to allow for any reference to an already created layer to remain up-to-date and also to keep any observables
