### ISSUE TITLE
[Broken Sample #11] Layer is not rendered when opacity is changed

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2594]
The initial opacity for the layer is set to 0.

__Expected:__ the layer should be rendered when opacity is set to a higher value.

__Actual:__ the layer remains invisible after changing the opacity value.

Sample: `11. Multiple layers with opacity disabled initially`
http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html

**Comment by JahidAhmed** [comment]
The issue here is the discrepancy between top level opacity and child transparency for dynamic layers. When we specify our opacity in the config, that's for the top-level and whenever we switch our opacity through the slider (or now, the API), the values being changed are the [transparency](https://developers.arcgis.com/javascript/3/jsapi/layerdrawingoptions-amd.html#transparency) values for the children passed in [here](https://developers.arcgis.com/javascript/3/jsapi/arcgisdynamicmapservicelayer-amd.html#setlayerdrawingoptions). So essentially the value we are changing it to is a fraction of the original opacity set. 

In this case, the opacity is 0 and changing the slider to any value is a fraction of the original opacity which will always be 0.

Another, possibly clearer example is if we specified the opacity to be 0.2 in the config and then set the slider to 100%. The actual opacity is 0.2 because its 100% of 0.2. And if we were to make it 50%, the opacity would be 0.1 (50% of 0.2).

So that 0.2 opacity, with the bar at 100% would be equivalent to using the default opacity (1) in the config and setting the bar to 20%.

Some discussion is required here on how to handle this situation and what the expected behaviour should be in these cases.

We could move forward with the actual behaviour we see currently, but document it in the help file to make it clearer (along with possibly some indication under the opacity slider) or we could make changes based on what was initially outlined as the expected behaviour in this issue.

**Comment by barryytm** [comment]
**Demo**
I've made a demo with a small fix.  I haven't changed much of its logic but added this [line](https://github.com/barryytm/fgpv-vpgf/blob/2.3.0-2594/src/app/core/config.class.js#L561).

Sample 11
http://fgpv.cloudapp.net/demo/users/barryytm/2.3.0-2594/dev/samples/index-samples.html 

**Things to consider**
One thing to point out.  If there exists a child opacity value of a dynamic layer that is not the same as it's siblings', the dynamic layer's opacity [value will be set to 0.5](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v2.3.0-build-06/src/app/geo/legend-block.class.js#L977).  We should think about whether we want keep it as it is, or have something to indicate the opacity of the dynamic layer is not accurate, or do it in some other ways.

Please play with the demo as much as you like.  All feedbacks/thoughts/suggestions are welcome.
