### ISSUE TITLE
Grid advertises that 4 records are on display, when there are only 3 in view. 

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#2602]
![image](https://user-images.githubusercontent.com/5294596/37653783-5f913332-2c16-11e8-86ce-6432c172d3d8.png)

Incidentally, if you scroll to the bottom of the grid, the values are now correct:
![image](https://user-images.githubusercontent.com/5294596/37653849-a421707a-2c16-11e8-8c51-773fe557cc95.png)

**Comment by JahidAhmed** [comment]
This seems to be an issue with how datatables render and display information. In this case, it seems that the table does not take into account the space taken up by the horizontal scrollbar (and possibly also the content under it) which is why it seems to show an incorrect number. 

One way to confirm this is by opening the settings panel and hiding all fields for the layer which will then display the correct value since there is no scrollbar.

**Comment by mweech** [comment]
DataTables is technically working as expected.
