### ISSUE TITLE
Not able to load renderer and table for pie chart layer

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2607]
When we try to load a pie chart layer, the table doesn't open and the symbology is not apply.

https://geoappext.nrcan.gc.ca/arcgis/rest/services/Energy/clean_energy_test_bio_ccs_small/MapServer/3

**Comment by james-rae** [comment]
The layer doesn't expose any renderer or drawing information (see [server json](https://geoappext.nrcan.gc.ca/arcgis/rest/services/Energy/clean_energy_test_bio_ccs_small/MapServer/3?f=pjson)). 
We've seen this with other complex renderers...they can be drawn on the server via dynamic, but the JS API cannot handle them so REST API doesn't expose the details (see https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2492 )

Short term solution, I can think of looking to add some extra checks to identify layers that are missing symbology / renderers, and generate a very simple placeholder renderer (e.g. small black circle).  Ideally, this prevents other parts of the code from breaking, such as the data table as was mentioned.

I'm under the impression that these kind of symbolized layers will never draw as feature layers; only via dynamic layers.  

A longer term solution is similar to the "small black circle" approach, but we interrogate the [server legend](https://geoappext.nrcan.gc.ca/arcgis/rest/services/Energy/clean_energy_test_bio_ccs_small/MapServer/legend), steal it's graphic, and use that instead of default circle

**Comment by mweech** [comment]
Not supported by Esri JS API feature set.
