### ISSUE TITLE
Map Export cannot finish loading after adding certain Scale Dependency layer

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#2647]
Tested build: http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-fgp-en.html?keys=JOSM,EcoAction,CESI_Other,NPRI_CO,Railways
Test data: http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/CESI/CESI_AirEmissions_SOx/MapServer
(provided by Dan & James, thanks!)

-  Import above test data to the Viewer
-  In step 3 (configure layer) select all layers, this will add SOx layer with four sub-layers
-  Export the map
It seems the export map is loading but never finished.

![image](https://user-images.githubusercontent.com/18723160/38752896-b262f01a-3f2a-11e8-8c4d-f563ebdbae9f.png)

**Comment by james-rae** [comment]
The old CESI "four-scale-layer" services have been removed from production after the major CESI update.

We provided some of these legacy layers on dev server, since they are useful for testing scale-dependency tests.  However, the print service cannot see the dev server so it causes a problem.

Will look into getting a scale-based layer on a different server that is useful

**Comment by james-rae** [comment]
Here is a scale dependent layer.  It's large so please use as `Dynamic Layer`, not `Feature Layer`.  Let me know if it still fails
http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/Provinces/MapServer

**Comment by IsabellaPan** [comment]
Hi James, the above scale dependent layer works on map export. Tested with build v2.3.0-b1.
Thanks for providing the test data.
