### ISSUE TITLE
Layers disappear after manual reload 

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2657]
Tested build:http://fgpv.cloudapp.net/demo/v2.3.0-build-05/dev/samples/index-samples.html
Sample Map: 08.Layer with single entry collapsed set

- Open Settings of any layer and click reload.
Two of the three layers disappeared.

**Comment by AleksueiR** [comment]
Yeah, this is a bug.

The 08 config add the same layer three times to the structured legend which might look like a nonsense use case:
```json
"legend": {
      "type": "structured",
      "root": {
        "name": "root",
        "children": [
          {
            "layerId": "somepowerplants"
          },
          {
            "layerId": "somepowerplants"
          },
          {
            "layerId": "somepowerplants"
          }
        ]
      }
    }
```

However, you the layer referenced is a Dynamic one, it's possible to only include a single subentry from that layer with each of the legend entries:
```json
"legend": {
      "type": "structured",
      "root": {
        "name": "root",
        "children": [
          {
            "layerId": "somepowerplants",
            "entryIndex": 21
          },
          {
            "layerId": "somepowerplants",
            "entryIndex": 17
          },
          {
            "layerId": "somepowerplants",
            "entryIndex": 19
          }
        ]
      }
    },
```
This use case makes sense, but the reloading of any one of these entries will remove the other two, which is not what is expected.

#### Expected Behaviour
All the legend entries referencing the same layer need to be restored after the layer is reloaded.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Issue resolved.
