### ISSUE TITLE
GeoJSON Import File

### ISSUE THREAD

**Issue by ppollock** [fgpv-vpgf/fgpv-vpgf#2698]
Good morning,

In FGPV 2.3.0 [78a5dbabf]

When importing some geojson files, we get the following error:
![image](https://user-images.githubusercontent.com/5502696/39603393-34af81d4-4ef6-11e8-81ca-4e3f41d93fb4.png)
And in the console:
![image](https://user-images.githubusercontent.com/5502696/39603371-241a2702-4ef6-11e8-9767-caeea4d32eb4.png)

But if we add the following to the geojson file:
{
  "type": "FeatureCollection",
  "features": [
…
]
}

Then it works.
Some of the sources for these geoJSON files are the following APIs:
http://geogratis.gc.ca/services/geoname/en/geonames.json?q=iqaluit
http://geogratis.gc.ca/services/delimitation/en/drainage-gen/05gc000.json
http://www.earthquakescanada.nrcan.gc.ca/api/earthquakes/latest/7d.json

The drainage delimitation geojson files work well in its original unedited form in QGIS.

They all fail in geojsonlint so I am also going to contact each of the API owners to ask them if they can modify their outputs.  In the meantime I am wondering if there is anyway to expand the acceptance test in the viewer so that a few more of these geojson files will load in the viewer?

Thanks,
Patricia

**Comment by james-rae** [comment]
All three examples appear to have different formats. 

Initial thoughts:

* It would be good, if possible, to have identified what schema these are in. Are these official/well known formats?
* If well known, it is possible to make a translation routine to get from those formats to proper GeoJSON (this is what we do with CSV & Shapefile).
* Added complexity is due to all the types having the extension `.json`. We will need to derive a way to inspect the content and determine what of the (possibly) four different schemas the file is in and take the appropriate steps.

I'll be interested to hear if it was possible / easy to adjust the source API's to spit out proper GeoJSON. If it's easy, we may favour being elitist in our JSON for the short term.

**Comment by ppollock** [comment]
I agree that the best way is likely to change the outputs from these APIs.  I will post updates to this issue as I get them from the API owners.

Cheers!
