### ISSUE TITLE
Make geosearch an intention which consumes the geoSearch library

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#2712]
Convert into an intention format which uses the https://github.com/RAMP-PCAR/geosearch library for fetching results. The UI should remain unchanged.

![untitled](https://user-images.githubusercontent.com/10187181/39937468-d5e7e046-551d-11e8-8482-52e275a3e005.png)

**Comment by barryytm** [comment]
## Background
I spent some time reading the [geoseach doc](https://ramp-pcar.github.io/geosearch/#/config) and [index.ts](https://github.com/RAMP-PCAR/geosearch/blob/master/src/index.ts#L31).  What I've observed was that there isn't an option for configuring the provinces/types service endpoints.   Further more, it seems our geosearch intention is getting provinces and types from some [json files](https://github.com/RAMP-PCAR/geosearch/tree/master/data) instead of from service endpoints.

There was an #1855 that addressed the problem when the service endpoints were not provided.  We have opted for option 2 as a temporary fix.  Therefore it is required to provide endpoints in the config file as in the current state. 

## Questions
Here are a few questions I hope we can discuss or maybe someone could answer.
1. Are we still planning to support the geosearch provinces/types endpoints in the intention?
2. If we are only using json files.  Do we still enforce users to put down some service endpoints?
3. Will we also provide a way for users to add their own provinces/types json files?
4. How would we handle the provided service endpoints from config file if a geosearch extension was used instead of the intention?

There might be some other problems that I didn't think of.  Please do share any questions/problems/concerns.

**Comment by james-rae** [comment]
Will let Miles give the official response, but random idea:

* The intention / extension has a `load` component.
* The intention `load` uses the existing logic: gets URLs from config file, uses json files you noted.
* Extensions must implement their own `load`. So they can get data from files / hardcoded in javascript / service urls.

This could be extrapolated to the `search` action as well, so an extension could execute a totally different kind of search. The results would be massaged into a standard format that our UI control can parse and display.

We might also consider making the Province/Type support optional, with the intention having them on. If off, the UI elements would be hidden.

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Search working properly.
