### ISSUE TITLE
Abstracting loader service/file duplicated code after WFS functionality added

### ISSUE THREAD

**Issue by JahidAhmed** [fgpv-vpgf/fgpv-vpgf#2726]
WFS POC: http://fgpv.cloudapp.net/demo/users/JahidAhmed/wfsPOC/dev/samples/index-samples.html
WFS Layer: https://www.ldproxy.nrw.de/rest/services/kataster/collections/flurstueck/items
Other relevant links:
https://github.com/opengeospatial/WFS_FES/blob/master/implementations.md
https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/openapi.yaml
https://www.ldproxy.nrw.de/rest/services/kataster/
https://app.swaggerhub.com/apis/cholmesgeo/WFS3/M1

A proof of concept allowing WFS layers to be imported as a service is linked above (zoom to layer boundary to see layer). 
-- --
There are a few limitations and required modifications to point out: (feel free to modify any of the outlined points)
- WFS layers are imported as services, but they are handled similar to how `GeoJSON` files are imported.
  - results in lots of duplicated code between `loader-service` and `loader-file` 
  - need to include if-statements to handle WFS vs. other services
  - file importer colorpicker used for WFS services
- WFS layers can contain multiple collections in the dataset
  - when we import WFS layers, we currently need to import an individual feature collection as opposed to multiple (for example, WFS layer linked above vs. simply https://www.ldproxy.nrw.de/rest/services/kataster and then picking desired collections)

**Comment by james-rae** [comment]
Some other issues that might overlap

FeatureServer as single layer -- same type of situation as WFS exposing multiple collections
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/580

Load file from config -- combined with this current issue, there is probably an opportunity to refactor the file layer code to support loading from outside the wizard, and to organize routines to allow sharing instead of duplicating.
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2700

**Comment by JahidAhmed** [comment]
Filtering capabilities on the map are also lost since they aren't supported for file layers: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2202

**Comment by james-rae** [comment]
Parent issue #400
