### ISSUE TITLE
Handling large WFS Datasets

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#2750]
Our initial implementation of WFS ( #2748 ) treats the dataset in the same way we treat a file or a snapshot feature layer: all features are loaded up-front.  This can become problematic with larger datasets; the site may stall or freeze as the layer loads, and IE may have difficulty rendering large sets of geometry (there will be no simplification of complex lines or polygons).

Look into the following areas for potential improvements:

- [x] See if the WFS 3.0 spec has any endpoints for streaming / paging results
- [ ] See if ESRI API 4.x WFS class supports a similar feature management approach similar to Feature Layer On-Demand mode (i.e. only download whats in view, simplify geometries)
- [ ] See if a web-worker could prevent freezing when loading large data ( #964 )
- [ ] Look at feasibility of writing our own implementation of something similar to Feature Layer On-Demand mode (it's probably very terrible)

**Comment by mweech** [comment]
WFS 3 supports pagination by default as a result of it following the Open API specifications.  Default behavior is to return a subset of records and to provide back/next endpoints to continue to page through the results.  

Note the response: http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items

Responses to WFS queries have a default "limit" set by the individual service.  In order to get all station records, you can do the following query: http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items?limit=10000

Since 10000 is the max value for the limit argument, we can get all records returned.  However, if the service has greater than 10000, then paging appears to be required.

**Comment by james-rae** [comment]
Work done in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2748 has implemented a paged initial load. This still means the entire service must be loaded up-front, but does it in blocks that reduce the probability of a time-out, and allow the viewer to give feedback as the layer loads.

This issue remains open until the other research items can be addressed.
