### ISSUE TITLE
List the WMS layer "NAME" not the "TITLE" when adding through the add-layer-wizard

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2828]
> suggestion: on Add Service, when adding a WMS, we should list the WMS layer "NAME" not the "TITLE"
the "NAME" are intended to be unique identifiers, whereas the "TITLE" is something that is used as part of the layer hierarchy to label sub layers
so for instance, CMIP5 data has MANY layers with the same name because they are all for the 50th percentile sub layer of a time period/var
@mweech 

:point_up: [July 5, 2018 3:36 PM](https://gitter.im/fgpv-vpgf?at=5b3e73467e23133ecb34f54a)

**Comment by ShrutiVellanki** [comment]
`WMSLayerEntryNodes` are created from objects that look like these (we are currently using `desc` for the wizard drop down menu and the `name` for the entry that shows up in the legend):

![capture](https://user-images.githubusercontent.com/25359812/43913831-24105670-9bd4-11e8-94bc-bc9f2d78899b.PNG)

I've created a couple of demos, let me know which combination would work best to resolve this issue! (or any other one that I may not have thought of).

- [v1](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v1/dev/samples/index-samples.html): `name` is used for both legend and drop down
- [v2](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v2/dev/samples/index-samples.html): `desc` is used for both legend and drop down
- [v3](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v3/dev/samples/index-samples.html): `desc` and `index` used for drop down (in case of duplicate layers like in [this service](http://maps.geogratis.gc.ca/wms/landcover_en?service=wms&version=1.3.0&request=GetCapabilities) with three `Land Cover Circa 2000`, though note that `index` might be useless since its just the entry number...)
- [v4](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v4/dev/samples/index-samples.html): `name` and `index` used for drop down (in case of duplicate layers)

**Comment by mweech** [comment]
> * [v1](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v1/dev/samples/index-samples.html): `name` is used for both legend and drop down
> * [v2](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v2/dev/samples/index-samples.html): `desc` is used for both legend and drop down
> * [v3](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v3/dev/samples/index-samples.html): `desc` and `index` used for drop down (in case of duplicate layers like in [this service](http://maps.geogratis.gc.ca/wms/landcover_en?service=wms&version=1.3.0&request=GetCapabilities) with three `Land Cover Circa 2000`, though note that `index` might be useless since its just the entry number...)
> * [v4](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wms-v4/dev/samples/index-samples.html): `name` and `index` used for drop down (in case of duplicate layers)

Are these hanging around anywhere?
