### ISSUE TITLE
Filter WMS

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#2839]
We would like to have the ability to filter WMS like we do it for ESRI layers with definition query. [ArcGIS server](http://enterprise.arcgis.com/en/server/latest/publish-services/windows/filtering-features-using-the-layerdefs-parameter-in-wms-requests.htm) supports it in version 10.6. WMS and WFS layer for ESRI Javascript Api let you add custom parameter to a WMS request that can fulfill this need. 

.../services/MyMapService/MapServer/WmsServer?VERSION=1.3.0&REQUEST=GetMap&CRS=CRS:84&BBOX=-180,-90,180,83.604158999999996&WIDTH=660&HEIGHT=318&LAYERS=country&STYLES=default&EXCEPTIONS=xml&FORMAT=image/png&BGCOLOR=0xFEFFFF&TRANSPARENT=TRUE&**layerDefs={"country":"POP_CNTRY>100000000"}**

**Comment by mweech** [comment]
I think there is a strong argument against a vendor specific function for WMS specifically when that vendor is Esri.  The utility of increasing support for MapServer based WMS's is debatable.

There are also too many commonly used WMS features that are required before we look to support such an edge case (many of these due to Esri's lack of follow through on support for the WMS as a data source).

**Comment by mweech** [comment]
Closing as this is not something we will invest in for core development priorities at this time. WMS query is considered vendor specific, and we would be remiss to only support ArcGIS WMS queries given it might be more appropriate to just use them as Dynamics initially since this is a Esri JavaScript API based viewer.  This can be pursued independently via PR if desired, however coverage for an OGC server would be expected to occur at the same time.
