### ISSUE TITLE
Opacity doesn't work properly for WFS layer.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2863]
Tested build: http://fgpv.cloudapp.net/demo/v2.5.0-b1/dev/samples/index-samples.html
Sample #68.
When you play with Opacity or Show Layer for "Hydrometric Stations - Start with 6000th index" layer just change colour.
No problem for other WFS layers.

**Comment by JahidAhmed** [comment]
I believe it appears to change colour because it is overlaying on another WFS layer with the same points, so it looks like the colour is changing and not opacity (since the underlying green points are stronger) 

If the visibility for the other layers were all false and the opacity for this layer was changed, it works as expected.

**Comment by YaroRoodzit** [comment]
@JahidAhmed: Highly likely. Can this layer be replaced with another to avoid confusion?

**Comment by bkutty** [comment]
This layer works as expected.
