### ISSUE TITLE
Failure to load WFS resources using wizard

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#2871]
When trying to import a WFS resource using the wizard it fails with 
```Failed to load resource: the server responded with a status of 404 (Not Found)```

Attempted with: 
- http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items?startindex=6000
- http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items
- https://www.ldproxy.nrw.de/rest/services/kataster/collections/flurstueck/items

**Comment by ShrutiVellanki** [comment]
Note resource loads with this:
http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items?startindex=6000 
using the latest [build](http://fgpv.cloudapp.net/demo/v2.5.0-b1/dev/samples/index-samples.html).  (Though there are some other errors in the console). Errors present for other two links.

**Comment by ShrutiVellanki** [comment]
Looks like last link is outdated. Making [these changes](https://github.com/fgpv-vpgf/fgpv-vpgf/commit/d1e57a14b744ca88cae4ac2e0e41769c19679330) (which I stole from build `v2.5.0-b1` where it also works) makes it work with the first two links. I don't know if you want me to PR it though because it might have been deleted for a reason?

[Demo](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/wfs-wizard/dev/samples/index-fgp-en.html)

**Note:** it sometimes says `Uncaught SyntaxError: Unexpected token :` in the console in which case you need to try loading the link again/refreshing the page. This was an issue for `v2.5.0-b1` also

**Comment by YaroRoodzit** [comment]
Tested with build v2.5.0-b2. Issue resolved.
