### ISSUE TITLE
Export image is broken when in corsEverywhere mode

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#2876]
Export image requires a proxy, corsEverywhere requires that there is no proxy.

We need to figure out a way to get them to play nice together.

Theres been one (probably very bad idea) thrown around to temporarily set the proxy while the export image dialog is open and then remove it when the image comes back or the dialog is closed.

**Comment by milesap** [comment]
Testing with `index-samples.html - 73. CORS Everywhere` exports the map as expected when the `export` property is updated in the config to:

```js
"export": {
      "title": {
        "value": "Title"
      },
      "map": {},
      "mapElements": {},
      "legend":{},
      "footnote": {
        "value": "anything..."
      }
    },
```
`map` and `mapElements` are missing from the `export` config property. Are there other services / configs I should be testing?

**Comment by milesap** [comment]
CCCS export image seems to be working for WFS but not WMS. Exporting WFS in ramp seems ok http://fgpv.cloudapp.net/demo/develop/prod/samples/index-samples.html. Will continue poking around

**Comment by james-rae** [comment]
Ahhhh it could be because our WMS services exist behind the firewall.  We are using a print server on Azure, so it cannot see the WMS services to get an image from them.

**Comment by james-rae** [comment]
CAPA is on a public server, if we can test that for export it should provide some decent answers.

**Comment by james-rae** [comment]
Ran the export directly on the Print Server.  The culprit is our Province overlay hosted on our cloud.  Likely the self-signed certificate.  

If you run CAPA with province & cities set to invisible, it will export.

I believe there is a task to migrate our cloud layers to our own servers, so this should resolve itself in time. 
The layers behind the firewalls will eventually get published on the public servers.
