### ISSUE TITLE
Symbology stack is mangled

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2935]
#### Version `2.4`.

- user-add `http://maps.geogratis.gc.ca/wms/railway_en`
- select sublayers
  - `Marker Post`
  - `Railway Subdivision Name`
- open the symbology stack
- see the mess:
![](https://i.imgur.com/RmLD3E5.png)

Images are overlapping each other and the legend entry and the `marker post` item is not wide enough to accommodate the width of the label.

Adding `Railway Ferry` and `Maker post` sublayers works better, but the second item is still not wide enough to show the full label.
![](https://i.imgur.com/T9ZaPUX.png)

#### Version `2.3`.
Also broken, but a bit less and at least the items are not overlapping:
![](https://i.imgur.com/DIk7yoh.png)

### Excpected
This should work as in `2.2`:
![](https://i.imgur.com/E3HkQrj.png)

### Acceptance Criteria:
- [ ] a symbology stack for a WMS layer renders that same way as it is rendered in version `2.2`; see screenshot above.

**Comment by JahidAhmed** [comment]
I attempted to fix the problem outlined in the comment above (and thought it was complete) but then noticed that there is weird behaviour with multiple layers; I tested Geomet and Railways. It turns out that the initial fix is still not working for some sublayers (instead of there being extra space below, its the opposite and there's not enough space still). So in the end, there was always 1 or 2 layers that didn't have enough space and 1 or 2 that had too much space. 

Note: the labels are different when importing through the wizard as compared to when loading thruogh the config, which also seemed to cause some discrepancies. 

I think the estimations we are making in order to calculate the label height [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.1.0-b3/src/app/ui/toc/symbology-stack.directive.js#L686) needs to be looked into to see if there's a good way forward to improve on it.
