### ISSUE TITLE
Implement `predictUrl` geoApi function in Angular

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#2937]
The import wizard's [`predictUrl`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/loader/layer-source.service.js#L87) function is used by the import wizard to determine the service type by poking it. Since it's a geoApi function, it uses the ESRI/dojo request service which expects the service to a JSONP reply. If the service does not support JSONP, the request fails. 

As is the case with this WFS layer: http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/collections/hydrometric-stations/items?startindex=6000 
It loads fine through the config, but fails when added through the wizard. 

Related #2859

**Comment by james-rae** [comment]
We had discussed something similar a long time ago.  One of the suggestions was to use `HEAD` requests on the server instead of attempting to execute a service call and inspect the result / handle the error.

Best to ask Aly for details on how to use the result, I'm under the impression the `HEAD` has some metadata about what the service is.

https://stackoverflow.com/questions/33127985/how-to-use-http-head-to-check-if-some-resource-exists

**Comment by mweech** [comment]
Given our dependence on Esri request library, we will be moving towards user selection of service type as expected functionality instead of intelligent detection.
