### ISSUE TITLE
Intermittent map loading

### ISSUE THREAD

**Issue by jvanulde** [fgpv-vpgf/fgpv-vpgf#2955]
I am noticing that maps are being rendered intermittingly. Example:

    https://open.canada.ca/data/en/fgpv_vpgf/a4b190fe-e090-4e6d-881e-b87956c07977

Sometimes the request to the proxy service is made, other times it is not. I am also noticing that the proxy is sometimes requested twice.

**Comment by james-rae** [comment]
We've tried the above sample URL and were not able to reproduce the intermittent rendering.
In the past, we've encountered situations where every 2nd or 3rd request to a map server failed (i.e. you could hit refresh on a url, and by counting, accurately predict if it would fail). These always turned out to be issues on the server content switch / reverse proxy where it was cycling between a good node and a failed node.  A possible explanation of what was happening.

I do see the proxy being requested twice. Once from the ESRI JS.API, another from a location only listed as `Other` in my web console.  I can't give an explanation as to why, but would appear the double calls are not originating from RAMP code (or if indirectly, the hiding of the 2nd location limits the ability to hunt down the source).

**Comment by jvanulde** [comment]
@james-rae thanks for looking into this. We'll do some more debugging on our end.
