### ISSUE TITLE
Update Data Grid help to better explain expected results

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/fgpv-vpgf#2966]
Attempting to use search, and then filter on a keyword only returns data that matches the start of the data:
![image](https://user-images.githubusercontent.com/5294596/44856181-d10a6480-ac3a-11e8-897b-fe579d8688e3.png)

In this example, we are searching "Indigenous" on the whole data layer, and then filtering "solar" on the Program name column. 
![image](https://user-images.githubusercontent.com/5294596/44856339-2b0b2a00-ac3b-11e8-9843-a331deb438f3.png)

Only one result is returned, when 3 records actually match.

### Conclusion:
Functionality is working as expected, but not well explained in documentation.

## Acceptance Criteria:
- Update in app help documentation to reflect expected functionality of data grid filtering.
- Mark french translations as needing official translation in a future review

**Comment by JahidAhmed** [comment]
I think this is expected behaviour based on how the filtering was implemented.

For the global search, it will match any element regardless of where it appears in the string.
For individual column filters, they only match strings where the text searched begins the sentence. In order to have similar functionality to global search, we'd need to use the wildcard character (`*`). 

So in this case, I think `*solar` would work.

Not sure if this is okay, or if we want to change it completely to have consistency between global search and column filtering.

**Comment by mweech** [comment]
Jahid is correct. A *solar search does work in this case, and the filter is working as expected.  Given it is a filter, regex type queries are being supported.  The text box does a simple keyword search on the contents of the table.

This was also implemented to match requirements of applications within NRCAN that were being replaced so we wouldn't be able to make a unilateral change.

**Comment by james-rae** [comment]
Related issue : https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2637

Though the content of that issue seems to no longer be in alignment with how the app is behaving.  But I think we can all agree Help Docs should reflect what the app is doing
