### ISSUE TITLE
Text length restrictions are required for the length of the download header

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#2978]
We have to implement limitations for title length for downloading. Please see attached.
We have no limit for the title field, but then it displayed incorrectly. Something should be fixed.
![titel length](https://user-images.githubusercontent.com/38046459/45036522-b6653080-b02a-11e8-9ebe-21f719fc0c14.jpg)

**Comment by mweech** [comment]
Limit title length to 128 characters and try to limit file name length as well.

**Comment by ShrutiVellanki** [comment]
> Limit title length to 128 characters and try to limit file name length as well.

Done: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3171

Title length is limited to 128 chars, and as a direct result filename is also limited thanks to this bit of code in `export.service.js`:

```js
            // file name is either the `app id + title` provided by the user or `app id + timestamp`
            if (self.titleComponent && self.titleComponent.value !== '') {
                fileName += ` - ${self.titleComponent.value}`;
            } else {
                const timestampComponent = self.exportComponents.get('timestamp');
                if (timestampComponent) {
                    fileName += ` - ${timestampComponent.value}`;
                }
            }
```

**Comment by AleksueiR** [comment]
I suggest we additionally wrap the title text based on the container width since even title limited to 128 characters but using "wider" letters will not spill over and get truncated.

Similar wrapping is already applied to the footnote using the textflow SVGjs extension, so the code can be just stolen from there.
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/ui/export/export-generators.service.js#L556

**Comment by YaroRoodzit** [comment]
Tested with  Build v2.6.0-b2.
Issue resolved. Works as expected.
