### ISSUE TITLE
Back To Cart - Plugin To Extension

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3061]
The existing Back to Cart plugin works something like this.

- User is on map with catalog layers (RCS keys), clicks Back To Cart
- RAMP places a bookmark in session storage
- RAMP redirects browser to catalog site, appending RCS keys to url (reflective of what is currently on the map)
- User does stuff on catalog site, changes datasets in their cart, then clicks button to return to the map
- RAMP page loads. It sees the bookmark in session storage and recognizes the user is returning from a cart visit
- Decodes the bookmark, compares the RCS keys on the current URL, and makes adjustments to the layers to reflect the current cart. Restores the map to the previous extent/basemap.

Would like to migrate this function to use the modern API / extension frameworks. Would also like to structure it in a way that the RAMP core loading function does not have the "check for cart bookmark in session storage" logic baked into it.  Ideally all the functions of Back To Cart will be contained in the extension.

**Comment by spencerwahl** [comment]
After some analysis;
 - Only major "change" to RAMP would be allowing plugins to create buttons in the sidenav again (a subset of old plugins did this, backToCart being one of them)
 - As discussed, needs `RV` access for bookmarking, should be updated to proper `RZ` bookmarking functions when those are decided upon & implemented (not an issue since `RV` is global..)

**Legacy backToCart**

To keep the current core plugin for v3 we either need to:
- bring back the old plugin registering, it seems like it may be possible but I didnt dig too far. 
:+1: legacy code remains unchanged (though its being changed anyway for the new extension
:-1: don't know if its possible

OR 

- We bundle the extension that comes from this issue with v3
:+1: don't have to fix any broken legacy code on top of adapting to new version
:-1: may have issues if its being "auto" initialized
:-1: will probably have to do some weird shim registration

In either case functionality has to be the exact same, so its just a matter of feasibility and code complexity.
If option 1 works it seems the simplest, otherwise option 2 sounds doable.

note: It seems like #3230 is assuming the second option

**Comment by spencerwahl** [comment]
Second PR covers letting the plugin use #3264
