### ISSUE TITLE
v3: Overriding Intentions with Extensions

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3086]
## Problem
`v3` has two types of tables, `simple table` which is loaded as an intention, `enhancedTable` which is loaded as an extension.

`Simple table` is currently enabled by default. This means when using `enhancedTables` without explicitly disabling `simple table` in the config, `simple table` is rendered under the `enhancedTable`. 

This is just one example but applies to all extensions that will override an intention.

## Possible solutions: 
1. Keep it as is. Users disable `simple table` in config -> the user has to manually disable the table intention when they plan to use the extension
      **This may be problematic**:
      - if user forgets to disable --> we go back to the issue of having two tables
      - if user accidentally disables the intention without the `enhancedTable` extension --> no tables are made

2. Through the `enhancedTable` extension (maybe using `mApi` or something else), disable intention 
i.e.:
    ```js
    // in the extension's preInit(config)...
    config.intentions.table = 'none';
    ```
    **This may be problematic**:
    - May not work as expected
    - Is it ideal for an extension to have enough access to override an intention?
    - Instructions would have to be included in the extension docs

Feedback for alternate solutions and suggestions for how to handle this issue are appreciated.

**Comment by ShrutiVellanki** [comment]
Related: 
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3079 (Point 4)
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3084

**Comment by james-rae** [comment]
Random thought from person fairly unfamiliar with intention/extension architecture.

It's not clear looking at current code how one overrides an intention.  E.g. looking at the epsg lookup intention, if one wanted to provide their own lookup extension it's not clear how.  We have code inside the app like 
`appInfo.plugins.find((x: any) => x.intention === 'epsg')`
to get the function, so I'm not seeing how my own extension could be used without me doing some trickery and overwriting that element in the plugins array.

For extensions that have no related intention, things seem fine.  E.g. the area of interest extension. It loads, does it's own thing, doesn't interfere with internal ramp at all.

For things that have intentions, seems an extension should override it (or is this wrong thinking?).  Should there be some type of tag/property on intentions/extensions to mark certain ones as filling a specific role?  This would mainly impact things that are core to ramp (like epsg lookup, datatable).  
So when we load up all our intentions/extension at startup, we can see that there is intention with `.flavour = 'datagrid'` and extension with the same property, and we know to take the extension, and know that it's filling the role of the datagrid.

Flipside, since this is all done at the time someone is authoring a config file, maybe we just need good documentation on how to not have two datagrids showing up at the same time (though it's still not clear how one overrides something like epsg lookup).

**Comment by milesap** [comment]
The only real difference between an extension and an intention is that the latter may contain special methods or properties that RAMP core knows about. For example, the EPSG intention has a special method `lookup` defined which RAMP is aware of and uses for it's proj4 projection definition lookup. 

All intentions have accompanying documentation which specifies any special required or optional properties/methods. You can see the documentation for EPSG: https://ramp-docs.fgpv-vpgf.com/v2.5.0-0726/#/plugins/intentions?id=epsg

So if you wish to provide your own EPSG intention you would need to:
1. Include your intention code on the host page
2. Tell ramp how to find your intention by changing `EPSG: default` in the config to `EPSG: myEPSG` where `myEPSG` points to your intention object on the window object. 

Having said this, enhancedTable should not be loaded as an extension as it is now in the `index-extension.html` file. It should be loaded as an intention which would replace the simple table. We then have the capability to add special properties and method requirements as needed to support a more complex table without necessarily needing to bloat the api with features only the table will use.

**Comment by ShrutiVellanki** [comment]
@milesap thanks for the clarification, so just to clarify, does this mean that 

**Option 1:**
the `enhancedTable` code in the extensions repo gets scrapped and written each time in.... 
```js
window.enhancedTable = {
       // ...here?
}
```

**Option 2:**
- do an `npm run dev` in the extension repo
- copy/paste the contents of the `dist` folder in the viewer repo where `index-extension.html` can access it
- and:
```js
window.enhancedTable = {
       // code found in copy/pasted dist file loaded here
}
```

My guess is option 2 so that code wouldn't have to be copy/pasted repeatedly is this correct?

**Comment by milesap** [comment]
**Option 2** is the way to go for now, just build the extension and copy/paste the enhancedTable distribution file into ramp (somewhere in the samples folder). You only need to load the script file, it [adds itself to the window automatically](https://github.com/fgpv-vpgf/extensions/blob/master/enhancedTable/index.ts#L94) as `enhancedTable`. 

I'll continue to ponder ways to simplify and automate the building and testing of extensions across different repos.
