### ISSUE TITLE
Bookmark discussion for v3

### ISSUE THREAD

**Issue by milesap** [fgpv-vpgf/fgpv-vpgf#3151]
This discussion ties into the larger **state preservation** topic. We don't have enough time to implement full state storage for the initial v3 release and likely longer into the future. This discussion is aimed at alternate implementation ideas.

### Basic solution first
We provide a basic implementation that is similar in functionality to the current bookmarking solution in ramp core and available in the appropriate parts of the new API. 

:+1: Easy(ish) first step

:-1: Not a solution to state preservation down the line

### Basic solution + intention
Building up from the **Basic solution first**, we allow our basic implementation to be replaced with an intention. 

:+1: Allows custom URL bookmark support
:+1: Can integrate with the existing "Share" popup box in ramp
:+1: Low-Medium implementation complexity

### Basic solution + plugin
Instead of an intention replacing our basic solution (see **Basic solution + intention**) it is instead always available. We then build support in the plugin system to allow for plugins to implement more complex state preservation on top of the existing basic solution. Some implementation requirements: 

- Interface to append the url with custom parameters
- Change `preInit` in plugins such that if it returns a promise that resolves into a ramp config use that config instead.
- Change how plugins are loaded from async to sync so that if one plugin provides an updated config, the next plugin in the loading chain receives that config. Allows for multiple plugins to act as state preservers (either for themselves or globally).

:+1: Allows the most flexibility / freedom for various state preservation requirements
:+1: Moves us away from implementing state storage to a supporting role 

:-1: High implementation complexity

### Just plugin
No basic solution, just right to the hard part 👍 

### Mix and match
Pick some or all from each of the above not listed.

**Comment by ShrutiVellanki** [comment]
## Other functions that don't exist in `v3`
Wanted to note that we still need to decide on the best approach for other functions in [`bootstrap.js`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3/src/app/bootstrap.js) (all of which only exist on `RV`) and functions that used to be there in [`core.run.js`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/core/core.run.js) that is [deleted](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3/src/app/core/core.run.js) as of `v3`. We may have to do a mix and match for these: 
- some remaining in `core.js` and `bootstrap.js` but ported over from `RV` to `RZ`
- some as plugins

## Interim Solution for RCS Keys
Also, the method we end up choosing for bookmarks can have implications for `RCS` keys, as the two go hand in hand.  

`RCS` keys don't work in the current `v3` because they are processed like this in all of our sample pages:

```js
RV.getMap('sample-map').restoreSession(keysArr); // restoreSession is in bootstrap.js
```
As @milesap points out: 
> We don't have enough time to implement full state storage for the initial v3 release and likely longer into the future. 

however, RCS keys probably need to be implemented in time for the `v3` release so we need an interim solution.

---

**Related:** https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3106

**Comment by mweech** [comment]
Basic requirement should be that existing bookmarks must continue to work as before.

With regards to the debate on basic/core/intention, etc.  Given there is no major change to bookmark functionality, we should maintain it as is until such time as we can make a more holistic change to it.

**Comment by spencerwahl** [comment]
Old API reinstated with @milesap's work on #3153 , PR opened to fix the bookmark functionality of the old API

Still need to get bookmarks working with maps created using the v3 api.
