### ISSUE TITLE
Structured legend parent/child and symbology expanded issues in v2.5.0

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpv-vpgf#3152]
1) In structured legends using v2.4.0 and latest v2.5.0 releases, turning parent group off and back on does not retain children's previous on/off settings.
2) In structured legends using v2.4.0 and v2.5.0-0726 releases, children are closed by default ('expanded: false') as expected; in v2.5.0 they are all opened (expanded: true) by default.
3) In v2.5.0 'symbologyExpanded: true' _still_ does not work with Dynamic layer.

Snip of structured legend used in testing with 2.4, 2.5.0-0726, and 2.5:
`

	{"children": [{
		"layerId": "Facilities***faa2798f",
		"symbologyExpanded": true
	}, {
		"layerId": "Reactivation Segments***b861f8b4"
	}, {
		"infoType": "text",
		"content": "The reactivated  segments of the existing Trans Mountain Pipeline"
	}, {
		"layerId": "Expansion Pipeline***cfb53d27"
	}, {
		"infoType": "text",
		"content": "The centre line of the proposed Trans Mountain expansion pipeline"
	}, {
		"layerId": "Expansion Pipeline Corridor***46b068e1"
	}, {
		"infoType": "text",
		"content": "The right of way (ROW) corridor for the proposed Trans Mountain expansion pipeline"
	}, {
		"layerId": "Existing Pipeline***0d0f5a94"
	}, {
		"infoType": "text",
		"content": "The centre line of the Trans Mountain Pipeline."
	}, {
		"layerId": "Shipping Lanes***2f0fa69a"
	}],
	"controls": ["visibility"],
	"expanded": false,
	"name": "Trans Mountain Expansion Project" }, {
		"infoType": "text",
		"content": "<b>Indigenous Consultation Groups</b>" },

`

**v2.5.0**
![parent_child_on-off_2 5](https://user-images.githubusercontent.com/2006029/49164660-8f528e00-f2fd-11e8-9c0f-892b65455665.gif)

**v2.4.0**
![parent_child_on-off](https://user-images.githubusercontent.com/2006029/49164866-f96b3300-f2fd-11e8-95d9-3927bb70bb72.gif)

---

#### Symbology
- Remove/modify additions causing the children to be updated
- In `symbology-stack.directive.js`, remove the listener here so the symbology don't get toggled
- Add menu options to show/hide all in `legend-node.html`

#### Groups
- In `legend-block.class.js` modify set visibility to cache the children visibility.
- In the same class add function to handle the toggle all on/off cases
- Add menu options to show/hide all in `legend-group.html`

### Acceptance Criteria
- [ ] Turning a parent group off then on retiains the children's previous on/off settings
- [ ] Turning a layer with symbology items off then on retains symbology on/off settings
- [ ] Using the hide all option in a group sets all child entries to hidden
- [ ] Using the show all option in a group sets all child entries to shown
- [ ] If all children were toggled off, the parent should toggle off
- [ ] Toggling the parent off after the above should cause all children to toggle on
- [ ] Using the menu option to show/hide all should steamroll the changes all the way down

**Comment by mweech** [comment]
Hi Benoit, here are some comments:

1. This has always been the intended behavior.  If a user checks a parents state off then back on, its assumed that parental state will override the children (as my sons have learned :).  We also do not track state to restore it at some unknown point in the future.
2. Will check to confirm if this was intended change, but I believe it was.  Most clients have been preferring to have them expanded initially (but shouldnt be a surprise change if its intentional).
3. You will need to provide a larger snippet that is complete.  From what I see, the Facilities item IS expanded, but not its underlying child layer "Trans Mountain Facilities"

**Comment by bchagnon** [comment]
> Hi Benoit, here are some comments:
> 
> 1. This has always been the intended behavior.  If a user checks a parents state off then back on, its assumed that parental state will override the children (as my sons have learned :).  We also do not track state to restore it at some unknown point in the future.

Okay. The question came about after we observed that the display state of a child's multi symbols settings are preserved by the parent and thought that would also apply to the group parent.

> 2. Will check to confirm if this was intended change, but I believe it was.  Most clients have been preferring to have them expanded initially (but shouldnt be a surprise change if its intentional).

If expanded initially is the new default then is there a simple way of having all closed by default instead of having to wrap each of them with something like `


		{ "children": [{
				"layerId": "First Nations***2dff3727",
				"symbologyExpanded": true
			}
		],
		"controls": ["settings", "visibility", "opacity", "query", "reload"],
		"expanded": false,
		"name": "First Nations"
		}

`

> 3. You will need to provide a larger snippet that is complete.  From what I see, the Facilities item IS expanded, but not its underlying child layer "Trans Mountain Facilities"

Yes, the Facilities item IS, but I am talking about the multi symbols in the item itself not being expanded even though the "symbologyExpanded": value is set to true. I guess its related to this entry #2987

**present output** using _"symbologyExpanded": true_:

![multi-symbols](https://user-images.githubusercontent.com/2006029/49176149-2e847f00-f318-11e8-8026-30a519ecfe61.png)

**desired output** using _"symbologyExpanded": true_:

![multi-symbols_expanded](https://user-images.githubusercontent.com/2006029/49176157-32b09c80-f318-11e8-962a-2bfb099ec9ab.png)

**Comment by mweech** [comment]
@bchagnon can you share your config file?  I was typing up a response but realized I really need the whole config to be able to give you an accurate response.  Have a hunch I know what is working differently then expected, but hard to say without the whole config file.

**Comment by bchagnon** [comment]
Sure, but be the map is in draft only mode and not to be shared with the public hence the secured map service it is referring to.  I'll send you the file and access credentials outside of Github.

**Comment by bchagnon** [comment]
Still not convinced that :

> This has always been the intended behavior. If a user checks a parents state off then back on, its assumed that parental state will override the children

It did not behave like this in version 2.4.0. A user needs a way to turn on/off the group of customized on/off children.

**v2.4.0**
![symbols-state_2 4 0](https://user-images.githubusercontent.com/2006029/49318810-fde34780-f4c7-11e8-885b-d8dddf10dbd0.gif)

**v2.5.0**
![symbols-state_2 5 0](https://user-images.githubusercontent.com/2006029/49318816-05a2ec00-f4c8-11e8-81ad-2e5aad4ba4ef.gif)

**Comment by bchagnon** [comment]
Fair enough. But there definitely is more than a use case for turning on/off the group of customized on/off children if you consider that the behavior, be it a side-effect and not intentional, has _afaict_ been present since at least version 2.3.0. The FGP portal users have been accustomed to it, and expect it when viewing multi symbol layers (sometimes with way to many symbols, I concur).

![fgp_custom_children](https://user-images.githubusercontent.com/2006029/49472880-93d7e480-f7de-11e8-94b5-9ec09bc8183c.png)

We were about to upgrade the viewer version on the portal from 2.3.0 to 2.5.0 but this surprise ux change will most probably delay the upgrade.

**Comment by bchagnon** [comment]
But note that the above should not affect users of the Open Maps Data Viewer if and when the admins ever upgrade their viewer from version 2.0.0 over to 2.5.0; version 2.0.0 does not allow turning individual layer symbols on or off :)

**Comment by AleksueiR** [comment]
At this point, I think everyone agrees these two use cases are worthwhile and should be addressed. Regardless of our initial intentions, the user-expected behaviour needs to be preserved; furthermore, it matches the default behaviour of the ArcGIS Online map viewer which many RAMP users will be familiar with.

I can think of three options:
#### 1. Legacy mode
A new config option is added to toggle between `legacy` (children's states are preserved upon toggling their parent) and `new` (children's states are reset to their parent's state) modes of parent/child interaction. A config author would need to select which state the map will operate in.

Pros:
- separates our botched implementation from initial intentions
- provides a mode aligning with ArcGIS Viewer map
- provides a mode implementing our initial intentions

Cons:
- need to implement both approaches
- a map author needs to know about this option and decide which mode to use
- a user would not know which mode is active (this one is really bad - maybe a mode indicator should be added anyway, or the user _can_ be given control over the mode) and would not have any control over it
- the same user might encounter maps with both modes with would be confusing

#### 2. Hybrid
We implement the legacy mode (children's states are preserved) and add additional two options to all groups' context menus letting users manually reset the group and all its children to visible or hidden. 

![](https://i.imgur.com/eRir3lu.png)

This will be similar to the visibility menu we have in the top right corner of the panel which can show/hide all the layers at once.

![](https://i.imgur.com/T8zbCp2.png)

Pros:
- need to implement only one approach
- users are likely to be familiar with it from 2.4, so there is no learning curve
- users have new menu options to reset groups' visibility similar to our original intentions
- aligns with behaviour of the ArcGIS Map viewer and exclusive visibility group (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2224#issuecomment-316987070)

Cons:
- these menu options are not dead obvious since they are hidden in the menu, but they are discoverable
- most work (arguably)

#### 3. Lazy
Implement just the legacy mode and pretend nothing happened.

Pros:
- least amount of work (arguably)
- users are likely to be familiar with it from 2.4, so there is no learning curve
- aligns with behaviour of the ArcGIS Map viewer and exclusive visibility group (https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2224#issuecomment-316987070)

Cons:
- resetting visibility for a large group needs to be done by hand which can be tedious for the user

### Thoughts
Option 1 is the worst since we start adding invisible app modes which users can't control (or worse, _can_ control) - different application modes just needlessly tax users' memory and attention.

Option 2 is the most favourable, in my opinion, since we preserve the behaviour users are familiar with and provide an option to reset group visibility through the menu. 

Option 3 is sub-optimal and it's technically a half of Option 2 and can be implemented if there is no time to fully implement Option 2.

### Note
The 2.4 implementation preserves the states only of the symbology items (as far as I know). In options 1 and 2, this needs to be expanded to also preserve the state of actual child element (`LegendNode`s) as well. Otherwise, the behaviour becomes fragmented.

**Comment by AleksueiR** [comment]
Hey, @bchagnon,
@dane-thomas has implemented Option 2 from [this comment](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3152#issuecomment-445801582) and it's in PR right now. If you have time, could you please review the demo and make sure it addresses the issue correctly? Thank you.

Demo link:
http://fgpv.cloudapp.net/demo/users/dane-thomas/symbol-stack/prod/samples/index-samples.html?sample=75&keys=JOSM

**Comment by bchagnon** [comment]
@dane-thomas Beautiful, great job! The solution addresses the issue @AleksueiR Thank you.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b4
Sample #26. http://fgpv.cloudapp.net/demo/v3.1.0-b4/prod/samples/index-samples.html?sample=75
Works as expected.
