### ISSUE TITLE
v3: RCS Layers load multiple times on language switch

### ISSUE THREAD

**Issue by spencerwahl** [fgpv-vpgf/fgpv-vpgf#3255]
example:
http://fgpv.cloudapp.net/demo/v3/prod/samples/index-fgp-en.html?keys=josm

Change language to french (in RAMP), multiple copies of the layer will be added.

Some investigation done by myself, @james-rae and @milesap so far:
- Loading the layers using `RV.getMap('fgpmap').loadRcsLayers(['josm'])` after the map loads seems to not multiply the layers on language switch.
- works fine on develop
- not caused by recent changes to legacyApi proxies
- get 5 copies of josm, very probably related to having the base dynamic layer + 4 children

**Comment by ShrutiVellanki** [comment]
I think I found a fix [link](https://github.com/fgpv-vpgf/fgpv-vpgf/compare/v3...ShrutiVellanki:rcs-load?expand=1). 

### [demo](http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/rcs-load/dev/samples/index-fgp-en.html?keys=josm)

**Test**
- only one layer on language switch
- preserves extent if you change it (which means RCS key loads with bookmark 
   - I have `console.log` which `RCS` layer loads on language switch so you can see it change from `rcs.jsom.en` to `rcs.jsom.fr` and add a bookmark on language change
   - alternatively you can use the [bookmark decoder](http://fgpv.cloudapp.net/demo/develop/prod/samples/bookmark-decode.html) to verify this

**The Problem**
- in [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/compare/v3...ShrutiVellanki:rcs-load?expand=1#diff-f98e10969e55a03227efed0aeedc4b71L165), and the code underneath would trigger the `rvCfgUpdated` event (wasn't there in this file in develop) regardless of whether the layer it was adding already existed in the legend or not 
- this would start a chain that would add multiple of the same `layerBlueprints` and in turn create a new `legendBlock` for each one. 
- I made a simple dictionary to keep track of whether a layer that the viewer was attempting to add was already added (so that it wouldn't add multiple times to the legend)

Let me know if this looks right. If it does, I'll go ahead and PR it with proper comments after I delete my `console.logs`. If it doesn't, I'll attempt another fix/look into it further/leave it.

**Comment by ShrutiVellanki** [comment]
Might be worth noting, the solution above may not be ideal as pointed out by @james-rae as it changes code that wasn't changed from `develop` to `v3`: 

Things I found upon further investigation: 

Two additional calls to [`processRcs`](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3/src/app/core/config.service.js#L136) AFTER language switch on `v3`. Could be a result of the function staying in the [legacy api queue](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3/src/legacy-api.ts#L35) and executing when map loads after language switch but I'm not sure.

## v3

![image](https://user-images.githubusercontent.com/25359812/51868447-1206c200-231c-11e9-8dcc-555536f2b7a4.png)


## develop
![image](https://user-images.githubusercontent.com/25359812/51858215-2e960080-2302-11e9-8de4-b961e6fd2bd2.png)

**Comment by james-rae** [comment]
I think I've boiled it down to [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/12bb02f0564ac492cd924e5946e83535fc359fd5/src/app/core/core.run.js#L70). During a language change, `preLoadApiBlock` gets called again (the RCS loading for language has already happened at this point).  However, now that we have this `runQueue()` call, it ends up triggering `restoreSession()` which then calls `LEGACY_API.loadRcsLayers(keys)` and causes more layers to spawn.

I don't understand the details of legacy-api, but I did this little cheat test to only run the queue the first time and things seem to be behaving on language change. Unsure if this breaks other scenarios.

```
if (magic === 0) {
    magic = 1;
    legacyAPI.runQueue();
}
```

Will pass the thread back to @milesap and @spencerwahl for legacy-api expertise.  Handwaving though is that  `preLoadApiBlock` needs to know the situation it's in and act accordingly.
