### ISSUE TITLE
Enhanced table stays open when settings or metadata panels are opened

### ISSUE THREAD

**Issue by dane-thomas** [fgpv-vpgf/fgpv-vpgf#3288]
### Problem
The table panel stays open and is rendered on top of the settings or metadata table panels. Table will also open on top of the settings or metadata panels if they are opened first.

### Expected behavior
The currently open panel closes making room for the opening panel

*Note: This also happens with the simple table

**Comment by milesap** [comment]
Things to ponder:

1. Should a panel which is being either partially or fully covered by another panel be closed (state loss - not re-opened once covering panel is closed), hidden (state preserved - reopened once covering panel is closed), or made semi-transparent?

2. Should the incoming panel be responsible for checking and closing/hiding/transparency of affected panels, or should the panel which is being either partially or fully covered by another panel watch for and react as needed?

3. Does it make sense to move some/all of this coordination logic away from individual panel implementations and instead do this within the panel API? So opening a panel auto closes/hides/transparency any panels in its path.
    - Should individual panels be able to customize how the panel API handles closing/hiding/transparency? For example, should panels be able to declare themselves as "always open" (incoming panel would fail to open over it or would "open" but would immediately start it's closing/hiding/transparency routine), or perhaps whether they close vs hide etc.

I don't believe we can hard code any specific closing patterns for panels now that we cannot know the positions of all possible panels until run time.

**Comment by AleksueiR** [comment]
I remember we made some of these decisions last summer when the first cut of the Panel API was being made. It must be written somewhere. I found [this issue](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2697), but there is no details on panel behaviour when overlapping with other panels.

**Comment by milesap** [comment]
# General Outline

The following is a general outline of how the new panel system will manage panel "collisions". A collision is when a panel (lets call it the **overlaying panel**) attempts to open either partically or fully over one or more other panels (which we'll call the **underlay panels**).

## Goal

To provide a simple mechanism for panels to co-exist on a 2D plane without the need for individual panels to monitor and react to external changes in regards to new panels being created, moved, or opened/closed.

## Panel underlay rules

A panel can prescribe to one of three underlay rules during its creation, depending on its needs and which are enforced by the RAMP panel API once the panel has successfully opened. The rule governs what happens to the panel when another panel is trying to open over it.

- `default`: this panel will be hidden from view - likely with the css property `visibility:hidden`. An observable named `hiding` will emit with the overlaying panel instance. **This panels visibility will be restored once the overlay panel has closed.**
- `close`: this panel will be closed using the panel API method `close`. It is not restored automatically.
- `persistent`: this panel refuses to hide or close. The call to `open` on the overlaying panel will fail and it will need to locate another spot or fail gracefully.

### General comments

The `open` method will be altered to `open(): {status: boolean | panels: Panel[]` which now returns a boolean status indicating if the operation was successful and an array of panels that occupied its space.

A panel cannot change its underlay rule.

A panel should not change its relative position, or have its computed width/height altered once opened. Doing so triggers an underlay rule check which if failed causes the panel to be closed. Monitoring panels can be done with a `MutationObserver` scanning for changes to the `styles` property and changes to the viewport size.

When the viewport size changes the underlay rules are verified in the order the panels were opened.

**Comment by james-rae** [comment]
I'm not a UI guy, but I might be worried that in `default` mode, I'd think the panel had closed when it goes invisible.   

Would making it something like 60% transparent work?  I guess that is problematic as the user could still interact with it.

**Comment by ShrutiVellanki** [comment]
### On Underlay Rules:
---
I like the three *types* of "underlay rules" but I'm just worried something like this could happen: 
- panel 1 subscribes to a default rule
- panel 2 subscribes to a close rule
- panel 3 subscribes to a persistent rule

![group 1](https://user-images.githubusercontent.com/25359812/53045494-c3040680-345b-11e9-8596-163faca974d5.png)

Panel 4 is trying to open on top of all three of them.
- Panel 1 becomes invisible
- Panel 2 closes
- Panel 4 can't open in 3's spot so it relocates with 3 still open

You close Panel 4.
- Panel 1 is visible again, Panel 3 was always visible. Panel 2 is still closed. 

Maybe this scenario is unlikely but it seems like somewhat of a weird possible experience. 

----
### Possible combined solution:  Stubborn Panels + Accommodating Panels. 

#### Stubborn Panels

A similar approach to what @james-rae said would work for panels like the side menu and "Link to Share":

![image](https://user-images.githubusercontent.com/25359812/53045824-9ac8d780-345c-11e9-964d-011220da43fb.png)

![image](https://user-images.githubusercontent.com/25359812/53045788-7ec53600-345c-11e9-9644-a04e990476aa.png)

They "grey out" + "freeze" ALL OTHER panels when open, and make it impossible for anyone to interact with them/open them until they are closed. If panels like these are on top, any other panel trying to open through the API fails until they are closed, period.

#### Accommodating Panels

An example of this panel would be `enhancedTable`/`meta data`/`settings`...to me, intuitively at least, it seems that if a user is trying to open metadata when `enhancedTable` was open, they want to interact with metadata ASAP (especially since they are tied to the same underlying feature), so `enhancedTable` should be accommodating enough to close (and vice versa).

Note that this use case would only make sense for panels that save their state on close...(`enhancedTable` does this and so does import wizard if you try and open up layers in the middle of it). This way the user knows that their progress won't be lost even if the panel disappears from view. If they don't save their state on close, they should be a stubborn panel.

**Comment by milesap** [comment]
New issue opened: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3312

**Comment by mweech** [comment]
Close on completion of changes to Panels API noted in #3312 

QA to note test case to cover panel interaction based on this issue.

**Comment by dane-thomas** [comment]
Testing done after merging the above PRs. The table interacts with the settings and metadata panels as expected.
