### ISSUE TITLE
Update Sample Test Pages to use Enhanced Grid

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3299]
The QA team utilizes `index-fgp-en.html` and `index-samples.html` for a number of tests.  Currently these pages are using the basic grid on the `v3` builds.  Should convert them to use the enhanced table plugin (maybe a few of the samples configs can be left as basic to test the basic grid).

Hopefully this can be done with a batch-replace over the config files.

**Comment by mweech** [comment]
The issue should be amended to PREVENT usage of the basic table under 3.0 as it is not released in its current form.

**Comment by ShrutiVellanki** [comment]
> The issue should be amended to PREVENT usage of the basic table under 3.0 as it is not released in its current form.

Alright, going forward with this. On @milesap's suggestion, going to pull `enhancedTable` into the build so that it replaces the basic table. The sample pages won't need to be changed (all of them will load `enhancedTable` instead of the basic table by default).

**Comment by james-rae** [comment]
https://github.com/orgs/fgpv-vpgf/teams/ramp-core/discussions/2

**Comment by milesap** [comment]
Steps to pull in `enhancedTable` into the RAMP build.

## Update plugins repo

The plugins repo publishes to npm. Currently the only plugin being exported in the npm package is `BackToCart`. To export enhancedTable, add it to the [npm index file](https://github.com/fgpv-vpgf/plugins/blob/2245869f7facbdf733f02831ed7e8987690fbe27/index.ts).

> Make sure you export the class, if not the TS compiler should complain. See [example](https://github.com/fgpv-vpgf/plugins/blob/2245869f7facbdf733f02831ed7e8987690fbe27/backToCart/index.ts#L1)

Then run `npm version patch` locally and wait while travis publishes to npm.

## Add npm package @fgpv/rv-plugins as a dependency to ramp

Run `npm i -S @fgpv/rv-plugins` locally within the ramp repo. 

## Import and initialize in plugin-loader.ts

Import the enhancedTable plugin in the `plugin-loader.ts` file of RAMP, something like:

```ts
import { EnhancedTable } from '@fgpv/rv-plugins';
```

Then use some magic in that file so that the imported `EnhancedTable` object is treated like a normal plugin and is initialized as any other. 

Some code I wrote for pulling in `BackToCart`: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3260/commits/3e82d31fa314eef41dedfc124254ee3ce52bb212

Feel free to take what you need from there.

**Comment by dane-thomas** [comment]
There were issues with the way files were being imported making the npm package usage tricky. That code has been refactored to import the css properly. 
Relevant PRs: 
- https://github.com/fgpv-vpgf/plugins/pull/52
- https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3330

Since the map authors will be including both the minified js and css, there's no reason to import the css in `panel-manager.js` (which was being done).

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2. 
Samples are using the new grid
