### ISSUE TITLE
Initial Map draw is not happening in IE11 for both Marcator and Lambert Map

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3339]
Tested with build:v3.0.0-b1

I have noticed an issue while I try to import scale dependency layer, I was not able to view map points. Map point do not update automatically for both Mercator and lambert map. The points do appear when you pan or zoom.
This issue is specific to IE 11 only. I tried with clearing cookie but issue still exists. Checked with Firefox and it works fine. 

Steps to reproduce:

1.	Use IE 11 and go to http://fgpv.cloudapp.net/demo/v3.0.0-b1/prod/samples/index-fgp-en.html
2.	Import below service:
http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/CESI/CESI_AirEmissions_SOx/MapServer
3.	Select all layers within configure layer option and click continue.
Expected Result: Map should update with map points for the imported layers.

Actual Result: Map does not update with map points.

Below is screenshot for both maps:

![screenshot_0603_import services issue1](https://user-images.githubusercontent.com/46937257/53968578-5c225680-40c5-11e9-92aa-da652e0d8af3.JPG)

![screenshot_0603_import services issue2](https://user-images.githubusercontent.com/46937257/53968621-6a707280-40c5-11e9-9711-ce51e5d7fac6.JPG)

**Comment by JahidAhmed** [comment]
This seems to be an issue affecting all layers (not only scale dependent layers) when importing them as dynamics (on the server linked above).

For example, I tried http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/EcoGeo/EcoGeo/MapServer/6 as both a feature and a dynamic and the latter does not work until a pan or zoom occurs. I also tried the layer on the prod server (http://maps-cartes.ec.gc.ca/arcgis/rest/services/EcoGeo/EcoGeo/MapServer/6) and it causes issues too.

However, if I try http://section917.cloudapp.net/arcgis/rest/services/EcoGeo/MapServer/6 as a dynamic, it seems to work fine.

Another example: http://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/LWBSF/LWBSF/MapServer/10 (broken) vs http://section917.cloudapp.net/arcgis/rest/services/LWBSF/MapServer/10 (working).

NOTE: Dev/prod are version 10.41 and the working one is 10.51. Another working example (http://geoappext.nrcan.gc.ca/arcgis/rest/services) is also 10.5. However, it does not seem to be as simple as an issue with all v10.4.1 since another tested example (http://www.agr.gc.ca/atlas/rest/services) is working as expected (and is 10.4.1).

NOTE: Dev/prod servers seem to be working on average once every few tries (sometimes a lot more/less frequently), so may be an issue with a broken node. In general, only seems to be a problem with our servers.

**Comment by mweech** [comment]
Closing because of issue only affecting ECCC servers, using IE11 and adding as Dynamic.  Not sufficient priority to solve.
