### ISSUE TITLE
Convert Metadata and Settings to Panel API

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#3364]
Convert the Metadata panel and Settings panel to Panel API.  These items have been grouped due to similarity in behavior and point of invocation.

**Comment by ShrutiVellanki** [comment]
One week update:

#### Done:
- migrating settings, metadata and metadata expanded panel to `Panels API`
- separating out headers/bodies 
- everything interacts properly (i.e. metadata opens --> settings closes and vice versa)
- data corresponds to proper `LegendBlock` 
- making changes to panels updates map and vice versa
- panels properly close, update, and reopen on reload

#### Discussed/Resolved: 
- was having discussion with @spencerwahl  about what to do if user tried using the `PanelAPI` to toggle metadata/settings...`PanelAPI` doesn't take a `legendBlock` as a parameter so the toggle wouldn't be "linked" to a `legendBlock'
- we decided the user should handle toggling of these panels with the `LegendAPI` since it links `legendBlock`in its `toggleMetadata` and `toggleSettings` call (this should be made clear in future documentation)
- `open`/`close`/`toggle` will still be accessible through the `PanelAPI` but these will be used to toggle `metadata` and `settings` internally

#### TODO: 
- metadata currently always shows sad canada failure image (even when there is metadata to populate)...something between `metadata-content-directive.js` and `metadataPackage` that is made in `displaymanager.service.js` is currently broken
- make everything mobile compatible
- style fixes (centering a few things here and there)

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b2
Sample #6.
As expected.
