### ISSUE TITLE
Regression UI Bugs

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#3397]
#### 1. Button focus highlight is not centered in the Settings, Metadata, Details, Expanded Details, and Help panels

![](https://i.imgur.com/oaIbRbK.png)

![](https://i.imgur.com/e7Rc74Z.png)

![](https://i.imgur.com/47f3hab.png)

![](https://i.imgur.com/QwQGmaV.png)

![](https://i.imgur.com/gTIhMnX.png)

#### 2. Map navigation cluster buttons are not sized correctly and their focus highlight is offset as well

![](https://i.imgur.com/bSiQav2.png)

The buttons should have size of 32x32; now they are 32x40.
Correct sizing:
![](https://i.imgur.com/3yvsqJH.png)

**Comment by dane-thomas** [comment]
The issues with the focus indicators was caused by enhanced table css overriding some RAMP styles. 

Another UI regression to do with the new panels. Panel close buttons do not have a focus indicator. I think this should apply for any buttons created through the panel api but needs a little more testing to confirm.

**Comment by dane-thomas** [comment]
Another UI regression found for the details and zoom buttons on the table with the buttons not being centered within the column. Moving back to in progress

**Comment by YaroRoodzit** [comment]
Tested build: V3.0.0-b2
Issue solved.
