### ISSUE TITLE
Data table panel remains open after layer is removed

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3439]
Tested with build: V3.0.0-b2
When you remove layer, data table is not closing automatically. Tested with IE 11 and Google Chrome browser. Below are steps to reproduce:

1.	Go to http://fgpv.cloudapp.net/demo/v3.0.0-b2/prod/samples/index-fgp-en.html
2.	Add layer
3.	Import file (e.g. Canada. Jason)
4.	View data table
5.	Remove Layer
6.	After removing layer, data table panel should also close but it remains open and you have to manually close the panel.

Screenshot:
![Table not closing](https://user-images.githubusercontent.com/46937257/56897583-df747e80-6a5c-11e9-9265-d09a9fb292a4.JPG)

**Comment by dane-thomas** [comment]
Partially fixed in https://github.com/fgpv-vpgf/plugins/pull/79; Determined to be enough for 3.0 release.

### Solution Limitations
 - Table will close once the "undo remove" toast closes so the empty table stays open momentarily
 - Table will not close until all children are removed for dynamic layers.

### More robust solution for a future release
Add an observable in `legend.ts` for removal of elements from the legend. Trigger right as element is removed from legend. Swap out layer remove for legend item remove in table. 

This would allow the table to close immediately and should also close for dynamic children as well

**Comment by YaroRoodzit** [comment]
Tested build: v3.0.0-b4
Issue solved.
