### ISSUE TITLE
Table retains external filters after layer reloads

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3499]
To replicate:

Load
http://fgpv.cloudapp.net/demo/develop/prod/samples/index-fgp-en.html?keys=JOSM

Open the datatable.
Expand the symbol stack in the legend and uncheck one of the symbols.  The table will update itself and show that rows are being filtered in the row count.

Reload the layer via the layer settings menu.

Open the datatable.

You'll see the legend is in the default state (all symbols checked), but the table is still remembering the old filter that was applied.

Handwaving analysis is that during a reload, the filter state is remaining somewhere for the symbols (either in the layer record's filter, or in the grid internals).  
Figure out where, and then have the reload code clear the state (e.g. setting the symbol sql to '', or shooting off a grid observable) to match the refreshed legend.

**Comment by yileifeng** [comment]
May or may not also be relevant: `findOpenPanel(panelSwitch, legendBlock)` in toc.service.js is never detecting an open table panel, whereas the function works properly for an open settings or metadata panel. 

This may also be due to how the panelSwitch mapping is set up: 

`panelSwitch.metadata.panel = mApi.panels.metadata;`  
`panelSwitch.settings.panel = mApi.panels.settings;`

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b1
Issue solved.
