### ISSUE TITLE
Details panel is not properly populated sometimes

### ISSUE THREAD

**Issue by ShrutiVellanki** [fgpv-vpgf/fgpv-vpgf#3517]
Originally posted [here](https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3441#issuecomment-494536698)

> 
> @YaroRoodzit pointed out that if you click on an empty portion of the map and then click on a point, this happens on and off:
> ![image](https://user-images.githubusercontent.com/25359812/58126670-727a8180-7be1-11e9-847a-b50395562660.png)
> (Point is found in the legend but the Details doesn't show it).
>

**Comment by dane-thomas** [comment]
It looks like the details are populated fine since the indicator shows up for the nuclear layer. 

The issue seems to be more that the layer where details are found is not selected by default

**Comment by james-rae** [comment]
I was able to get the following case (which I thought was what the bug was describing).

- Click nowhere. Get a nonethanks
- Click on a cluster of points. Get a list with one layer selected
- Click nowhere. Get a nonethanks, but the side list remains (as in screenshot above).  If you click an item in the side list, the result appears.

So it seems the data structure in the side list (either in identify, or in the angular directive, or state manager, or where-ever) isn't clearing out the past results properly in the nonethanks event.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b1
Test sample: 6
Issue solved.

**Comment by AleksueiR** [comment]
eh, this is actually a feature, not a bug - the details panel remembers your last layer selection on the side menu until the details panel is closed. This is useful when you just want to see the details for a specific layer (even if there are none) while exploring several points on the map.

**Comment by AleksueiR** [comment]
Please see this comment for implementation details: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/645#issuecomment-222126596

**Comment by RyanCoulsonCA** [comment]
Reverted. See https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3581
