### ISSUE TITLE
Structure legend symbology stack images

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3518]
When we replace icons (unique value renderer) for a layer inside the structure legend, the unique value visibility selector doesn't work anymore.

![NotWorkingStack](https://user-images.githubusercontent.com/3472990/58259556-ca7cc980-7d42-11e9-972f-485dabe15b5a.gif)

Config file snippet
```
"symbologyStack": [
                {
                    "image": "https://geoappext.nrcan.gc.ca/fgpv/images/saving.png",
                    "text": "A"
                },
                {
                    "image": "https://geoappext.nrcan.gc.ca/fgpv/images/powering.png",
                    "text": "B"
                },
                {
                    "image": "https://geoappext.nrcan.gc.ca/fgpv/images/reusable.png",
                    "text": "C"
                },
                {
                    "image": "https://geoappext.nrcan.gc.ca/fgpv/images/world.png",
                    "text": "D"
                }
            ],
            "symbologyRenderStyle": "icons",
```

**Comment by james-rae** [comment]
This is a combination of a bug and a missing feature.

The bug is that the checkbox is showing up.  We should have logic suppressing that checkbox if the symbol stack has been overwritten.

The missing feature is https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3143
This feature would provide a means to allow the symbol stack in your example to define how it interacts with the layer filter.

There is a bit of a workaround currently, using the `customRenderer` in the layer config.  However this will force the symbols on the map to be the same as your legend, which would defeat what you're attempting to do here.

**Comment by yileifeng** [comment]
Tried to reproduce this issue using the following config file snippet: 

```
"symbologyStack": [
    {
        "image": "http://fgpv.cloudapp.net/demo/__assets__/beautiful.png",
        "text": "A"
    },
    {
        "image": "http://fgpv.cloudapp.net/demo/__assets__/cookies.gif",
        "text": "B"
    },
    {
         "image": "http://fgpv.cloudapp.net/demo/__assets__/tenor.gif",
         "text": "C"
    },
    {
         "image": "http://fgpv.cloudapp.net/demo/__assets__/tiles.png",
         "text": "D"
    }
],
"symbologyRenderStyle": "icons"
```

The symbology checkboxes seem to be correctly suppressed.

**Comment by RyanCoulsonCA** [comment]
Tested using [`sample 91`](http://fgpv-app.azureedge.net/demo/branches/develop/dev/samples/index-samples.html?sample=91). Visibility selector now seems to be working as intended.
