### ISSUE TITLE
Layer  is not displayed initially.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3529]
Tested build: v3.0.0-b5
The layer "2 column filters" is not displayed initially.
Steps to reproduce.
- Open http://fgpv.cloudapp.net/demo/v3.0.0-b5/dev/samples/plugins/coordInfo/samples/coordinfo-index.html
- Validate that layer "2 column filters" is not displayed initially.
The layer becomes visible after it is hidden and selected for re-display.

**Comment by james-rae** [comment]
Brief analysis. 
This service isn't ours, and it's possible they have re-published and changed their object ids since the test was made.
The initial filter results in no rows, so nothing visible on the map is correct. (`Abbotsford` has object ids 23 and 24; filter appears to have been written when they were less than 10)

However, toggling the visibility should keep the map invisible.  It appears the map is losing the grid filter when the visibility gets toggled.  So that is something to look into why
