### ISSUE TITLE
Changing the language causes a lot of errors in the console.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3534]
Tested build: v3.0.0-b5
When in IE a language change causes a lot of errors in the console.
The problem exists in other browsers.
![image](https://user-images.githubusercontent.com/38046459/58648311-6f654c80-82d7-11e9-993f-807f7be83591.png)

**Comment by YaroRoodzit** [comment]
Just to point out that Microsoft Edge has the same problem.
![image](https://user-images.githubusercontent.com/38046459/58814204-5ddfb580-85f3-11e9-8d0f-91055ab2b394.png)

**Comment by yileifeng** [comment]
Follow up: 

Using http://fgpv.cloudapp.net/demo/develop/dev/samples/index-fgp-en.html?keys=JOSM also produces some additional errors: 

![additional errors from keysJOSM](https://user-images.githubusercontent.com/31557789/58881265-d142ff00-86a7-11e9-9e37-71b1bb326273.PNG)

The first error only occurs on the first time changing the language. 

The second error is caused by the listener 
```
configService.onEveryConfigLoad(config => {
        if (config.map.components.geoSearch.enabled) {
            init();
        }
    });
```
in `geosearch-filters.service.js` 

For the last error, it is a bit inconsistent as I can't seem to reproduce it with the given link, so maybe it was just something I changed and tested locally.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b2
Issue solved.
