### ISSUE TITLE
The viewer loses focus after using Export, Share, HELP.

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3537]
Tested build: 3.0.0-b5
http://fgpv.cloudapp.net/demo/v3.0.0-b5/prod/samples/index-fgp-en.html
    The problem exists and is easily reproduced in IE during navigation only from the keyboard.
Focus returns to the menu after pressing Alt + Tab.
Steps for reproduce: 
- Go to Menu and select  Export, Share or HELP.
- Try to use and close or just close the selected one.
- Check that the focus is lost and no further navigation using the Tab is available. An error displayed in the console.
![image](https://user-images.githubusercontent.com/38046459/58660662-f1636e80-82f3-11e9-90e5-adb76f0b8707.png)

**Comment by RyanCoulsonCA** [comment]
My initial findings:

1. This issue only seems to be happening on IE (tested Chrome and Firefox and both work when closing the panels)
2. It's not specifically just export, share and help that are causing the issue, it's any window that pops up over the viewer. Opening the data table and closing it causes the same problem.
3. The problem only occurs if you use the `close` button on the panel. Pressing `esc` to close the panel doesn't cause it.

**Comment by RyanCoulsonCA** [comment]
Some more interesting findings:
1. In both browsers, when a panel is closed and tab is pressed, `rvFocus` is being called on element at the beginning of the document (not in the viewer). For example, using `index-samples`, rvFocus is being called on the drop down menu to select a sample. The dropdown doesn't seem to actually be in focus, because it is not highlighted and I can't use the arrow keys to navigate through the options.
2. After closing a panel in IE and then alt-tabbing out and back in, focus is restored on the correct element within the viewer. In Edge, this does not happen.
