### ISSUE TITLE
Close panel button is squished in IE 

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3584]
Tested with V3.1.0-b1

Noticed that close panel button is squished in IE when tying to view details of layer after importing service layer. 

Steps to reproduce:

1.	Using IE, go to http://fgpv.cloudapp.net/demo/v3.1.0-b1/prod/samples/index-fgp-en.html
2.	Import service layer –
http://geoportal.gc.ca/arcgis/services/Arctic_Voyage_Planning_Guide_ENG/MapServer/WmsServer
3.	Click on layer within map to view details
4.	Close panel button is squished

Noticed this only with IE browser

![IE Closed button panel is squished](https://user-images.githubusercontent.com/46937257/59380601-7ce2f380-8d27-11e9-8857-38513b8c2930.JPG)

****

**Comment by james-rae** [comment]
> i bet that particular service is returning html that is corrupting the styles on that panel... 

- Mr Weech

**Comment by AleksueiR** [comment]
I doubt the identify html results are to blame since this is happening in the panel's header and not its body. It's the lengthy title that mashes the buttons into that weird smiley face. It works perfectly fine on Chrome because Chrome interprets `min-width: auto` on the buttons container as the current width of the container, preventing it from being shrunk down. IE doesn't seem to care about such details though.

Just add `flex-shrink: 0` to the `rv-header-controls` there to prevent the buttons from being squashed:
![](https://i.imgur.com/xQeDvAL.png)

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b4
Issue solved.
