### ISSUE TITLE
Opening of  index-fgp-fr.html causes "Object doesn't support property or method 'keys'" errors in console .

### ISSUE THREAD

**Issue by YaroRoodzit** [fgpv-vpgf/fgpv-vpgf#3606]
Tested build: v3.1.0-b2
Test URL: http://fgpv.cloudapp.net/demo/v3.1.0-b2/prod/samples/index-fgp-en.html
Browser: IE 
![image](https://user-images.githubusercontent.com/38046459/59775015-705a2000-927e-11e9-94e6-8e9517d8d1a4.png)

FYI
Chrome and Edge also get errors when opening /index-fgp-fr.html.
![image](https://user-images.githubusercontent.com/38046459/59775327-07bf7300-927f-11e9-9e27-bd0db8a4e353.png)

**Comment by ShrutiVellanki** [comment]
I get this error in IE without switching language.

**Comment by YaroRoodzit** [comment]
@ShrutiVellanki Yes . You are right. I will correct the title.

**Comment by yileifeng** [comment]
IE does not support `Map.prototype.keys`

**Comment by RyanCoulsonCA** [comment]
This will be fixed in the PR to fix #3611.

**Comment by RyanCoulsonCA** [comment]
Can confirm this error was showing up because of the same reason as https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3611. Checking again after [this PR](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3628) was merged, the problem no longer occurs.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b5
Same problem.
IE, Edge and Chrome still show a bunch of errors in the console.

**Comment by james-rae** [comment]
I can see errors for cross origin (e.g. `Access to XMLHttpRequest`) which are out of our control, an api depreciation error (which we trigger as a warning), and missing `backToCart` which is a known problem with our `prod` build (the `dev` build should have back to cart).

If QA is still seeing `Object doesn't support property or method 'keys'`, please let us know. This is the error the work on this issue was supposed to remove.

**Comment by YaroRoodzit** [comment]
Re-Tested build: v3.1.0-b5.
The error "Object doesn't support property or method 'keys'" is no longer displayed.
 Problem solved.
