### ISSUE TITLE
Details panel French apostrophe

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3627]
When we have a layer name with apostrophe, the layer name is not well formatted in the details panel.

If you use this layer: https://maps-cartes.ec.gc.ca/arcgis/rest/services/ICDE/MapServer/5

You will have this output:

<img width="394" alt="Screen Shot 2019-07-03 at 11 00 56 AM" src="https://user-images.githubusercontent.com/3472990/60602495-e6cc4700-9d81-11e9-927a-06f08fac9c35.png">

It use to work with version 2.5

**Comment by AleksueiR** [comment]
I could be wrong, but I came across a similar bug in SAR, and the single quote `'` was the culprit. 

First, there is a bunch of meta-characters which are [not allowed inside jQuery selectors](https://api.jquery.com/category/selectors/): ```!"#$%&'()*+,./:;<=>?@[\]^`{|}~```

Second, maybe that quote in `Qualité de l'eau aux sites de suivi` needs to be escaped since the name is wrapped in single quotes.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b7
Issue solved.
