### ISSUE TITLE
Legends not updated while clicking hide/show layers for Feature/Dynamic Layer

### ISSUE THREAD

**Issue by mpath** [fgpv-vpgf/fgpv-vpgf#3630]
Tested with: V3.1.0-b4

Noticed that when you click on Hide layers for the Feature/Dynamic layer, the layers are updated and hidden on map but individual legend still shows layer with check mark on. 

Steps to Reproduce:
1.	For Feature layer, go to http://fgpv.cloudapp.net/demo/v3.1.0-b4/prod/samples/index-fgp-en.html?keys=JOSM
2.	Click on hide layer to hide Oil Sands layer and notice that individual legends within Oil sands layer still appear with check mark on. In addition, when you uncheck few legends randomly, and try to uncheck and check Oil sands layer, it should have all legends updated on map. However, only legends with check mark on is updated on the map.
3.	For Dyanamic layer, go to http://fgpv.cloudapp.net/demo/v3.1.0-b4/prod/samples/index-fgp-en.html and import service: http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI_FGP_All_Layers/MapServer and select Nature layer while importing service.
4.	Click on Hide layer to hide  “Protected Areas, Canada, Large” layer and notice that individual legends within that layer still appear with check mark on

Screenshots: 
![B4 Issue_Feature_Hide Show layer](https://user-images.githubusercontent.com/46937257/60674099-53f5e000-9e47-11e9-880b-29ebdfb5e10b.JPG)

![B4 Issue_Dymamic layer_Hide Show layer](https://user-images.githubusercontent.com/46937257/60674132-6c65fa80-9e47-11e9-9511-4142e251d1e5.JPG)

**Comment by AleksueiR** [comment]
Historically, we treated legend and layers/layer groups separately, because internally they refer to two completely different things. When the layer itself is off, we don't really care about the state of legend items - they won't be visible anyway. However, I can see @mpath's point - to the user these are all just checkboxes which control the visibility of things on the map (users won't know or care how these things are different from each other).

To be consistent with out UI behaviour, I think we should adjust how the legend checkboxes are displayed based on whether their parent layer is on or off, the same way as with layer groups. We already preserve the state of the legend checkboxes, so no changes there are needed.

**Comment by YaroRoodzit** [comment]
Tested build: v3.1.0-b7
Issue solved.
