### ISSUE TITLE
Plugins samples are not building

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3678]
See http://fgpv-app.azureedge.net/?prefix=demo/tags/v3.1.0-b7/dev/samples/plugins/

previously we had no samples appearing in the `prod` build, now it appears to be affecting the `dev` builds as well

**Comment by james-rae** [comment]
https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3691

Fixes the samples on the `dev` builds. Still none on `prod` builds but sounds like there might be reasons™ for that

**Comment by milesap** [comment]
Samples on `dev` and `prod` should be fixed by #3691. Plugin samples will only be available when `@fgpv/rv-plugins` is pointing to an npm release.

http://fgpv-app.azureedge.net/demo/tags/v0.0-travis/dev/samples/plugins/areasOfInterest/samples/pics.html

http://fgpv-app.azureedge.net/demo/tags/v0.0-travis/prod/samples/plugins/areasOfInterest/samples/pics.html
