### ISSUE TITLE
Crosshairs helptext is cut off in windowed map view

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#3794]
When you trigger the identify crosshairs (focus on the map, use arrow keys), a helpful bit of text appears at the bottom of the map.  This looks fine in `index-samples` which is fullscreen map, but is cut off in `index-fgp-en`. 

First check if the cutoff is a CSS problem in the `index-fgp-en` page itself.  If so, attempt to correct the sample.

If it's a problem with RAMP core code/css, then will need to fix

**Comment by AleksueiR** [comment]
`index-samples`
![](https://i.imgur.com/r2a0JmH.png)

`index-fgp-en`
![](https://i.imgur.com/6LYOFlk.png)

The problem is on the sample page, not in RAMP:
https://github.com/fgpv-vpgf/fgpv-vpgf/blob/fbad05fe85ba9d737c39ef37f49912c0dd91956e/packages/ramp-core/src/content/samples/index-fgp-en.tpl#L23

Replace margin with `10px -8px -8px -8px;` to fix.
