### ISSUE TITLE
WMS layer legend not showing

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#3912]
There is a bug with some WMS service and legend.

When we try to load this service
GetCap: https://maps.geogratis.gc.ca/wms/hydro_network_en?service=wms&version=1.3.0&request=get[…]ro_network&legend_format=image/png&feature_info_type=text/
Catalog: https://gcgeo.gc.ca/geonetwork/metadata/eng/a4b190fe-e090-4e6d-881e-b87956c07977
I have no legend... The GetLegendGrpahic is not trigger

Doing it manually it works
https://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=Get[…]n=1.1.0&layer=hydro_network&format=image/png&STYLE=default

This WMS has 3 levels, the first one hydro_network does not return the legend but the second group level nhn:nhn does.

The same thing happen when we load manually

Layer GOV Canada …. Master group layer with name hydro_network
Second layer is National hydro network… Master group for hydro with name nhn:nhn
![a1](https://user-images.githubusercontent.com/3472990/119718332-6ca18180-be35-11eb-87a4-4325196bbe55.png)

The first layer doesn't have the legend, the second yes
![a2](https://user-images.githubusercontent.com/3472990/119718416-89d65000-be35-11eb-9565-a1a29d3f8d14.png)

The legend for the first group should be
![a3](https://user-images.githubusercontent.com/3472990/119718504-a83c4b80-be35-11eb-8cf4-ba7d82c764b5.png)

**Comment by elsa-huang** [comment]
RAMP gets the legend graphic from a URL provided by the XML. As far as I can tell, the reason the legend is not loading in this case is because the URL isn't present in the [XML](https://maps.geogratis.gc.ca/wms/hydro_network_en?service=wms&version=1.3.0&request=getcapabilities&legend_format=image/png&feature_info_type=text/). 

For the second layer (National Hydro Network), the XML contains the following lines:
```xml    
<Style>
    <Name>default</Name>
    <Title>default</Title>
    <LegendURL width="243" height="257">
        <Format>image/png</Format>
        <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=nhn:nhn&format=image/png&STYLE=default"/>
    </LegendURL>
</Style>
```
As we can see, a [URL ](http://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=nhn:nhn&format=image/png&STYLE=default)to the legend graphic is provided.

However the first layer (GOV Canada) doesn't have this. As a result, RAMP finds nothing when it tries to load the legend graphic.

As pointed out above though, a [URL](https://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=hydro_network&format=image/png&STYLE=default) to the legend graphic for that layer does actually exist, and it would work if it was in the XML, or if RAMP could somehow build the URL itself. Not sure if this is something we realistically can or want to try to do though.

**Comment by jolevesq** [comment]
@dan-bowerman This layer also have a weird return from the getFeatureInfo. It ask for a DATA parameter.

![image](https://user-images.githubusercontent.com/3472990/124476521-eb60d700-dd70-11eb-9665-bf413331e5e6.png)

**Comment by dan-bowerman** [comment]
@jolevesq Hi Johann, after quite a bit of review on this, we've determined that these are largely problems with the source service and not something we should be modifying the RAMP core to accommodate. I strongly suggest getting in touch with the data provider to align their service with how WMS should be expected to perform. 3.3.4 will be coming next week, but there will not be anything in that update that will address this issue.

**Comment by prosperva** [comment]
> RAMP gets the legend graphic from a URL provided by the XML. As far as I can tell, the reason the legend is not loading in this case is because the URL isn't present in the [XML](https://maps.geogratis.gc.ca/wms/hydro_network_en?service=wms&version=1.3.0&request=getcapabilities&legend_format=image/png&feature_info_type=text/).
> 
> For the second layer (National Hydro Network), the XML contains the following lines:
> 
> ```
> <Style>
>     <Name>default</Name>
>     <Title>default</Title>
>     <LegendURL width="243" height="257">
>         <Format>image/png</Format>
>         <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=nhn:nhn&format=image/png&STYLE=default"/>
>     </LegendURL>
> </Style>
> ```
> 
> As we can see, a [URL ](http://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=nhn:nhn&format=image/png&STYLE=default)to the legend graphic is provided.
> 
> However the first layer (GOV Canada) doesn't have this. As a result, RAMP finds nothing when it tries to load the legend graphic.
> 
> As pointed out above though, a [URL](https://maps.geogratis.gc.ca/wms/hydro_network_en?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=hydro_network&format=image/png&STYLE=default) to the legend graphic for that layer does actually exist, and it would work if it was in the XML, or if RAMP could somehow build the URL itself. Not sure if this is something we realistically can or want to try to do though.

**Is there a way to add the legendUrl in the RAMP config file?**
