### ISSUE TITLE
ESRI dynamic sub layer remove button

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpv-vpgf#4011]
When we add esriDynamic with sublayers, once added to legend by the loadRcsLayers functions, every items (group and sub layers) has the remove button enable.

For some group layers, if not all of them it would be useful to remove the remove button from the sub layer so it can't be remove because the group layer is kind of a whole.

Adding a parameter to the loadRcsLayers to achieve this would be a nice addition

**Comment by james-rae** [comment]
An alternate idea that occurred to me just now. Rather than a parameter on the `loadRcsLayers`, maybe creating a global flag in the main app config file would be easier. If turned on, **any** dynamic "tree" type layer in the legend would have the Remove icons stripped from the child tree entries. This lets us avoid having an extra param for one edge case.

The question is would this suffice? It feels to me like this would be a site-wide desired behavior.  If the need is for some trees to have child-delete and others not to, then this doesn't work.

**Comment by james-rae** [comment]
Global config flag `ui.legend.sublayerRemovable` was implemented
