### ISSUE TITLE
Export feature is broken in v3.3.5

### ISSUE THREAD

**Issue by prosperva** [fgpv-vpgf/fgpv-vpgf#4064]
When trying to download a map through the Export feature, the download button is not working. Console show the following error:

<img width="528" alt="Screen Shot 2022-10-26 at 11 25 09 AM" src="https://user-images.githubusercontent.com/1531271/198094681-d3d03ec5-3d64-4185-a3d2-f97bc86a4614.png">

**Comment by james-rae** [comment]
I don't have a `v3.3.5` site handy, but things appear to be working in `v3.3.6`. 

That said, I'm a bit surprised at the error since `RV` gets defined in the [startup routines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/packages/ramp-core/src/app/global-registry.js#L13). Is it possible you are embedding in an iFrame or something like that? Alternately you could attempt to insert a knucklehead script on your page that does 
```text
window.RV = {};
```

I'll also open a new issue, since the thing in the export that is exploding seems to be not implemented as well.

**Comment by prosperva** [comment]
@james-rae

**Comment by prosperva** [comment]
Thanks @james-rae. I upgraded to v3.3.6 and it worked.
