### ISSUE TITLE
map layer checkbox event

### ISSUE THREAD

**Issue by prosperva** [fgpv-vpgf/fgpv-vpgf#4073]
Does RAMP have layer checkbox event when a user toggles on and off a layer? I have tried this, but it only works when you click on the whole row and not the checkbox beside the layer name:

```
RAMP.mapById('rv-app-0').layers.click.subscribe(function(e){
  console.log(e);
});
```

**Comment by james-rae** [comment]
I don't think there is a "global" event that raises for any layer.

You would need to watch observables on each individual layer. Also, this will trigger if anything changes the visibility; not just mouse clicks on legend checkbox toggles.

e.g.

```text
var myLayer = RAMP.mapById('rv-app-0').layers.allLayers[0];
myLayer.visibilityChanged.subscribe(e => {
  console.log('I am visible? : ' + e); // e is boolean
});
```

You can use the `MapAPI.layers.layerAdded` observable if you need to watch for new layers coming in (to add listeners to their observable).

**Comment by prosperva** [comment]
Thanks. Is there a way to check when `RAMP` has been added to the DOM?

**Comment by james-rae** [comment]
`RAMP.mapAdded.subscribe(map => { do stuff })` but to be honest I rarely use this and am not sure how the timing works. If a map is generated in the page lifetime it should show up on this observable. For maps that are hard-defined in the DOM (e.g. a div with `is="rv-map"`), I'm not sure...it might exist before that observable.  Might need to test it on your end, but I would hope it fires lol.  If not you can check the `.mapInstances` array for pre-existing maps before listening.

**Comment by prosperva** [comment]
I came up with this solution but it is firing before RAMP has been added to the DOM

```
function remove(arr, value) {
    return arr.filter(function (ele) {
      return ele != value;
    });
  }

  $(".rv-list-item-controls").click(function (checkbox) {
    let selectedLayers = [];
    RAMP.mapById("rv-app-0").layers.allLayers.forEach(function (e) {
      if (e.visibility) {
        selectedLayers.push(e.id);
      } else {
        remove(selectedLayers, e.id);
      }
    });
    localStorage.setItem("selectedLayers", selectedLayers);
  });

  if (localStorage.getItem("selectedLayers") != null) {
    let loadLayers = localStorage.getItem("selectedLayers").split(",");
    if (typeof loadLayers != "undefined" && loadLayers.length > 0) {
      loadLayers.forEach(function (e) {
        RAMP.mapById("rv-app-0").layers.getLayersById(e)[0].visibility = true;
      });
    }
  }
```

**Comment by james-rae** [comment]
I have very little context in what you're trying to do, but am guessing the bottom part 

> `RAMP.mapById("rv-app-0").layers.getLayersById(e)[0].visibility = true;`

runs too early. Is this script running before the ramp script? If so, put it after. If it's already after, you may need to do some waiting until your instance appears.  I.e. waiting for the instance, and possibly waiting for layers.  I don't know how your site starts up or the requirements so you'll need to do what works for you. I love `setTimeouts` for glorious busywait hacks.

Alternately, if your setup can work with it, you could consider trying to leverage the bookmarking module.

See this [sample page](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/gh-pages/develop/samples/index-fgp-en.html)
- [This line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/gh-pages/develop/samples/index-fgp-en.html#L455), notice  `data-rv-wait="true"` is set. This does a block to allow any potential bookmark to be consumed before finishing the load.
- [This line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/gh-pages/develop/samples/index-fgp-en.html#L584) shows how to set a bookmark (you would have stored it in your local storage). Notice it uses the "legacy API" `RV`, you'll need the [legacy script](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/gh-pages/develop/samples/index-fgp-en.html#L535) if you're not already using it. Also note if you had nothing in your local storage, you'd need to call this with empty parameter to unblock the instance.
- [This line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/gh-pages/develop/samples/index-fgp-en.html#L600) shows how to grab a bookmark of the current state. So whenever you want to save your state, you'd do this and put in local storage instead of the `document` call this sample does.

The bookmark will track visibility, opacity, map extent, etc. So might not be what you want.
The sample page here isn't great since has no layers but you could add a dummy layer for local testing if you wanted (corresponding config is [here](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/gh-pages/develop/samples/config.rcs.en-CA.json))

Might be more trouble than it's worth, up to you.

**Comment by james-rae** [comment]
Also it only works with layers that are in your config file. If you have random layers getting dropped in via API calls, don't bother with the bookmark module

**Comment by prosperva** [comment]
I ended up manipulating the config file using some custom code and it worked. The project I am on uses React so it adds some complexity. Thanks for your guidance
