### ISSUE TITLE
Identify Stacked Results Tolerance

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#419]
Handle tolerance on hybrid identify clicks.

**Comment by james-rae** [comment]
[Developer Wiki Article](https://github.com/fgpv-vpgf/fgpv-vpgf/wiki/Map-Identify#feature-layer-click-vs-spatial-query) with overview on current implementation, pros and cons, and high-level idea for hybrid solution

**Comment by james-rae** [comment]
Not touched week Mar 21-25

**Comment by james-rae** [comment]
Not touched week Mar 28-Apr 1

**Comment by mweech** [comment]
This was discussed in more detail during the workshop.  Original issue body needs to be beefed up a bit for further planning.

**Comment by james-rae** [comment]
Wiki article was bulldozed. Reproducing it here.

When a user clicks a map, we can have one of two behaviors happen: 

* Details of the top-most item under the mouse is displayed (a.k.a. Top-most Identify)
* Details of all items under the mouse are displayed (a.k.a. Drill-through Identify)

Things to consider in the implementation:

* The map click event and the feature layer click event are triggered at the same time.
* Feature layer click events will only trigger on the top-most feature of a stack of features.
* Image based layers (e.g. Dynamic Map Service, WMS) currently must always be below feature layers.  However, in ESRI JS API 4, layer types will be allowed to mix in the map stack.
* File-based layers cannot utilze the ArcGIS Server identify task

## Drill-through Identify

The main trick in achieving this is to determine a full set of Feature Layer features under the mouse (as the click event only gives the top-most). Adding additional hassle is synchronizing the feature and map click events with populating the results pane.  When do you clear the previous click results from the pane? When do you stop the loading animations?

To get around these obstacles, the click events on feature layers will not be set. When the map click occurs, the following steps take place:

* Clear the identify results pane
* Trigger the ArcGIS Server [Identify task](https://developers.arcgis.com/javascript/jsapi/identifytask-amd.html) for visible Dynamic Map Service layers. Add results to the pane as they return asynchronously.
* Perform a [Spatial Query](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#queryfeatures) on each visible Feature Layer for the point click.  This will execute locally when possible. Add results to the pane as they return asynchronously.

As part of their config structure, each layer should have an identify tolerance to help make the mouse click match symbology sizes instead of actual geometries (i.e. the user needs to click the square around the point, not the exact middle of the square).


## Top-most Identify

This will be implemented later, and will be a configurable option.  Again, only the map click handler is enabled. The main steps will be:

* Clear the identify results pane
* Iterate through each visible layer, starting with the top-most one
* Perform an Identify or Spatial Query on the layer, depending on the layer type
* If a result is found, add it to the results pane and break the iteration.

An alternate approach, which involves adding click handlers to the feature layer.  The approach is more convoluted, but has the advantage of utilizing the feature click event first, which will save on spatial queries and server-side identify calls.  The basic idea is:

* Clear the identify results pane
* In the map click, delay the logic to allow for any possible feature clicks [NASTY!]
* If a feature click is registered, check if the clicked layer is above all non-feature layers.
* If it is above, add the result and exit.
* If it is not above, run Identify on each Dynamic layer above it. If any of these return a hit, add the hit to the result and exit.
* If no Dynamic hits, add the feature result to the results pane and exit.
* If no feature clicks happen in the determined time, continue processing Dynamic layers in view order and show the first hit

## Feature Layer Click vs Spatial Query

One of the main advantages of using the click event on a feature layer is that the entire feature symbology is interactive.  This is especially relevant for point features, which often have symbology that is much larger than the actual map point. As an example, if a point layer uses large stars for symbology, if a user clicks the tip of a star, they will expect the feature to be selected.  If they click in the gap betwen two tips of the star, the feature should not select.  The click event will achieve this.

Spatial queries, on the other hand, are not as flexible.  They work on geometries in map co-ordinates, not symbologies.  So when clicking on a point layer, the mouse click is represented as a single point map point, and the point is also a single point (regardless of symbology).  A successful intersection between the two points can be tricky, especially at Canada-wide zoom levels.  The query has a tolerance parameter to help, but this can get messy with oddly shaped point symbols.  Using the star example above, a low tolerance would mean clicks on the star tips would not register.  A high tolerance would mean clicking the gap between to tips would be a successful hit.

The advantage of spatial queries is that they do not care about overlapping features, whereas an SVG shape will block the click event on another shape that is underneath it.

## Hybrid Approach

This is still in the big-fluffy-idea state of design, but it may be possible to have both feature layer clicks work in combination with our Drill-through identify approach, for the sole reason of ensuring that regardless of the drill-through, if a user clicks on a feature it will be selected.  The primary issue with this approach is synchronizing the map click and feature click events, and having the detail panel correctly populate & refresh against those two separate events.

**Comment by mweech** [comment]
#2598 has consumed the life force of #419 and will live on...
