### ISSUE TITLE
Anchor/OnHover Tooltips Design and PoC

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#424]
For layer features, provide OnHover tooltips (client side layers only) as well as Anchor tooltips.

- [x] Look at RAMP Maptip Code
- [x] Look at Hovertip for grid-embedded buttons
- [x] Design method for putting angular tooltip on non-angular element (or alternative)
- [x] Design how to handle hovertips for Dynamic content
- [ ] Design how detail panel (which is a list) relates to a single anchortip

**Comment by mweech** [comment]
- make angular element that can have tooltip triggered via property instead of events (which is the normal way)
- position element over center of geometry to align tooltip (I believe RAMP has code that can be borrowed to do part of this)
- logic for show/hide of anchor tip (on feature select, on feature de-select [many cases])
- handler to move anchor tips when map is panned

**Comment by james-rae** [comment]
# RAMP Behavior

Unlike fgpv, RAMP did not use dynamic layers, nor did it use AngularJS.  To do maptips, we would

* Use [tooltipster](https://github.com/RAMP-PCAR/tooltipster#rampfix) library to manage the physical tip
* Use [snap](http://snapsvg.io/) library to position the tip relative to the map feature
* Use ESRI's [feature layer events](https://developers.arcgis.com/javascript/3/jsapi/featurelayer-amd.html#event-mouse-out) to detect mouse over on features

WMS Layers did not have any type of maptip support

# Hovertips on Dynamic Layers

By design, Dynamic Layers do not pull feature geometry to the client.  This means there is no client-side-only event to determine if the pointer is over a feature contained in a dynamic layer.

## Option 1A - No Hovertips for Dynamic Layers

PROS

* Easy
* Lazy

CONS 

* Reduced user experience - more effort to identify a feature on the map. 
* Can give the appearance of broken when hovertips are showing on one layer and not another.

## Option 1B - Polling on Mouse Move

When the mouse moves, ask the server what is under the new mouse position

PROS 

* Will allow user quick view of on-map features.
* Consistent with Feature Layers

CONS

* Increased network traffic.  
* Slower response times for maptip to appear.
* Difficult to tell top-most feature from identify result - maptip may be for something currently obscured.
* Buffer-size descrepancies on odd-shaped point symbols can give confusing or frustrating results.  
* Can conflict with mouse-over handlers of feature layers - can result in two hovertips appearing.

Variant: Figure out how to only poll when mouse stops moving for a small amount of time.  This may reduce the network load.

# Creating a Physical Maptip

We need something on the website to display the maptip.

## Option 2A - Use Tooltipster

Since we are using AngularJS, I am going to assume this is the wrong idea. Please comment if tooltipster is in fact a good choice.

## Option 2B - Use Angular Tooltip Tag

Doesn't appear to be a way to make it stick (for anchor tips), plus we would need ability to have two open at once (anchor + hover). Seems like a bad approach.

## Option 2C - Custom Angular Tip

Involves making a UI element specifically for displaying maptips. As a non-angular person, first thought would be stealing code for the `appbar` and stripping it down to something more lightweight.

PROS 

* Can make it look and behave to our exact specifications
* Remains in AngularJS world

CONS

* Most work involved, will require UI developer input.

# Positioning the Maptip

We need to know where to put our tip. In RAMP, we used the top center of the bounding box surrounding the feature.

## Option 3A - Use SNAP Library

Snap library provides the means to calculate the bounding box of an SVG item.

PROS 

* Work is done by the library.  We make one API call.

CONS

* Does it make sense to use SNAP in AngularJS?
* Requires SVG. Which means creating an SVG item for Dynamic Layer feature we are maptipping.
  * Most advantageous approach would be to implement a highlight layer to host the SVG.
    * Done in both RAMP and GCViz
	* Also gives us highlighting
	* Increases scope of work for the task

## Option 3B - Use Alternate Library or AngularJS Techniques

Feel free to make suggestions. Remember, the map is a DOJO construct, not an AngularJS one.

## Option 3C - Custom Algorithm to Calculate Position

Feels like re-inventing the wheel when there are libraries available.

# Maptip Event Triggers

## Anchortip Show

Should be triggered on a detail select. This can come from clicking on a result after an identify has happened, or when the details button in the grid is clicked.  When an anchor tip is shown, it should close or commandeer any existing anchor tip (i.e. only one anchor tip visible at a time).

**Discussion:** the details panel for identify is a long list of items for individual layers. There is currently no good way to select an active item

* Add a button to "show on map", triggering the anchor tip
* Default to the first item and not care
* Calculate the top-most in view, apply tip to that one. Update as user scrolls.
* Mouse-over in detail pane to select
* Something better?

## Anchortip Hide

Hide the tip when user clicks the `X` button on the anchortip, or when they close the detail pane.

## Reposition Anchortip

Add handler to the map's `extent-change` event to reposition the tip if it exists

## Hovertip Show and Hide

Depends on decision made for how we deal with Dynamic Layer.  If we take the easy option, will continue to utilize the `mouse-over` and `mouse-out` events of the layers.

# Maptip Content

* Grab icon using same methods we use now for grid -- `geoService.retrieveSymbol`
* Use name field for text content. We currently don't have a display field defined in our config schema (see `FIXME` in `indentifyService.getFeatureName`).  
  * Option: Make a task to add that (may also impact RCS?).  Extra work. 
  * Option: Temporarily have object id display until time to fix name field, same as identify function.
  * Once name field is being used, `getFetaureName` should be moved to somewhere easily accessible for all geo modules.  Possibly a new feature module containing all the feature specific functions.

**Comment by james-rae** [comment]
Results of design discussion on above proposal.

# Hovertips

At this point, we will not implement any type of hover-based function for any layers

# Creating a Physical Maptip

At this point, we will not implement a traditional maptip (i.e. a box that floats above the target point).  Instead, we will implement a highlight layer for the focused point.  As the feature details window will be open, all relevant information on the highlighted point is already available, thus making the information in the traditional maptip redundant.  We will use the same technique RAMP uses to produce the highlight.

We will also implement a graphic marker (i.e. a pin) to indicate the location the user clicked.

For Dynamic Layers, we will grab the geometry of the individual feature and use that in the highlight layer.

# Event Triggers

## Highlight Show

Should be triggered on a detail select. This can come from clicking on a result after an identify has happened, or when the details button in the grid is clicked.  Only one feature should be highlighted at a time.

A button will be added to each individual feature in the details panel.  Clicking the button will trigger the highlight for that feature on the map

## Highlight Hide

Remove the highlight when the details panel is closed.

## Reposition Highlight

As it is a graphic layer, will follow the map for freeeee.

## Future Enhancements

* Some type of visual cue from the detail panel to the highlighted feature.  Suggested was a line, similar to location pictures on google maps.
* Cache the geometry for dynamic layers, so we don't have to load a given feature's points more than once.

**Comment by AleksueiR** [comment]
## Notes from UX review:

### Datagird
 - this is no explicit `highlight` button
 - item is highlighted when the `zoomto` button is clicked
 - item is highlighted on datatable row select event

### Details Panel [needs mockup]
 - if there are more than say three hits, hit sections are collapsed (only the feature name and it's primary/OBJECTID field is displayed)
 - clicking on the collapsed section expands it and highlights the corresponding feature on the map

### Enhancements [needs mockups]
- on identify, all hits are highlighted for a selected layer (in mini selector inside the details panel)
  - when switching layers, highlights change to hits from that layer 
  - highlighted features can have hover tooltips since their geometry is already downloaded;
