### ISSUE TITLE
Notify host page when global RV is ready

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#502]
When the fgpv framework loads up, it adds a global object `RV` to the host page window. This object is used by the host page to further communicate with fgpv instances (for example, language switch, passing URL parameters).

There needs to be some type of notification that the host page can use to determine when the `RV` object is available.

An attempt to use the document event `DOMContentLoaded` did not work, the event fires prior to the creation of `RV`. 

Suggestion (untested): 

Add `global-registry` file to `injector` and not the `core`, so the `RV` global will be created as soon as `injector` executes and then you can do this:

```
RV.appRegistry[appId].then(app => 
    app.loadRcsLayers(keys)
);
```

Further background information:

The way our scripts are injected now is after the last script tag. In this case core.js and friends would end up after the small key snippet.

**Comment by spencerwahl** [comment]
I don't think the suggestion will work; we not only have to wait for `global-registry`, we also need to wait for the core run block (in `core.run.js`). Before that run block the app doesn't exist in the `appRegistry`, promise or otherwise, which means we'll still get an error.

We could get around this by waiting on the `appRegistry` but we don't have a great way of turning it into a promise. We don't know how many apps we should be waiting for and if we only wait for a certain amount it's possible we get every app but the one we need.

More bad news; we can't run `core.run` earlier since its tied to angular.

**Comment by AleksueiR** [comment]
The idea is to wait async until map instances are ready and keeping a queue of possible calls from the host page, keeping at the same time a simple synchronous looking external API.

Here is the gist [e33b0e214585af4de856201257a11fe2](https://gist.github.com/AleksueiR/e33b0e214585af4de856201257a11fe2).

With that, call to load rcs keys will be something like this:
```js
RV.getMap(mapId).addRcsLayer(keys);
```

**Comment by spencerwahl** [comment]
PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/530
