### ISSUE TITLE
Support custom fill polygon in renderer-to-legend

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#524]
Our current approach for legend images is to use data URLs, either provided from ArcGIS Server as base64 images, or as SVG images made to mimic standard ESRI symbols.

Certain types of symbols, namely Simple Fills (polygons) with a hash-line fill, or a Picture Fill ( a polygon with a custom image tiled inside it) do not work with embedded SVG in data urls.  SVG uses an `xlink` attribute to link to the fill image; these links are not supported in data urls (see [In Conclusion section at bottom of this page](http://dbushell.com/2015/01/30/use-svg-part-2/)).

This affects both the images shown in the legend, as well as any icon shown beside a feature (e.g. grid row, detail pane, maptip).

Possible solutions

* Through either tagging during legend info generation, or deriving at runtime, if we detect this case, we adjust the template holding the image to be an SVG element instead of an Image element.  Will allow the `x-link` to work. May be a problem for injected image in datagrid
* Through either tagging during legend info generation, or deriving at runtime, if we detect this case, we draw the polygon border using our regular technique, and utilize CSS to place the fill image in the middle (in reality, behind it, and the polygon is transparent). May be a problem for injected image in datagrid.
* Make a hidden canvas. Draw the border and image on the canvas. Export the canvas as base64, use that in the data url.  Possible cross-domain issues if the fill images are on unfriendly servers

**Comment by james-rae** [comment]
Brief update: tried using svg `image` element but also failed, again due to `xlink`

**Comment by AleksueiR** [comment]
All legend image types except text symbols (James says he never saw such a legend) are supported now.

Instead of being converted into datauri strings and rendered as images, symbology items are represented as plain SVG objects. 
Changes:
- Picture Marker Symbol - images provided by the server are inserted into an SVG container and scaled to fit accordingly; supports datauri string as wells as regular urls;
- Picture Fill Symbols - ESRI standard fill types are implemented in SVG instead of using image assets for tiling; 
- Simple Marker Symbol - now scaled to fit;
