### ISSUE TITLE
Initial layer order does not reflect layer order in the map stack

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#592]
Layers are added to the legend in the order they appear in the config (thanks to legend placeholders); however, this doesn't exactly reflect the order of the map stack (there are two of them - one for feature layers: `graphicsLayerIds`; and one for everything else: layerIds; thanks James for elucidating this point). 

This makes it difficult to tell if the layer reordering is working correctly and it might appear entirely broken to the user. See #272.

**Comment by james-rae** [comment]
I think I might see part of the problem here.  When a layer is [added to the map](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L246) it is passing in an index from the legend position.  What I think it should be doing is using Aly's logic to [derive insertion position](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/develop/src/app/geo/layer-registry.service.js#L129).   If the layers are initially added in the correct order, then re-orders should always put them in the correct spot if using the logic.

@alyec can you verify my assumptions?

**Comment by AleksueiR** [comment]
Yes, this seems to be the problem. Aly's reorder function needed placeholders to work first, and I also had to change it a bit to get the reorder to work.
Is it fair to say that this issue blocks #272? Can we pull it in the sprint? I can do this one since I'm already working on layer reordering anyway.
