### ISSUE TITLE
WMS identify clicks are offset in WET pages

### ISSUE THREAD

**Issue by alyec** [fgpv-vpgf/fgpv-vpgf#623]
It appears that WMS clicks are offset to the left when using pages within the WET template.
![2016-05-18 09_15_06-fgp](https://cloud.githubusercontent.com/assets/7646414/15359876/4eb3eef4-1cd9-11e6-8b37-ba79e278f0d9.png)

**Comment by jolevesq** [comment]
![screen shot 2016-05-18 at 3 14 02 pm](https://cloud.githubusercontent.com/assets/3472990/15371837/7aac5d34-1d0b-11e6-8f09-1dba608f866d.png)

There is a shift between the click event and the map. Not only on the identify tool but in the zoom in by extent as well. We use to have this in GCViz when we modify the map size. We had to do a map.refresh to reinitialize the map with his container. We also had the problem with the shift on the map and it was because of css class use by WET. I will investigate both options.

**Comment by jolevesq** [comment]
It was because of css. If I remove the padding on container it solves the problem. WET does not use prefix for their CSS classes. It cause a lot of problems.
.container {
    margin-right: auto;
    margin-left: auto;
    /* padding-left: 15px; */
    /* padding-right: 15px; */
}

**Comment by AleksueiR** [comment]
Yeap, we had the same exact problem with RAMP, only then padding was 10px, not 15px :smile:
I suggest adding an override to our vendor's style folder.
Create a file name `_wet.scss` in `src/content/styles/vendor` with the following:
``` scss
@mixin wet {
    .container {
        padding: 0;
        margin: 0;
    }
}
```
And then add  `@import "_wet.scss"; @include wet;` to the `_all.scss` in the same folder.

We keep all third-party overrides in there to prevent collisions like this or to just re-style something. Everything from this folder (except for `_special.scss`) is wrapped in `.fgpv` class limiting overrides to the app container node. (`_special.scss` is for overriding styles outside the app container.)
