### ISSUE TITLE
Point Information panel always shows results for topmost layer

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#645]
Mini-layer selector should initially select one of the layers that has results instead of defaulting to the topmost layer every time.

![](https://cloud.githubusercontent.com/assets/7583387/15429149/85d81eba-1e6d-11e6-8679-ac63dbfadab5.PNG)

**Comment by AleksueiR** [comment]
Required behaviour:
- when the details panel opens the first time, the topmost item in the mini-legend with hits is selected;
- if the user switches to a different item in the, this item is considered to be __pinned__;
- the pinned item will stay selected when it has no hits (on subsequent panel refreshes when the user continues to query the map)
- the pinned item is reset when the details panel is closed;

**Comment by jolevesq** [comment]
@mweech I will do it at the same as #643 and send both off them together.

**Comment by jolevesq** [comment]
@AleksueiR even if there is data for the selected layer it wont work because data array for the selectedItem is not set. If I put a timeout like this below it works because the data array is now initialize. I don't think timeout is the best way to do it. Do you have some suggestions? Thanks

```
$scope.$watch('self.display.data', newValue => {
            // console.log('self.display.data', newValue);
            // if multiple points added to the details panel ...
            if (newValue && newValue.length > 0) {
                // pick first point to be selected initially
                setTimeout(function() {self.selectedItem = newValue[self.selectedIndex];}, 1000);
            } else {
                self.selectedItem = null;
            }
        });
```

**Comment by AleksueiR** [comment]
@mweech @jolevesq 
Ouch, we can't select the first with hits because results are loaded asynchronously, and until all results are loaded, it's not possible to tell which one is the topmost this hits (unless it's the first one). 

One solution would be to select the first one initially, and then select the topmost with hits after all results are loaded.
Another solution would be not select anything initially, and then select the topmost with hits after all results are loaded.

Both of these solutions will make an arbitrary and unexpected (to the user) change to the selector.

I suggest to keeping the original behaviour (selection to topmost by default as we can't tell which item will have hits), with addition of the pinned item as described above.

**Comment by mweech** [comment]
@AleksueiR thats a fair trade off at this point.  pinning the selection will address a good portion of the issue initially and we can reassess following more feedback.

**Comment by jolevesq** [comment]
@AleksueiR I made it to save the index. Even if the panel is close the index is save for the next time. This way the user set it once and it stays even when the panel is close. I think it will better for the user. If you prefer to reinitialize, let me know.

**Comment by AleksueiR** [comment]
I don't think we should store the index of the pinned item; we should store the item's name or id. Say we have this mini selector:
```
0: layer 0
1: layer 1 [x]
2: layer 2
3: layer 3
```
User pins `layer 1`, and then - without closing details panel - toggles off `layer 0` or zooms out of `layer 0`'s scale and triggers identify again:
```
0: layer 1
1: layer 2 [x]
2: layer 3
```
Since we stored the index (`1`), `layer 2` is now pinned, which is not what's expected.

Also, I think the pinned item should be reset after panel is closed as the next time the panel is opened, the pinned item might not be present in the panel (as in the above example) and it will have to be reset anyway.

**Comment by jolevesq** [comment]
Already started to use id (name and caption) because of what you say. I will reset after panel close.
