### ISSUE TITLE
Data table does not load consistenly after re-establishing network connection

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#685]
Tested on http://fgpv.cloudapp.net/demo/develop/index-fgp-en.html

Tested item :Add error message to datatable if attribute fail to load #564

Browser : Chrome

**Steps to Reproduce**

1. Load FGP site
2. Select Legend
3. Click on a layer to load data table
4. Disable network
5. Select the layer again (A blank grid with error message appears)
6. Restore connectivity
7. Select the layer (Blank data grid loads)
8. Seems once a blank grid loads it is not possible to load data again 

Please investigate

![image](https://cloud.githubusercontent.com/assets/18539315/15653760/eaa35ebc-265c-11e6-8cdf-0ffc792e8e21.png)

I also notice that error message remains on the screen for other layers even when data is loaded

![image](https://cloud.githubusercontent.com/assets/18539315/15654104/699873e0-265f-11e6-9384-272a6bee39b0.png)

**Comment by mweech** [comment]
a bit more complexity:

- when running through the steps i was able to successfully view the airport layers datagrid after disconnecting network although with the error message present.  on subsequent attempt after network is reconnected the grid loads with no issues.
- i can confirm that once a data table fails to load, it is permanently failing
- if a toast message appears for a particular datagrid, it will persist until user selects "CLOSE" even if successfully selecting and viewing another layers datagrid.

**Comment by cynngah** [comment]
Datagrid can now load properly given a re-established network connection.
Toast message will also disappear when the datagrid is loaded properly

However, one edge case remains when you load multiple consecutive datagrids without network connection. Because you cannot detect which datagrid a toast belongs to, it will remove the message every second datagrid given none of these grids have had their formatted attributes loaded already.

**Comment by AleksueiR** [comment]
Should the app try to redownload failed attributes every time the datatable is opened or should the user trigger it by clicking a button?
