### ISSUE TITLE
Tile layers can obscure other layers

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#699]
When Tile Layers are added to the viewer, they obscure all layers below them.  A user may be unaware that there are layers obscured by the tile layer.  To address this the viewer should:
- preferentially  add tile layers to the bottom of the stack of layers.  
- occurs when using both the User Added Layers control and on load via an RCS call
- structured config should be able to override this behaviour.

**Comment by mweech** [comment]
:point_up: [May 31, 2016 3:42 PM](https://gitter.im/fgpv-vpgf?at=574de918f44fde236e522526)
> James Rae @james-rae May 31 15:42
Suggestion from QA Testers on our initial map settings: the tile layer in the TOC (which is a basemap) covers all layers below it, giving the initial impression that there is nothing there. If we can set the initial opacity of the tile layer to something around 50% it makes it more apparent that it is just a regular layer.

> Mike Weech @mweech 08:23
 agree...
would also recommend u switch to the Hillshade layer as a tile layer.. as with that initial opacity its much more appropriate usage wise

> Aleksuei Riabtsev @AleksueiR 09:34
 what if we move that baselayer to the bottom of the layer list?

> James Rae @james-rae 09:35
it still gives the appearance of layers turning off if they are re-ordered below the tile

> Johann Levesque @jolevesq 09:36
Maybe tile layer should not be mixed with other layer and always stay at the bottom (not moveable)?

> Aleksuei Riabtsev @AleksueiR 09:37
right, agree, set it to 50% and change to Hillshade as Mike suggested (or change the default basemap), so that layer stands out; still think it's a good idea to move it to the bottom - even at 50% opacity, it will partially obscure icons and other features.

> James Rae @james-rae 09:37
note this suggestion is only to help not confuse the testers. i think for normal GIS users, the existing functions and behaviors are good.

> Johann Levesque @jolevesq 09:38
If it confuse the tester, I think it will confuse the user as well because most of them are not GIS users

> James Rae @james-rae 09:42
yeah, its a bit of a funny situation...i'm not really sure where I stand
i don't want to lose the ability to re-order a tile...that is useful
mostly confusing if tile is an actual basemap...would think most use-cases, it's more of an overlay tile (as we already have basemaps)
for the immediate demo page, I'm indifferent where we order the layer...opacity will be the quick fix
for non-gis users who manually add a basemap as layer (willingly or accident), yes it could be confusing. I don't have a great answer, something we can discuss or make a discussion issue for?

> Mike Weech @mweech 10:00
i would say things are working as intended.. however that adding an entire basemap as a tile layer would be considered non-typical usage scenario
the most i could see is trying to constrain tile layers to the bottom, and maybe by default we stick them at the bottom
but the user should have the ability to put them in any order they please

> James Rae @james-rae 10:02
modding the "add layer" to put tile types at the bottom rather than the top (default) would be simple and effective

> Aleksuei Riabtsev @AleksueiR 10:16
As for being confused, if a user adds a layer and all his points seem to disappear from the map, it's pretty obvious this has something to do with the new layer. I just don't want to introduce inconsistent behaviours.

> James Rae @james-rae 10:20
That makes sense. Could be this is more of a "wait and see" thing...could be worth capturing this conversation in a discussion issue and then let it just linger around.
If no complaints, we claim victory and don't worry 

> Aleksuei Riabtsev @AleksueiR 10:20
I approve the lazy solution.
Still need to modify the demo config though.

**Comment by AleksueiR** [comment]
I think this can be closed - all layers are always added to the top now according to https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2253.
