### ISSUE TITLE
Manitoba 2007-2011 layer bounding box not shown

### ISSUE THREAD

**Issue by IsabellaPan** [fgpv-vpgf/fgpv-vpgf#736]
Manitoba 2007-2011 layer bounding box does not show.
Source cause is bounding box cannot generate from source projection WKID 26914
http://www.agr.gc.ca/atlas/rest/services/imageservices/mb_colour_orthos_50cm/ImageServer

Related to issues https://github.com/fgpv-vpgf/fgpv-vpgf/issues/281 and https://github.com/fgpv-vpgf/fgpv-vpgf/issues/616

![image](https://cloud.githubusercontent.com/assets/18723160/15905761/0ec2b94a-2d84-11e6-9874-6325732433a9.png)

**Comment by mweech** [comment]
Need to update our usage of proj4js in order to support the use of WKT (well known text) based projections, such as the NPRI FGP Service which is using a lambert projection but not using the WKID, instead using the WKT representation of it. Customized projections specified as a WKT are still not officially supported.

#616 and #742 are related.
