### ISSUE TITLE
Zoom to Feature non responsive for NPRI Substance Layer in FGP build

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#742]
Tested on: http://fgpv.cloudapp.net/demo/v0.17.0-1/index-fgp-en.html
~~Linked to: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/736~~
Service URL: http://ec.gc.ca/arcgis/rest/services/NPRI_FGP_All_Layers/MapServer/8

**Zoom to feature" is not responding for this layer in the data table. Projection issue was displayed in the console.**Please investigate

![screenhunter_2233 jun 09 10 33](https://cloud.githubusercontent.com/assets/18539315/15933391/a21d3090-2e2d-11e6-8f42-971bebcea87b.jpg)

![screenhunter_2232 jun 09 09 44](https://cloud.githubusercontent.com/assets/18539315/15933322/586f6daa-2e2d-11e6-9958-6520ca5da80d.jpg)

**Comment by spencerwahl** [comment]
Duplicate #616

**Comment by mweech** [comment]
Need to update our usage of proj4js in order to support the use of WKT (well known text) based projections, such as the NPRI FGP Service which is using a lambert projection but not using the WKID, instead using the WKT representation of it. Customized projections specified as a WKT are still not officially supported.

#616 is related.
