### ISSUE TITLE
Maintain Consistency in Scale/Extent of default Viewer for both French and English version

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#784]
Tested on : V18.0

At present the initial extent and zoom level of viewer is not consistent in English and French version. Please investigate

English version 
![screenhunter_2267 jun 15 13 58](https://cloud.githubusercontent.com/assets/18539315/16091390/65c43a34-3301-11e6-9b17-b833e3ee4bab.jpg)

French Version
![screenhunter_2266 jun 15 13 51](https://cloud.githubusercontent.com/assets/18539315/16091413/7f717c30-3301-11e6-8297-e963a381c963.jpg)

**Comment by cynngah** [comment]
This seems to be another reload service problem and not mercator specific. The same thing happens vice versa if mercator is the initial base map and you reload to lambert.

**Comment by cynngah** [comment]
This issue happens because in bookmarks, the zoom level is stored on basemap switch. However, the scales for the same zoom level is different for different projections (ie. the scale for zoom level 4 for lambert is 17.5million, while for mercator is around 37million).


I wanted to get some feedback because in order to fix this, we would probably have to store scale in the bookmark instead of zoom level, but it makes the bookmark much larger. So the issue is larger bookmark vs. more accurate scale.
