### ISSUE TITLE
On displaying raw html identify results from a wms layer

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#787]
"Grounwater information network" returns the whole page with its own JavaScript and CSS styles which try to take over the page.
![](https://i.imgur.com/KRW2brC.png)

It seems this page also executes its own ajax calls to fetch the data. Also, it cannot be opened in the expanded details panel (getting Error: multipleDefine(…) errors).

I think this can be a security risk as we are executing external JavaScript code. Maybe, instead of trying to render html content inside the details panel, display a link to open a new page with these wms html results.

**Comment by alyec** [comment]
There is potential to run external JS; however, we're also working against a catalogue of services that *should* be safe.  In the case of a user added layer it may be worthwhile to add a warning that pages can basically execute whatever they want (since we communicate over jsonp with a bunch of arcgis stuff it would be pretty easy to setup a malicious arcgis server).

We do have https://github.com/fgpv-vpgf/fgpv-vpgf/issues/427 implemented to allow WMSes to signal that they won't be opening full HTML pages.  That said I don't think wide adoption will be too quick.

**Comment by mweech** [comment]
iframe anyone? :smile:

**Comment by AleksueiR** [comment]
"Grounwater information network" wms results page already uses iframes...

**Comment by mweech** [comment]
Closing the issue.  This service is meant for it's particular use case and is not something we are looking to formally support with RAMP
