### ISSUE TITLE
Add watermark icon/logo to the map

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#832]
Similar to how esri adds it's own logo into the lower right corner of the map, add logo specified in the config (we can have two options in the config: one image to be displayed in the side menu; another, to be added as a watermark) to the map.

**Comment by jolevesq** [comment]
This is how watermark works

If watermark node does not exist, it will take default values from the basemap for text (Copyright Text) and the esri API for the logo and link. For esri basemap it should be the default even if we can overwrite it. For other basemaps like NRCan one, atttribution node must be there because if not it will show esri logo (API default). For blank basemap, nothing must be shown.

Attribution node looks like this:
"attribution": {
            "text": {
                "enabled": true, // true will show text, false will hide text
                "value": "" // if empty, use basemap mapserver default
            },
            "logo": {
                "enabled": true, // true will show logo, false will hide logo
                "value": "", // if empty, use basemap mapserver default
                "link": "" // if empty, use basemap mapserver default
            }
        }

For now, it is implemented in samples/index-fgp-en.html. There is different configuration to see what can be the result. This is the expected results:

Lambert basemap:
first basemap: only text, custom value from configuration file
second basemap: only logo, default value (esri logo)
third basemap: hide logo and show text
fourth basemap: custom text, custom logo (value from configuration file)

Mercator basemap:

first, second  (no attribution node, default value)
third, text and logo enable with default value
fourth: only default logo (esri logo)
fifth: only default text
sixth: nothing

It seems there is a bug when we set text enable true but value is ""... the node display is still none and it should be visible
