### ISSUE TITLE
Fix broken layers on demo pages

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#843]
http://fgpv.cloudapp.net/demo/develop/index-one.html
![](https://i.imgur.com/j1cdsag.png)

**Comment by james-rae** [comment]
The `JOSM` and `Air Ozone` layers were due to ArcGIS migration and are already patched.

The `GeoMet` is failing due to the trailing URL slash being removed from all layers.  Once determined where it's necessary, will stop applying it to layers that dont need it.

The `STB EOS 2014` layer is a tile in the wrong projection. Our code sets the layer to invisible immediately, which then triggers the state transition issue we talked about at the workshop (it never updates, thus never leaves the loading mode on the screen).  @mweech should we prioritize that state transistion fix, or simply remove that tile from the config for now?

**Comment by mweech** [comment]
@james-rae don't prioritize that fix for now.  Initially any tile set would have to be in an FGP approved projection anyhow.  At the very least we can use the hillshade layer.  If we are able to set then we should ser an initial transparency so that layer isnt so confusing.

**Comment by james-rae** [comment]
Sounds good, though for the record, that tile is in an FGP approved projection -- just not the projection we start our app in; if you switch to the ESRI Mercator basemap it shows up just fine.
