### ISSUE TITLE
GeoApi version out of synch with viewer

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#846]
Tested v -18.0-3

There seems to be an issue when a File is imported or a service is added. User is given the message of "Incorrect File format" even when the format is correct. Please investigate

![screenhunter_2326 jun 29 11 18](https://cloud.githubusercontent.com/assets/18539315/16458104/f164ed5a-3deb-11e6-85e6-a5708df2fa9e.jpg)

![screenhunter_2325 jun 29 11 08](https://cloud.githubusercontent.com/assets/18539315/16458115/f96d0280-3deb-11e6-8cd7-b6b55d04f82e.jpg)

**Comment by bkutty** [comment]
The files /Service used for testing were working in the previous build. However Service Layer http://www.agr.gc.ca/atlas/rest/services/mapservices/aafc_census_of_agriculture_2011_ccs/MapServer seems to be working

**Comment by AleksueiR** [comment]
This happened because geoApi was version tagged on individual PR branches, and not on the develop branch.

Here's what I think had happened:

- Person A works on `Feature A`, bumps version to `0.a`, tags it and PRs it (a build labeled `0.a` build is deployed to the cloud and can be referenced by the viewer)
- Person B works on `Feature B` and bump version to `0.b`, tags it, and PRs it (a build labeled `0.b` is deployed to the cloud and can be referenced by the viewer)
- if `Feature B` PR is submitted before `Feature A` PR is merged -> build `0.b` will not have `Feature A` in it.

:point_up: [June 30, 2016 9:02 AM](https://gitter.im/fgpv-vpgf?at=5775187b265214c130af7c84)
Proposal: change the tag structure a bit to include a marker if it is being used for testing only. Examples:
- I create a test version v0.3.0-1+wip which is not merged into geoApi develop
it later gets merged and I tag v0.3.0-2 off the commit which got merged into develop
- So +wip is added for all builds which are not yet merged. No +wip means the tagged commit should be in develop. Also, the viewer's develop branch shouldn't be using a +wip build.

**Comment by mweech** [comment]
this was a process issue, not a software issue.
