### ISSUE TITLE
Loading mode and layer visibility states (for some layers) not maintained while switching projections/bookmarking

### ISSUE THREAD

**Issue by bkutty** [fgpv-vpgf/fgpv-vpgf#847]
Tested on v0.18.0-4

Linked to : https://github.com/fgpv-vpgf/fgpv-vpgf/issues/280
                  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/715
                  https://github.com/fgpv-vpgf/fgpv-vpgf/issues/824

Loading mode is not captured while using the Get Link function or while changing basemaps. Tested using JOSM layer by "Enabling" the snapshot mode.
Layer visibility not maintained for Spatial Density Layer while using Get Link/ changing projections.
Please investigate

**Comment by james-rae** [comment]
The snapshot value issue was twofold.  The legend item was only disabling itself when Snapshot was clicked; it was not updating the snapshot value, so the bookmark would not know it was in snapshot.  Also, when an item was first loaded in snapshot mode, the legend was not disabling the Snapshot button.

The visibility issue was caused by the same situation as seen in https://github.com/fgpv-vpgf/fgpv-vpgf/issues/824 . Had to change the code a bit as the 824 fix only applied itself to layers living in the config file, not layers coming from RCS.
