### ISSUE TITLE
Allow user to import poorly named file (i.e. json file without a .json extension)

### ISSUE THREAD

**Issue by AleksueiR** [fgpv-vpgf/fgpv-vpgf#868]
Requires refactor in geoApi.

Related #770

**Comment by mweech** [comment]
geoApi needs two different entry points, 1 for file based layers and 1 for service based.

**Comment by AleksueiR** [comment]
Have we fixed that?

**Comment by barryytm** [comment]
I just tried it on http://fgpv.cloudapp.net/demo/develop/dev/samples/index-samples.html importing a CSV file with the json format selected.  It did not go to the next step but an error showed up on the console.

![capture](https://user-images.githubusercontent.com/19259169/28726294-af47cada-738e-11e7-9c73-d3cca913fe72.PNG)

![capture2](https://user-images.githubusercontent.com/19259169/28726295-b0611c32-738e-11e7-8062-609778271305.PNG)

**Comment by barryytm** [comment]
Used `.jso` as extension and an error message appeared
![capture](https://user-images.githubusercontent.com/19259169/28726493-77d3100e-738f-11e7-81f9-afaced99e4d4.PNG)

**Comment by AleksueiR** [comment]
Yeap, geoapi is still rejecting files based solemnly on their extensions.

**Comment by james-rae** [comment]
A situation was missed.  Because we are now defaulting on the file check to `geoJson`, any ESRI Server URL hits that default and gets treated as `geoJson`.   
This is due to how the wizard used to behave, where a user would place path to a file sitting on a webserver/url in the Service section of the wizard.  It has since been changed to do this in the File section of the wizard.

Things to update:

in geoApi `layer.js`, make a new function `predictFileUrl`.  Do this by copying the structure of `predictLayerUrlBuilder`.  The new function should only have the file-specific guts of `predictLayerUrlBuilder`.
Then update `predictLayerUrlBuilder` to remove any file-specific things.   
Essentially, you are taking the original predictor (which handled files and services) and are splitting it into two predictors, one for files, one for services.

in viewer, `layer-source.service.js` - `fetchFileInfo` call the new function `predictFileUrl` instead of `predictLayerUrl`
