### ISSUE TITLE
Identify does not Return Results

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#894]
There is a series an uncaught promise errors trying to convert undefined toString when performing Identify clicks on the following service:  http://fgpv.cloudapp.net/demo/develop/samples/index-fgp-en.html?keys=EnergyNA

**Comment by james-rae** [comment]
Our symbology lookup uses attribute field names to determine appropriate pictures when dealing with Class Breaks or Unique Value renderers. 
Results from the identify service presents attributes keyed by their aliases rather than field names (if an alias exists). 
This is the first time we've encountered an aliases field that is used by a renderer.
Quick Fix was to make an un-aliased copy of the attributes to pass to the symbol lookup.
