### ISSUE TITLE
FGP map will error when user-adding ESRI services

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#908]
On the [FGP Page](http://fgpv.cloudapp.net/demo/develop/samples/index-fgp-en.html), open the legend and attempt to add any layer hosted on an ArcGIS Server.

Upon completing step 1, the error `Service Does not Respond` is displayed.

Looking at the console, it appears the code is attempting WMS GetCapabilities calls on the endpoint and failing.

This does not happen in the stand-alone page (`index-one`)

**Comment by james-rae** [comment]
Update - it appears to only be happening the first attempt to load a layer.  A second attempt will go through.  The WMS check is normal; it is supposed to fail and the code should continue on to the next check in determining what the URL points to.  Still unknown why the initial fail is treated as catastrophic, while subsequent fails are handled fine.

**Comment by AleksueiR** [comment]
It fails the first time since `esriRequest` tries to go through proxy which fails with a `403` error.

If a layer from the same domain was loaded previously from the config or rcs, the `GetCapabilities` call never uses proxy.

Sample layer:
http://ec.gc.ca/arcgis/rest/services/EcoGeo/EcoGeo/MapServer

Blank fgp page with no layers loaded:
http://fgpv.cloudapp.net/demo/develop/samples/index-fgp-en.html?

Fgp page with layers from the standard config loaded:
http://fgpv.cloudapp.net/demo/develop/samples/index-fgp-en.html?config=config.en-CA.json


Manually adding the sample layer will fail on the blank page but will pass on the page with layers already loaded.

**Comment by AleksueiR** [comment]
There is no permanent fix for this unless we do https://github.com/fgpv-vpgf/fgpv-vpgf/issues/702.

Aly updated the proxy list to make ec.gc.ca services work for now.
