### ISSUE TITLE
Zoom is not respecting visible scales

### ISSUE THREAD

**Issue by james-rae** [fgpv-vpgf/fgpv-vpgf#949]
To reproduce:

* Add `http://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/CESI_Air_Ozone/MapServer` to the map.  In the wizard, only chose `zoom level 3` during the third step
* Open the grid, and click the zoom glass on a row.  
* Map will zoom in to the very lowest scale.  The feature will appear visible, but it is only the highlight.  A small pan will clear it and no feature will be visible.

Same issue happens for the zoom control in the details panel.

Is confusing to the user because a) the symbol disappears when they pan, and b) highlight is visible but legend indicates layer is off scale.

**Comment by mweech** [comment]
From what I can tell this is specific to Dynamic layer situations, but I could be wrong.  Contrast with functionality for http://fgpv.cloudapp.net/demo/v1.0.0/samples/index-fgp-en.html?keys=ZoomScale in which Zoom to Feature works well.  I think it using the Group Layers minscale instead of the child layer as you can see that it tries to zoom in VERY close to the map and then gets backed out to the Lowest level we allow (as close to 0 as it can get).

"layers": [
  {
   "id": 0,
   "name": "Ozone",
   "parentLayerId": -1,
   "defaultVisibility": true,
   "subLayerIds": [
    1,
    2,
    3,
    4
   ],
   "minScale": 0,
   "maxScale": 0
  },
  {
   "id": 1,
   "name": "zoom level 1",
   "parentLayerId": 0,
   "defaultVisibility": true,
   "subLayerIds": null,
   "minScale": 73957339,
   "maxScale": 25000001
  },
  {
   "id": 2,
   "name": "zoom level 2",
   "parentLayerId": 0,
   "defaultVisibility": true,
   "subLayerIds": null,
   "minScale": 25000000,
   "maxScale": 5000001
  },
  {
   "id": 3,
   "name": "zoom level 3",
   "parentLayerId": 0,
   "defaultVisibility": true,
   "subLayerIds": null,
   "minScale": 5000000,
   "maxScale": 100001
  },
  {
   "id": 4,
   "name": "zoom level 4",
   "parentLayerId": 0,
   "defaultVisibility": true,
   "subLayerIds": null,
   "minScale": 100000,
   "maxScale": 9028
  }
 ],
