### ISSUE TITLE
WMS Legends missing for GeoMet Service

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#951]
Viewer is not displaying legends for layers registered from the GeoMet service:

http://fgpv.cloudapp.net/demo/v1.0.0/samples/index-fgp-en.html?keys=RadarRain,AirTemp

This is because Geomet has a trailing slash on it's WMS link, and this is being stripped off.  Need to make sure we respect the OnlineResource value as specified in the GetCapabilities document (http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities).

**Comment by james-rae** [comment]
Trailing slash is present, and is not the cause of the issue.

Issue is due to [the legend url scraper](https://github.com/fgpv-vpgf/geoApi/blob/v1.0.0/src/layer/ogc.js#L140) assuming the array of [layerInfos](https://developers.arcgis.com/javascript/3/jsapi/wmslayerinfo-amd.html) is flat.  

The geomet layers return nested structures.  E.g. to get the temperature legend url, you would have to go `layer.layerInfos[6].subLayers[1].subLayers[3].legendUrl`.

Need to enhance the function to recursively crawl the `layerInfos` to extract all buried legends.

Will boost the estimate as it is no longer a matter of not truncating a `/`
