### ISSUE TITLE
Make material color scheme configurable/override able

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#967]
Use new gcgeo color scheme as a sample..

**Comment by ShrutiVellanki** [comment]
From discussion with @AleksueiR a decision was made to scrap this for the following reasons: 

- As part of our efforts to reduce the size of the bundle, we are going to disable theme support, at least at run time. Third item from the bottom in fgpv-vpgf/fgpv-vpgf#2562
- According [to this document](https://material.angularjs.org/latest/Theming/05_under_the_hood) AngularJS uses a runtime function `generateAllThemes()` to generate `<style>` tags added to the `head` of the application
- This makes it difficult to pre-compile themes as an alternate solution, (for example using `npm run build-theme my-palette.css`) which would have made it easier for the user to load a CSS files onto a page containing RAMP in order to override the default theme

Thus is looks like disabling theme support at run time would also make it difficult to override the default material colour scheme

**Comment by dane-thomas** [comment]
There is a workaround available provided by #2886. With the custom angular material build a user could specify the theme they want and rebuild it. This does require the user to build and deploy RAMP themselves. This also pre-compiles the theme making any runtime theme changes difficult.
