### ISSUE TITLE
Investigate options for exception management and logging libraries

### ISSUE THREAD

**Issue by mweech** [fgpv-vpgf/fgpv-vpgf#981]

**Comment by milesap** [comment]
See #1702 for current implementation. Replace `RV.logManager` with an actual logging lib.

**Comment by milesap** [comment]
Do we plan on uploading certain log messages/exceptions to a server for reporting or is this strictly client-side?

**Comment by alyec** [comment]
Logging serious errors with a server would be nice, but just getting a logging library will be a big improvement to start with.  For general logging I think a server is overkill in our case.

Is the tradeoff that we can get a better library if we ignore remote logging?

**Comment by milesap** [comment]
Some libraries are better suited for remote logging, some are easier to use for client side implementations. I think we should list out our logging/exception management requirements so that it is easy to choose one library over another. Would be good to know how we will be leveraging the library - we can discuss at code review today.
